#!/usr/bin/env python3
"""
Combined ANC hotfix generator.

Auto-detects what needs a hotfix and generates the version numbers for it:

1. If aks-node-controller/ (the Go module) has changes other than *_test.go or
   testdata files vs the base branch, bumps the patch of the current
   pkg/agent/datamodel/linux_sig_version.json version and uses it as `version`.

2. Detects which CSE provisioning scripts changed vs the base branch, injects their
   write_files entries into the EnableScriptlessCSECmd section of
   parts/linux/cloud-init/nodecustomdata.yml, and generates a matching ANC-owned
   embedded payload. If that injection (or a direct edit) leaves nodecustomdata.yml
   different from the base branch, `scripts_version` is bumped using the same
   base-version + tag-collision algorithm as `version`.

3. Writes the resulting {"version", "scripts_version"} (omitting fields that don't
   apply) to parts/linux/cloud-init/artifacts/aks-node-controller-hotfix.json only
   when there is an active hotfix. If no hotfix applies, the file is removed/left
   absent so scriptless customData does not embed an empty hotfix artifact.

Usage: python3 hotfix/hotfix_generate.py [--embedded-only] <base_ref>
  base_ref: git ref to diff against for changed-script/changed-code detection
            (e.g., origin/official/v20260219)
  --embedded-only: omit the legacy CRP script block. This is intentionally
                   default-off until 15 supported-version rotations complete
                   and the oldest supported ABSvc/VHD release is confirmed
                   embedded-capable.

This script is called by the hotfix-generate GH Action.
"""

import argparse
import json
import os
import re
import shutil
import subprocess
import sys

TARGET_FILE = "parts/linux/cloud-init/artifacts/aks-node-controller-hotfix.json"
TEMPLATE = "parts/linux/cloud-init/nodecustomdata.yml"
ARTIFACTS_DIR = "parts/linux/cloud-init/artifacts"
LINUX_SIG_VERSION_FILE = "pkg/agent/datamodel/linux_sig_version.json"
ANC_DIR = "aks-node-controller/"
GENERATED_DIR = os.path.join(ANC_DIR, "scripthotfix", "generated")
GENERATED_MANIFEST = os.path.join(GENERATED_DIR, "manifest.json")
GENERATED_PAYLOADS_DIR = os.path.join(GENERATED_DIR, "payloads")
MANIFEST_SCHEMA_VERSION = 1

VERSION_RE = re.compile(r'^\d{6}\.\d{2}\.\d+$')

# Marker comments for idempotent injection of the raw changed-script blocks.
SCRIPTS_BEGIN = "# ---- hotfix-scripts: auto-generated ----"
SCRIPTS_END = "# ---- end hotfix-scripts ----"
LEGACY_SCRIPTS_BEGIN = "# ---- hotfix: auto-generated by hotfix-generate GH Action ----"
LEGACY_SCRIPTS_END = "# ---- end hotfix ----"

# Map from source file paths (relative to artifacts/) to the GetVariableProperty
# keys used in nodecustomdata.yml. Only scripts that appear as write_files entries
# in the traditional section are included.
SOURCE_TO_VARKEY = {
    # CSE helpers — base (non-distro)
    "cse_helpers.sh": "provisionSource",
    # CSE helpers — distro variants (all map to the same conditional block)
    "ubuntu/cse_helpers_ubuntu.sh": "provisionSourceUbuntu",
    "mariner/cse_helpers_mariner.sh": "provisionSourceMariner",
    "azlosguard/cse_helpers_osguard.sh": "provisionSourceAzlOSGuard",
    "flatcar/cse_helpers_flatcar.sh": "provisionSourceFlatcar",
    "acl/cse_helpers_acl.sh": "provisionSourceACL",
    # CSE install — base
    "cse_install.sh": "provisionInstalls",
    # CSE install — distro variants
    "ubuntu/cse_install_ubuntu.sh": "provisionInstallsUbuntu",
    "mariner/cse_install_mariner.sh": "provisionInstallsMariner",
    "azlosguard/cse_install_osguard.sh": "provisionInstallsAzlOSGuard",
    "flatcar/cse_install_flatcar.sh": "provisionInstallsFlatcar",
    "acl/cse_install_acl.sh": "provisionInstallsACL",
    # CSE config
    "cse_config.sh": "provisionConfigs",
    # CSE main / start
    "cse_main.sh": "provisionScript",
    "cse_start.sh": "provisionStartScript",
    # Python scripts
    "cse_redact_cloud_config.py": "provisionRedactCloudConfig",
    "cse_send_logs.py": "provisionSendLogs",
    # Other scripts
    "reconcile-private-hosts.sh": "reconcilePrivateHostsScript",
    "bind-mount.sh": "bindMountScript",
    "mig-partition.sh": "migPartitionScript",
    "enable-dhcpv6.sh": "dhcpv6ConfigurationScript",
    "ensure_imds_restriction.sh": "ensureIMDSRestrictionScript",
    "ensure-no-dup.sh": "ensureNoDupEbtablesScript",
    "cloud-init-status-check.sh": "cloudInitStatusCheckScript",
    "measure-tls-bootstrapping-latency.sh": "measureTLSBootstrappingLatencyScript",
    "validate-kubelet-credentials.sh": "validateKubeletCredentialsScript",
    "setup-custom-search-domains.sh": "customSearchDomainsScript",
    "configure-azure-network.sh": "configureAzureNetworkScript",
    "init-aks-custom-cloud.sh": "initAKSCustomCloud",
    "init-aks-cloud.sh": "initAKSCloud",
    # Distro-specific scripts
    "ubuntu/ubuntu-snapshot-update.sh": "snapshotUpdateScript",
    "mariner/mariner-package-update.sh": "packageUpdateScriptMariner",
    # Systemd services
    "kubelet.service": "kubeletSystemdService",
    "reconcile-private-hosts.service": "reconcilePrivateHostsService",
    "bind-mount.service": "bindMountSystemdService",
    "dhcpv6.service": "dhcpv6SystemdService",
    "mig-partition.service": "migPartitionSystemdService",
    "secure-tls-bootstrap.service": "secureTLSBootstrapService",
    "ensure-no-dup.service": "ensureNoDupEbtablesService",
    "measure-tls-bootstrapping-latency.service": "measureTLSBootstrappingLatencyService",
    "ubuntu/snapshot-update.service": "snapshotUpdateService",
    "ubuntu/snapshot-update.timer": "snapshotUpdateTimer",
    "mariner/package-update.service": "packageUpdateServiceMariner",
    "mariner/package-update.timer": "packageUpdateTimerMariner",
    "99-azure-network.rules": "azureNetworkUdevRule",
    # Component manifest
    "manifest.json": "componentManifestFile",
}

# Distro-variant variable keys that share a single conditional write_files block.
# When any variant in a group changes, the entire block (with all conditionals) is injected.
VARKEY_TO_BLOCK_GROUP = {
    "provisionSourceUbuntu": "helpers_distro",
    "provisionSourceMariner": "helpers_distro",
    "provisionSourceAzlOSGuard": "helpers_distro",
    "provisionSourceFlatcar": "helpers_distro",
    "provisionSourceACL": "helpers_distro",
    "provisionInstallsUbuntu": "install_distro",
    "provisionInstallsMariner": "install_distro",
    "provisionInstallsAzlOSGuard": "install_distro",
    "provisionInstallsFlatcar": "install_distro",
    "provisionInstallsACL": "install_distro",
}

VARKEY_TO_SOURCE = {varkey: source for source, varkey in SOURCE_TO_VARKEY.items()}

HOTFIXABLE_SUFFIXES = (
    ".sh",
    ".py",
    ".service",
    ".timer",
    ".rules",
)
GENERATED_ARTIFACTS = {
    "aks-node-controller-hotfix.json",
}

# Runtime path helpers used by nodecustomdata.yml. Platform applicability is
# deliberately parsed from the template itself rather than duplicated here.
TEMPLATE_PATH_HELPERS = {
    "GetCSEHelpersScriptFilepath": "/opt/azure/containers/provision_source.sh",
    "GetCSEHelpersScriptDistroFilepath": "/opt/azure/containers/provision_source_distro.sh",
    "GetCSEInstallScriptFilepath": "/opt/azure/containers/provision_installs.sh",
    "GetCSEInstallScriptDistroFilepath": "/opt/azure/containers/provision_installs_distro.sh",
    "GetCSEConfigScriptFilepath": "/opt/azure/containers/provision_configs.sh",
    "GetInitAKSCloudFilepath": "/opt/azure/containers/init-aks-cloud.sh",
    "GetInitAKSCustomCloudFilepath": "/opt/azure/containers/init-aks-custom-cloud.sh",
    "GetCustomSearchDomainsCSEScriptFilepath": "/opt/azure/containers/setup-custom-search-domains.sh",
    "GetDHCPv6ServiceCSEScriptFilepath": "/etc/systemd/system/dhcpv6.service",
    "GetDHCPv6ConfigCSEScriptFilepath": "/opt/azure/containers/enable-dhcpv6.sh",
}

ALL_PLATFORMS = ("ubuntu", "mariner", "azlosguard", "flatcar", "acl")
PLATFORM_PREDICATES = {
    "ubuntu": set(),
    "mariner": {"IsMariner"},
    "azlosguard": {"IsMariner", "IsAzlOSGuard"},
    "flatcar": {"IsFlatcar"},
    "acl": {"IsACL"},
}
PLATFORM_TOKENS = frozenset({
    "IsACL",
    "IsAzlOSGuard",
    "IsMariner",
    "IsFlatcar",
})


class GenerationError(RuntimeError):
    """Raised when hotfix assets cannot be generated safely."""


def validate_source_mappings():
    """Validate the explicit hotfixable source allowlist."""
    if len(VARKEY_TO_SOURCE) != len(SOURCE_TO_VARKEY):
        raise GenerationError("source mappings contain duplicate variable keys")
    for varkey in VARKEY_TO_BLOCK_GROUP:
        if varkey not in VARKEY_TO_SOURCE:
            raise GenerationError(
                f"distro block variable key {varkey} has no source mapping"
            )


def read_base_version():
    """Read the current released VHD image version, e.g. '202607.02.0'."""
    with open(LINUX_SIG_VERSION_FILE) as f:
        data = json.load(f)
    version = (data.get("version") or "").strip()
    if not VERSION_RE.match(version):
        print(f"ERROR: {LINUX_SIG_VERSION_FILE} has invalid version '{version}', "
              f"expected YYYYMM.DD.PATCH", file=sys.stderr)
        sys.exit(1)
    return version


def tag_exists(tag):
    """Check whether a git tag already exists (locally)."""
    result = subprocess.run(
        ["git", "rev-parse", "-q", "--verify", f"refs/tags/{tag}"],
        capture_output=True,
    )
    return result.returncode == 0


def bump_version(base_version):
    """Bump base_version's patch to the first patch number not already tagged.

    base_version is 'YYYYMM.DD.PATCH' (e.g. '202607.02.0'). Tags are
    'v0.YYYYMMDD.PATCH' (e.g. 'v0.20260702.1'). Returns the new
    'YYYYMM.DD.PATCH' string.
    """
    match = re.match(r'^(\d{6})\.(\d{2})\.\d+$', base_version)
    yyyymm, dd = match.group(1), match.group(2)
    patch = 1
    while True:
        tag = f"v0.{yyyymm}{dd}.{patch}"
        if not tag_exists(tag):
            return f"{yyyymm}.{dd}.{patch}"
        patch += 1


def path_changed(base_ref, *paths):
    """Return True if any selected path differs from the working tree and base_ref."""
    result = subprocess.run(["git", "diff", "--quiet", base_ref, "--", *paths])
    if result.returncode == 0:
        return False
    if result.returncode == 1:
        return True
    raise subprocess.CalledProcessError(result.returncode, result.args)


def write_hotfix_file(version, scripts_version):
    """Write the resolved {version, scripts_version} to TARGET_FILE when active.

    When no hotfix applies, remove TARGET_FILE if present. An empty JSON object is
    still embedded as a real scriptless customData file, which changes payload
    shape even though there is no hotfix for the wrapper to consume.
    """
    payload = {}
    if version:
        payload["version"] = version
    if scripts_version:
        payload["scripts_version"] = scripts_version

    if payload:
        with open(TARGET_FILE, "w") as f:
            json.dump(payload, f, indent=4)
            f.write("\n")
        print(f"Wrote {payload} to {TARGET_FILE}", file=sys.stderr)
        return

    try:
        os.remove(TARGET_FILE)
        print(f"No active hotfix; removed {TARGET_FILE}", file=sys.stderr)
    except FileNotFoundError:
        print(f"No active hotfix; {TARGET_FILE} already absent", file=sys.stderr)


def detect_changed_varkeys(base_ref, available_varkeys=None):
    """Detect changed scripts via git diff and return the set of varkeys to inject."""
    result = subprocess.run(
        ["git", "diff", "--name-only", base_ref, "--", f"{ARTIFACTS_DIR}/"],
        capture_output=True, text=True, check=True,
    )
    changed_files = result.stdout.strip()
    if not changed_files:
        print("No changed scripts detected. Nothing to do.")
        return set()

    print("Changed files:")
    print(changed_files)
    print()

    matched_varkeys = set()
    matched_block_groups = set()

    for filepath in changed_files.splitlines():
        local_path = filepath.removeprefix(f"{ARTIFACTS_DIR}/")
        if local_path in GENERATED_ARTIFACTS:
            continue
        if local_path in SOURCE_TO_VARKEY:
            source_path = os.path.join(ARTIFACTS_DIR, local_path)
            if not os.path.isfile(source_path):
                raise GenerationError(
                    f"changed hotfix source {local_path} does not exist at {source_path}"
                )
            varkey = SOURCE_TO_VARKEY[local_path]
            matched_varkeys.add(varkey)
            if varkey in VARKEY_TO_BLOCK_GROUP:
                matched_block_groups.add(VARKEY_TO_BLOCK_GROUP[varkey])
            print(f"  Matched: {local_path} → {varkey}")
        elif local_path.endswith(HOTFIXABLE_SUFFIXES) or local_path == "manifest.json":
            raise GenerationError(
                f"changed hotfixable artifact {local_path} has no source/runtime mapping"
            )
        else:
            print(f"  Warning: {local_path} has no mapping in SOURCE_TO_VARKEY (skipped)")

    if not matched_varkeys:
        print("No matched variable keys. Nothing to inject.")
        return set()

    # If a distro block group was matched, add all members of that group
    for varkey, group in VARKEY_TO_BLOCK_GROUP.items():
        if (
            group in matched_block_groups
            and (available_varkeys is None or varkey in available_varkeys)
        ):
            matched_varkeys.add(varkey)

    for varkey in matched_varkeys:
        source = VARKEY_TO_SOURCE.get(varkey)
        if not source:
            raise GenerationError(f"variable key {varkey} has no source mapping")
        source_path = os.path.join(ARTIFACTS_DIR, source)
        if not os.path.isfile(source_path):
            raise GenerationError(
                f"selected hotfix source {source} does not exist at {source_path}"
            )

    print(f"\nVariable keys to inject: {' '.join(sorted(matched_varkeys))}")
    return matched_varkeys


def find_block_boundaries(lines):
    """Find the EnableScriptlessCSECmd / else / end block boundaries."""
    scriptless_start = None
    else_line = None
    end_line = None

    for i, line in enumerate(lines):
        stripped = line.strip()
        if '{{if EnableScriptlessCSECmd}}' in stripped or '{{ if EnableScriptlessCSECmd }}' in stripped:
            scriptless_start = i
            break

    if scriptless_start is None:
        return None, None, None

    depth = 0
    for i in range(scriptless_start, len(lines)):
        stripped = lines[i].strip()
        if re.match(r'\{\{-?\s*if(?:\s+|$)', stripped):
            depth += 1
            continue
        if (
            depth == 1
            and else_line is None
            and re.match(r'\{\{-?\s*else\s*-?\}\}$', stripped)
        ):
            else_line = i
            continue
        if re.match(r'\{\{-?\s*end\s*-?\}\}$', stripped):
            depth -= 1
            if depth == 0:
                end_line = i
                break

    return scriptless_start, else_line, end_line


def parse_write_files_blocks(traditional_lines):
    """Parse write_files blocks from the traditional section.

    Each block is either a simple '- path:' entry or an entire conditional
    block (e.g., {{if IsAzlOSGuard}}...{{end}}) treated as a single unit.

    Returns a list of (varkeys_set, lines_list) tuples.
    """
    blocks = []
    current_block = []
    current_varkeys = set()
    in_block = False
    conditional_depth = 0

    for line in traditional_lines:
        stripped = line.strip()

        # Track conditional nesting depth
        if re.match(r'\{\{-?\s*if\s+', stripped):
            conditional_depth += 1
        if re.match(r'\{\{-?\s*end\s*-?\}\}', stripped):
            conditional_depth -= 1

        # Detect start of a new top-level write_files entry
        is_path_line = stripped.startswith('- path:')
        # Distro conditionals in the template are unindented, while nested
        # conditionals inside write_files entries are indented.
        is_unindented = not line[0:1].isspace() if line else False
        is_conditional_start = (conditional_depth == 1 and is_unindented and re.match(r'\{\{-?\s*if\s+', stripped))

        start_new = False
        if conditional_depth == 0 and is_path_line:
            start_new = True
        elif is_conditional_start:
            start_new = True

        if start_new:
            if current_block and current_varkeys:
                blocks.append((current_varkeys.copy(), list(current_block)))
            current_block = []
            current_varkeys = set()
            in_block = True

        if in_block:
            current_block.append(line)
            match = re.search(r'GetVariableProperty\s+"cloudInitData"\s+"(\w+)"', stripped)
            if match:
                current_varkeys.add(match.group(1))

    if current_block and current_varkeys:
        blocks.append((current_varkeys.copy(), list(current_block)))

    return blocks


def parse_write_file_entries(traditional_lines):
    """Parse runtime metadata from traditional nodecustomdata write_files entries.

    Platform selectors are evaluated from the existing template condition chain,
    including compound and negated expressions used by older official branches.
    Non-platform conditions do not change OS applicability.
    """
    entries = []
    active_platforms = set(ALL_PLATFORMS)
    conditional_stack = []
    current = None

    def finish_current():
        nonlocal current
        if current is None:
            return
        if current.get("varkey"):
            if not current.get("permissions"):
                raise GenerationError(
                    f"write_files entry for {current['varkey']} has no permissions"
                )
            entries.append(current)
        current = None

    for line in traditional_lines:
        stripped = line.strip()

        template_if = re.match(r'\{\{-?\s*if\s+(.+?)\s*-?\}\}', stripped)
        template_else_if = re.match(
            r'\{\{-?\s*else\s+if\s+(.+?)\s*-?\}\}',
            stripped,
        )
        template_else = re.match(r'\{\{-?\s*else\s*-?\}\}', stripped)
        template_end = re.match(r'\{\{-?\s*end\s*-?\}\}', stripped)

        if template_if:
            finish_current()
            expression = template_if.group(1)
            matching = evaluate_platform_expression(expression)
            frame = {
                "parent": set(active_platforms),
                "platform_condition": matching is not None,
            }
            if matching is not None:
                frame["remaining"] = active_platforms - matching
                active_platforms &= matching
            conditional_stack.append(frame)
            continue
        if template_else_if:
            finish_current()
            if not conditional_stack:
                raise GenerationError("template else-if has no matching if")
            frame = conditional_stack[-1]
            if frame["platform_condition"]:
                matching = evaluate_platform_expression(
                    template_else_if.group(1)
                )
                if matching is None:
                    raise GenerationError(
                        "platform conditional chain contains an unsupported "
                        f"else-if expression {template_else_if.group(1)!r}"
                    )
                active_platforms = frame["remaining"] & matching
                frame["remaining"] -= matching
            continue
        if template_else:
            finish_current()
            if not conditional_stack:
                raise GenerationError("template else has no matching if")
            frame = conditional_stack[-1]
            if frame["platform_condition"]:
                active_platforms = set(frame["remaining"])
            continue
        if template_end:
            finish_current()
            if not conditional_stack:
                raise GenerationError("template end has no matching if")
            frame = conditional_stack.pop()
            active_platforms = frame["parent"]
            continue

        if stripped.startswith("- path:"):
            finish_current()
            current = {
                "path": stripped.removeprefix("- path:").strip(),
                "platforms": tuple(
                    platform
                    for platform in ALL_PLATFORMS
                    if platform in active_platforms
                ),
            }
            continue
        if current is None:
            continue

        permissions = re.match(r'permissions:\s*["\']?([0-7]+)["\']?', stripped)
        if permissions:
            current["permissions"] = permissions.group(1)
        varkey = re.search(
            r'GetVariableProperty\s+"cloudInitData"\s+"(\w+)"',
            stripped,
        )
        if varkey:
            current["varkey"] = varkey.group(1)

    finish_current()
    return entries


def evaluate_platform_expression(expression):
    """Evaluate a supported Go-template expression for each concrete platform.

    Returns None when the expression does not reference platform predicates.
    """
    tokens = re.findall(r'[()]|[A-Za-z][A-Za-z0-9]*', expression)
    if not PLATFORM_TOKENS.intersection(tokens):
        return None

    def parse(index, predicates, stop_at_paren=False):
        if index >= len(tokens):
            raise GenerationError(
                f"incomplete platform expression {expression!r}"
            )
        token = tokens[index]
        if token == "(":
            value, index = parse(index + 1, predicates, stop_at_paren=True)
            if index >= len(tokens) or tokens[index] != ")":
                raise GenerationError(
                    f"unbalanced platform expression {expression!r}"
                )
            return value, index + 1
        if token == "not":
            value, index = parse(index + 1, predicates)
            return not value, index
        if token in ("or", "and"):
            values = []
            index += 1
            while index < len(tokens) and (
                not stop_at_paren or tokens[index] != ")"
            ):
                value, index = parse(index, predicates)
                values.append(value)
            if len(values) < 2:
                raise GenerationError(
                    f"operator {token!r} needs at least two operands in "
                    f"{expression!r}"
                )
            return (
                any(values) if token == "or" else all(values)
            ), index
        if token in PLATFORM_TOKENS:
            return token in predicates, index + 1
        raise GenerationError(
            f"unsupported token {token!r} in platform expression {expression!r}"
        )

    matching = set()
    for platform, predicates in PLATFORM_PREDICATES.items():
        value, next_index = parse(0, predicates)
        if next_index != len(tokens):
            raise GenerationError(
                f"trailing tokens in platform expression {expression!r}"
            )
        if value:
            matching.add(platform)
    return matching


def resolve_runtime_path(path_expression):
    """Resolve a literal path or a known nodecustomdata template path helper."""
    if path_expression.startswith("/"):
        if (
            "\\" in path_expression
            or ".." in path_expression.split("/")
            or os.path.normpath(path_expression).replace("\\", "/")
            != path_expression
        ):
            raise GenerationError(
                f"unsafe runtime path expression {path_expression!r}"
            )
        return path_expression

    helper_match = re.fullmatch(r'\{\{\s*(\w+)\s*\}\}', path_expression)
    if not helper_match:
        raise GenerationError(
            f"unsupported runtime path expression {path_expression!r}"
        )
    helper = helper_match.group(1)
    destination = TEMPLATE_PATH_HELPERS.get(helper)
    if not destination:
        raise GenerationError(f"unresolved runtime path helper {helper}")
    return destination


def build_manifest_entries(target_varkeys, traditional_lines):
    """Build deterministic manifest entries from selected template write_files."""
    parsed_entries = parse_write_file_entries(traditional_lines)
    by_varkey = {}
    for parsed in parsed_entries:
        varkey = parsed["varkey"]
        if varkey in by_varkey:
            raise GenerationError(
                f"template contains multiple write_files entries for {varkey}"
            )
        by_varkey[varkey] = parsed

    manifest_entries = []
    selected_destinations = {platform: {} for platform in ALL_PLATFORMS}
    for varkey in sorted(target_varkeys):
        source = VARKEY_TO_SOURCE.get(varkey)
        if not source:
            raise GenerationError(f"variable key {varkey} has no source mapping")
        parsed = by_varkey.get(varkey)
        if not parsed:
            raise GenerationError(
                f"changed source {source} maps to {varkey}, but the traditional "
                f"{TEMPLATE} section has no matching write_files entry"
            )

        destination = resolve_runtime_path(parsed["path"])
        if not destination.startswith("/") or ".." in destination.split("/"):
            raise GenerationError(
                f"unsafe runtime destination {destination!r} for {source}"
            )
        mode = parsed["permissions"]
        try:
            parsed_mode = int(mode, 8)
        except ValueError as err:
            raise GenerationError(f"invalid mode {mode!r} for {source}") from err
        if parsed_mode <= 0 or parsed_mode > 0o777:
            raise GenerationError(f"invalid mode {mode!r} for {source}")

        source_path = os.path.join(ARTIFACTS_DIR, source)
        if not os.path.isfile(source_path):
            raise GenerationError(
                f"selected hotfix source {source} does not exist at {source_path}"
            )

        platforms = parsed["platforms"]
        if not platforms:
            raise GenerationError(
                f"template entry for {source} does not apply to any platform"
            )
        for platform in platforms:
            previous = selected_destinations[platform].get(destination)
            if previous:
                raise GenerationError(
                    f"duplicate runtime destination {destination} for platform "
                    f"{platform}: {previous} and {source}"
                )
            selected_destinations[platform][destination] = source

        manifest_entries.append({
            "source": source,
            "payload": f"payloads/{source}",
            "destination": destination,
            "mode": mode.zfill(4),
            "platforms": list(platforms),
        })

    return manifest_entries


def write_embedded_payload(entries):
    """Write a stable embedded manifest and only its selected source payloads."""
    shutil.rmtree(GENERATED_PAYLOADS_DIR, ignore_errors=True)
    os.makedirs(GENERATED_DIR, exist_ok=True)

    for entry in entries:
        source_path = os.path.join(ARTIFACTS_DIR, entry["source"])
        payload_path = os.path.join(GENERATED_DIR, *entry["payload"].split("/"))
        os.makedirs(os.path.dirname(payload_path), exist_ok=True)
        shutil.copyfile(source_path, payload_path)

    manifest = {
        "schema_version": MANIFEST_SCHEMA_VERSION,
        "entries": entries,
    }
    with open(GENERATED_MANIFEST, "w", newline="\n") as manifest_file:
        json.dump(manifest, manifest_file, indent=2)
        manifest_file.write("\n")
    print(
        f"Wrote {len(entries)} embedded hotfix entries to {GENERATED_MANIFEST}",
        file=sys.stderr,
    )


def read_existing_crp_varkeys():
    """Return varkeys from an already-active generated CRP script block."""
    with open(TEMPLATE) as template_file:
        content = template_file.read()
    varkeys = set()
    for begin, end in (
        (SCRIPTS_BEGIN, SCRIPTS_END),
        (LEGACY_SCRIPTS_BEGIN, LEGACY_SCRIPTS_END),
    ):
        match = re.search(
            rf'{re.escape(begin)}\n(.*?){re.escape(end)}',
            content,
            flags=re.DOTALL,
        )
        if match:
            varkeys.update(re.findall(
                r'GetVariableProperty\s+"cloudInitData"\s+"(\w+)"',
                match.group(1),
            ))
    return varkeys


def read_existing_manifest_varkeys():
    """Return varkeys from the checked-in generated manifest, if present."""
    try:
        with open(GENERATED_MANIFEST) as manifest_file:
            manifest = json.load(manifest_file)
    except FileNotFoundError:
        return set()
    if manifest.get("schema_version") != MANIFEST_SCHEMA_VERSION:
        raise GenerationError(
            f"{GENERATED_MANIFEST} has unsupported schema version"
        )

    varkeys = set()
    for entry in manifest.get("entries", []):
        source = entry.get("source")
        varkey = SOURCE_TO_VARKEY.get(source)
        if not varkey:
            raise GenerationError(
                f"existing embedded source {source!r} has no variable mapping"
            )
        varkeys.add(varkey)
    return varkeys


def remove_scripts_block():
    """Remove any previously injected hotfix-scripts block (idempotent cleanup)."""
    with open(TEMPLATE) as f:
        content = f.read()

    new_content = remove_generated_scripts_blocks(content)

    if new_content != content:
        with open(TEMPLATE, 'w') as f:
            f.write(new_content)
        print(f"Removed previous hotfix-scripts block from {TEMPLATE}", file=sys.stderr)
        return True
    return False


def remove_generated_scripts_blocks(content):
    """Remove current and legacy generated hotfix blocks."""
    for begin, end in (
        (SCRIPTS_BEGIN, SCRIPTS_END),
        (LEGACY_SCRIPTS_BEGIN, LEGACY_SCRIPTS_END),
    ):
        content = re.sub(
            rf'{re.escape(begin)}\n.*?{re.escape(end)}\n?',
            '',
            content,
            flags=re.DOTALL,
        )
    return content


def inject_scripts(target_varkeys):
    """Extract matching write_files blocks from the traditional section and inject
    them into the scriptless section, replacing any previously injected block."""
    with open(TEMPLATE, 'r') as f:
        content = f.read()

    content = remove_generated_scripts_blocks(content)

    lines = content.splitlines(keepends=True)

    scriptless_start, else_line, end_line = find_block_boundaries(lines)
    if scriptless_start is None or else_line is None or end_line is None:
        print("ERROR: Could not find EnableScriptlessCSECmd block boundaries", file=sys.stderr)
        print(f"  scriptless_start={scriptless_start}, else_line={else_line}, end_line={end_line}", file=sys.stderr)
        sys.exit(1)

    print("\nTemplate structure:", file=sys.stderr)
    print(f"  EnableScriptlessCSECmd block: lines {scriptless_start+1}-{else_line+1}", file=sys.stderr)
    print(f"  Traditional block: lines {else_line+2}-{end_line+1}", file=sys.stderr)

    traditional_lines = lines[else_line+1:end_line]
    blocks = parse_write_files_blocks(traditional_lines)
    print(f"Found {len(blocks)} write_files blocks in traditional section", file=sys.stderr)

    selected_blocks = []
    for varkeys, block_lines in blocks:
        if varkeys & target_varkeys:
            selected_blocks.append(block_lines)
            print(f"  Selected block with varkeys: {varkeys}", file=sys.stderr)

    if not selected_blocks:
        print("No matching write_files blocks found for the target varkeys.", file=sys.stderr)
        return False

    scripts_lines = [
        "\n",
        f"{SCRIPTS_BEGIN}\n",
    ]
    for block_lines in selected_blocks:
        scripts_lines.extend(block_lines)
    scripts_lines.append(f"{SCRIPTS_END}\n")

    final_lines = lines[:else_line] + scripts_lines + lines[else_line:]

    with open(TEMPLATE, 'w') as f:
        f.writelines(final_lines)

    print(f"\nInjected {len(selected_blocks)} write_files block(s) into EnableScriptlessCSECmd section", file=sys.stderr)
    print(f"Updated {TEMPLATE}", file=sys.stderr)
    return True


def main():
    parser = argparse.ArgumentParser(description="Generate ANC hotfix assets")
    parser.add_argument(
        "--embedded-only",
        action="store_true",
        help="omit legacy CRP script injection (default-off compatibility switch)",
    )
    parser.add_argument("base_ref", help="git ref to diff against")
    args = parser.parse_args()
    base_ref = args.base_ref

    # Best-effort: make sure locally-known tags are up to date before checking for
    # collisions. Ignore failures (e.g. no network) and fall back to local tags.
    subprocess.run(["git", "fetch", "--tags"], capture_output=True)

    try:
        validate_source_mappings()
        with open(TEMPLATE, "r") as template_file:
            template_lines = template_file.readlines()
        _, else_line, end_line = find_block_boundaries(template_lines)
        if else_line is None or end_line is None:
            raise GenerationError(
                f"could not find traditional write_files section in {TEMPLATE}"
            )
        traditional_lines = template_lines[else_line + 1:end_line]
        available_varkeys = {
            entry["varkey"]
            for entry in parse_write_file_entries(traditional_lines)
        }

        # Preserve all active fixes while adding newly changed scripts. Removing
        # an active hotfix requires a separate, explicit retirement after the
        # supported VHD window.
        existing_varkeys = (
            read_existing_crp_varkeys()
            | read_existing_manifest_varkeys()
        )
        changed_varkeys = detect_changed_varkeys(
            base_ref,
            available_varkeys=available_varkeys,
        )
        target_varkeys = existing_varkeys | changed_varkeys

        manifest_entries = build_manifest_entries(
            target_varkeys,
            traditional_lines,
        ) if target_varkeys else []
        write_embedded_payload(manifest_entries)

        if target_varkeys and not args.embedded_only:
            if not inject_scripts(target_varkeys):
                raise GenerationError("failed to inject selected legacy CRP scripts")
        else:
            remove_scripts_block()
    except GenerationError as err:
        print(f"ERROR: {err}", file=sys.stderr)
        sys.exit(1)

    base_version = read_base_version()

    version = ""
    if path_changed(
        base_ref,
        ANC_DIR,
        f":(exclude,glob){ANC_DIR}**/*_test.go",
        f":(exclude,glob){ANC_DIR}**/testdata/**",
    ):
        version = bump_version(base_version)
        print(f"aks-node-controller/ production files changed vs {base_ref}; "
              f"version={version}", file=sys.stderr)
    else:
        print(f"aks-node-controller/ has no production changes vs {base_ref}; "
              "version not set", file=sys.stderr)

    scripts_version = ""
    if path_changed(base_ref, TEMPLATE):
        scripts_version = bump_version(base_version)
        print(f"{TEMPLATE} changed vs {base_ref}; scripts_version={scripts_version}", file=sys.stderr)
    else:
        print(f"{TEMPLATE} unchanged vs {base_ref}; scripts_version not set", file=sys.stderr)

    write_hotfix_file(version, scripts_version)


if __name__ == '__main__':
    main()
