oom_score = -999
version = 4

[metrics]
  address = "0.0.0.0:10257"

[plugins."io.containerd.cri.v1.images".pinned_images]
    sandbox = "mcr.microsoft.com/oss/v2/kubernetes/pause:3.10.2"

[plugins."io.containerd.cri.v1.runtime".containerd]
    default_runtime_name = "nvidia"

    [plugins."io.containerd.cri.v1.runtime".containerd.runtimes]

        [plugins."io.containerd.cri.v1.runtime".containerd.runtimes.nvidia]
            runtime_type = "io.containerd.runc.v2"

        [plugins."io.containerd.cri.v1.runtime".containerd.runtimes.nvidia.options]
            BinaryName = "/usr/bin/nvidia-container-runtime"

        [plugins."io.containerd.cri.v1.runtime".containerd.runtimes.runc]
            runtime_type = "io.containerd.runc.v2"

        [plugins."io.containerd.cri.v1.runtime".containerd.runtimes.runc.options]
            BinaryName = "/usr/bin/runc"

        [plugins."io.containerd.cri.v1.runtime".containerd.runtimes.untrusted]
            runtime_type = "io.containerd.runc.v2"

        [plugins."io.containerd.cri.v1.runtime".containerd.runtimes.untrusted.options]
            BinaryName = "/usr/bin/runc"

[plugins."io.containerd.cri.v1.images".registry]
    config_path = "/etc/containerd/certs.d"

[plugins."io.containerd.cri.v1.images".registry.headers]
    X-Meta-Source-Client = ["azure/aks"]
