#!/bin/bash
cat <<'DMESG_EOF'
[    0.000000] Linux version 5.4.0-1064-azure (buildd@lcy02-amd64-112) 
[    1.234567] Memory: 8192000K/8388608K available
[   10.123456] systemd[1]: Started Kernel log.
[ 3500.567890] Out of memory: Kill process 1234 (chrome) score 850 or sacrifice child
[ 3500.567891] Killed process 1234 (chrome) total-vm:2345678kB, anon-rss:1234567kB, file-rss:0kB, shmem-rss:0kB
[ 3520.789012] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/session-2.scope,task=node,pid=5678,uid=1000
[ 3520.789013] Out of memory: Kill process 5678 (node) score 500 or sacrifice child
[ 3520.789014] Killed process 5678 (node) total-vm:1234567kB, anon-rss:987654kB, file-rss:123456kB, shmem-rss:0kB
[ 3590.123456] systemd[1]: Started some-service.service.
DMESG_EOF
