#!/bin/bash
# Mock wget that returns unhealthy response
echo "  HTTP/1.1 503 Service Unavailable"
echo "  Date: Mon, 14 Jul 2025 18:48:48 GMT"
echo "  Content-Length: 0"
echo "  Content-Type: text/plain; charset=utf-8"
exit 0
