#!/bin/bash
# Mock wget that outputs HTTP/2 response - this reproduces the real issue!
echo "  HTTP/2 200"
echo "  Date: Mon, 14 Jul 2025 18:48:48 GMT"
echo "  Content-Length: 2"
echo "  Content-Type: text/plain; charset=utf-8"
exit 0
