# Add the "components" label to PRs that modify parts/common/components.json.
components:
- changed-files:
  - any-glob-to-any-file: 'parts/common/components.json'
requires-component-owner-approval:
- head-branch: ['renovate\/[0-9a-zA-Z-]+ciprod']