package nodeconfigutils

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	aksnodeconfigv1 "github.com/Azure/agentbaker/aks-node-controller/pkg/gen/aksnodeconfig/v1"
	"github.com/stretchr/testify/require"
)

// TestBackwardCompatibility tests that old code can unmarshal configs generated by current code.
func TestBackwardCompatibility(t *testing.T) {
	t.Parallel()
	targetCommit := os.Getenv("COMPAT_COMMIT")
	if targetCommit == "" {
		// We aim to support VHDs released in the last 6 months.
		// This commit is from 2025-11-08. Around the time first version of Config is released.
		// Adjust as needed in the future. But no sooner than 6 months.
		// CAREFUL, TEST FAILURE MAY HIGHLIGHT POTENTIAL BACKWARD COMPATIBILITY ISSUES.
		// Please investigate before updating this commit.
		targetCommit = "c4ddd55f7dd72bfb541313fe586f586dfa7bd114"
	}

	t.Logf("Testing backward compatibility with commit: %s", targetCommit)

	// Step 1: Generate JSON with current code
	cfg := &aksnodeconfigv1.Configuration{}
	PopulateAllFields(cfg)

	currentJSON, err := MarshalConfigurationV1(cfg)
	require.NoError(t, err)
	t.Logf("Generated %d bytes of JSON with current code", len(currentJSON))

	// Step 2: Create git worktree at target commit
	worktreePath := t.TempDir()
	cmd := exec.Command("git", "worktree", "add", worktreePath, targetCommit)
	output, err := cmd.CombinedOutput()
	require.NoError(t, err, "Failed to create worktree: %s", output)

	t.Cleanup(func() {
		exec.Command("git", "worktree", "remove", "--force", worktreePath).Run()
	})

	// Get commit info
	cmd = exec.Command("git", "log", "-1", "--oneline", targetCommit)
	commitInfo, _ := cmd.CombinedOutput()
	t.Logf("Testing against: %q", strings.TrimSpace(string(commitInfo)))

	// Step 3: Write JSON to worktree
	pkgPath := filepath.Join(worktreePath, "aks-node-controller", "pkg", "nodeconfigutils")
	jsonPath := filepath.Join(pkgPath, "test_compat.json")
	require.NoError(t, os.WriteFile(jsonPath, currentJSON, 0644))

	// Step 4: Create test file to unmarshal with old code
	testCode := `package nodeconfigutils
import (
	"os"
	"testing"
	"github.com/stretchr/testify/require"
)
func TestUnmarshalCompat(t *testing.T) {
	data, err := os.ReadFile("test_compat.json")
	require.NoError(t, err)
	cfg, err := UnmarshalConfigurationV1(data)
	require.NoError(t, err, "Old code should unmarshal current JSON")
	require.NotNil(t, cfg)
	t.Logf("✓ Successfully unmarshaled %d bytes", len(data))
}
`
	testFile := filepath.Join(pkgPath, "compat_test.go")
	require.NoError(t, os.WriteFile(testFile, []byte(testCode), 0644))

	// Step 5: Run test with old code
	cmd = exec.Command("go", "test", "-v", "-run", "TestUnmarshalCompat", "./pkg/nodeconfigutils")
	cmd.Dir = filepath.Join(worktreePath, "aks-node-controller")
	output, err = cmd.CombinedOutput()

	t.Logf("Old code output:\n%s", output)

	if err != nil {
		t.Errorf("❌ BACKWARD COMPATIBILITY BROKEN: Old code (%s) cannot unmarshal current JSON", targetCommit)
	} else {
		t.Logf("✅ BACKWARD COMPATIBLE with %s", targetCommit)
	}
}
