package nodeconfigutils

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"testing"

	aksnodeconfigv1 "github.com/Azure/agentbaker/aks-node-controller/pkg/gen/aksnodeconfig/v1"
	"github.com/stretchr/testify/require"
)

const (
	// Commit from 2025-11-08 when the first version of Config was released.
	// CAREFUL: Test failure may indicate backward compatibility breakage.
	// This commit should be 6-8 months old to account for VHD release cycles and deployment timelines.
	// Investigate thoroughly before updating.
	backwardCompatCommit = "c4ddd55f7dd72bfb541313fe586f586dfa7bd114"

	// Commit when PopulateAllFields was first introduced.
	// CAREFUL: Test failure may indicate forward compatibility breakage.
	// Only active RP releases (potentially multiple) need to be supported.
	// Investigate thoroughly before updating.
	forwardCompatCommit = "878718c80db175859a6d7cf377f7b7d40c438413"
)

var (
	fetchOnce sync.Once
)

// TestMain fetches required commits before running tests to avoid git lock conflicts in CI.
func TestMain(m *testing.M) {
	// Fetch commits needed for compatibility tests (only matters in CI with shallow clones)
	fetchCommitsOnce()
	os.Exit(m.Run())
}

// fetchCommitsOnce fetches required commits exactly once to avoid git lock conflicts.
func fetchCommitsOnce() {
	fetchOnce.Do(func() {
		fetchCommitsForTests(backwardCompatCommit, forwardCompatCommit)
	})
}

// setupWorktree creates a git worktree at the specified commit and returns its path.
func setupWorktree(t *testing.T, targetCommit string) string {
	worktreePath := t.TempDir()
	cmd := exec.Command("git", "worktree", "add", worktreePath, targetCommit)
	output, err := cmd.CombinedOutput()
	require.NoError(t, err, "Failed to create worktree: %s", output)

	t.Cleanup(func() {
		_ = exec.Command("git", "worktree", "remove", "--force", worktreePath).Run()
	})

	// Log commit info
	cmd = exec.Command("git", "log", "-1", "--oneline", targetCommit)
	if commitInfo, err := cmd.CombinedOutput(); err == nil {
		t.Logf("Testing against: %q", strings.TrimSpace(string(commitInfo)))
	}

	return worktreePath
}

// fetchCommitsForTests fetches required commits for compatibility tests in CI shallow clones.
// This is called once before tests run to avoid git lock conflicts between parallel fetches.
func fetchCommitsForTests(commits ...string) {
	for _, commit := range commits {
		cmd := exec.Command("git", "fetch", "--depth=1", "origin", commit)
		_ = cmd.Run() // Ignore errors - commit might already exist
	}
}

// TestBackwardCompatibility tests that old code can unmarshal configs generated by current code.
func TestBackwardCompatibility(t *testing.T) {
	t.Logf("Testing backward compatibility with commit: %s", backwardCompatCommit)

	// Generate JSON with current code
	cfg := &aksnodeconfigv1.Configuration{}
	PopulateAllFields(cfg)

	currentJSON, err := MarshalConfigurationV1(cfg)
	require.NoError(t, err)
	t.Logf("Generated %d bytes of JSON with current code", len(currentJSON))

	// Create git worktree at target commit
	worktreePath := setupWorktree(t, backwardCompatCommit)

	// Write JSON to worktree
	pkgPath := filepath.Join(worktreePath, "aks-node-controller", "pkg", "nodeconfigutils")
	jsonPath := filepath.Join(pkgPath, "test_compat.json")
	require.NoError(t, os.WriteFile(jsonPath, currentJSON, 0644))

	// Create test file to unmarshal with old code
	testCode := `package nodeconfigutils
import (
	"os"
	"testing"
	"github.com/stretchr/testify/require"
)
func TestUnmarshalCompat(t *testing.T) {
	data, err := os.ReadFile("test_compat.json")
	require.NoError(t, err)
	cfg, err := UnmarshalConfigurationV1(data)
	require.NoError(t, err, "Old code should unmarshal current JSON")
	require.NotNil(t, cfg)
	t.Logf("✓ Successfully unmarshaled %d bytes", len(data))
}
`
	testFile := filepath.Join(pkgPath, "compat_test.go")
	require.NoError(t, os.WriteFile(testFile, []byte(testCode), 0644))

	// Run test with old code
	cmd := exec.Command("go", "test", "-v", "-run", "TestUnmarshalCompat", "./pkg/nodeconfigutils")
	cmd.Dir = filepath.Join(worktreePath, "aks-node-controller")
	output, err := cmd.CombinedOutput()

	t.Logf("Old code output:\n%s", output)
	require.NoError(t, err, "❌ BACKWARD COMPATIBILITY BROKEN: Old code (%s) cannot unmarshal current JSON", backwardCompatCommit)
}

// TestForwardCompatibility tests that current code can unmarshal configs generated by old code.
func TestForwardCompatibility(t *testing.T) {
	t.Logf("Testing forward compatibility with commit: %s", forwardCompatCommit)

	// Create git worktree at target commit
	worktreePath := setupWorktree(t, forwardCompatCommit)
	pkgPath := filepath.Join(worktreePath, "aks-node-controller", "pkg", "nodeconfigutils")

	// Try to generate JSON with old code using PopulateAllFields
	generateCode := `package nodeconfigutils
import (
	"os"
	"testing"
	aksnodeconfigv1 "github.com/Azure/agentbaker/aks-node-controller/pkg/gen/aksnodeconfig/v1"
	"github.com/stretchr/testify/require"
)
func TestGenerateCompat(t *testing.T) {
	cfg := &aksnodeconfigv1.Configuration{}
	PopulateAllFields(cfg)
	data, err := MarshalConfigurationV1(cfg)
	require.NoError(t, err)
	require.NoError(t, os.WriteFile("old_config.json", data, 0644))
	t.Logf("Generated %d bytes", len(data))
}
`
	generateFile := filepath.Join(pkgPath, "generate_compat_test.go")
	require.NoError(t, os.WriteFile(generateFile, []byte(generateCode), 0644))

	// Run the generation test
	cmd := exec.Command("go", "test", "-v", "-run", "TestGenerateCompat", "./pkg/nodeconfigutils")
	cmd.Dir = filepath.Join(worktreePath, "aks-node-controller")
	output, err := cmd.CombinedOutput()

	t.Logf("Old code generation output:\n%s", output)
	require.NoError(t, err, "Old code failed to generate JSON")

	// Read generated JSON
	jsonPath := filepath.Join(pkgPath, "old_config.json")
	oldJSON, err := os.ReadFile(jsonPath)
	require.NoError(t, err)
	t.Logf("Generated %d bytes of JSON with old code", len(oldJSON))

	// Unmarshal with current code
	cfg, err := UnmarshalConfigurationV1(oldJSON)
	require.NoError(t, err, "❌ FORWARD COMPATIBILITY BROKEN: Current code cannot unmarshal old JSON (%s)", forwardCompatCommit)
	require.NotNil(t, cfg)
}
