package config

import "github.com/urfave/cli/v3"

func Flags() []cli.Flag {
	return []cli.Flag{
		&cli.StringFlag{Name: "acr-secret-name", Value: Config.ACRSecretName, Destination: &Config.ACRSecretName, Sources: cli.EnvVars("ACR_SECRET_NAME")},
		&cli.StringFlag{Name: "acr-target-repository", Value: Config.AzureContainerRegistrytargetRepository, Destination: &Config.AzureContainerRegistrytargetRepository, Sources: cli.EnvVars("ACR_TARGET_REPOSITORY")},
		&cli.StringFlag{Name: "blob-container", Value: Config.BlobContainer, Destination: &Config.BlobContainer, Sources: cli.EnvVars("BLOB_CONTAINER")},
		&cli.StringFlag{Name: "blob-storage-account-prefix", Value: Config.BlobStorageAccountPrefix, Destination: &Config.BlobStorageAccountPrefix, Sources: cli.EnvVars("BLOB_STORAGE_ACCOUNT_PREFIX")},
		&cli.StringFlag{Name: "build-id", Value: Config.BuildID, Destination: &Config.BuildID, Sources: cli.EnvVars("BUILD_ID")},
		&cli.StringFlag{Name: "location", Value: Config.DefaultLocation, Destination: &Config.DefaultLocation, Sources: cli.EnvVars("E2E_LOCATION")},
		&cli.DurationFlag{Name: "poll-interval", Value: Config.DefaultPollInterval, Destination: &Config.DefaultPollInterval, Sources: cli.EnvVars("DEFAULT_POLL_INTERVAL")},
		&cli.StringFlag{Name: "subnet-name", Value: Config.DefaultSubnetName, Destination: &Config.DefaultSubnetName, Sources: cli.EnvVars("DEFAULT_SUBNET_NAME")},
		&cli.StringFlag{Name: "vm-sku", Value: Config.DefaultVMSKU, Destination: &Config.DefaultVMSKU, Sources: cli.EnvVars("DEFAULT_VM_SKU")},
		&cli.BoolFlag{Name: "disable-scriptless", Value: Config.DisableScriptless, Destination: &Config.DisableScriptless, Sources: cli.EnvVars("DISABLE_SCRIPTLESS")},
		&cli.BoolFlag{Name: "disable-scriptless-compilation", Value: Config.DisableScriptLessCompilation, Destination: &Config.DisableScriptLessCompilation, Sources: cli.EnvVars("DISABLE_SCRIPTLESS_COMPILATION")},
		&cli.StringFlag{Name: "log-dir", Value: Config.E2ELoggingDir, Destination: &Config.E2ELoggingDir, Sources: cli.EnvVars("LOGGING_DIR")},
		&cli.BoolFlag{Name: "secure-tls-bootstrapping", Value: Config.EnableSecureTLSBootstrapping, Destination: &Config.EnableSecureTLSBootstrapping, Sources: cli.EnvVars("ENABLE_SECURE_TLS_BOOTSTRAPPING")},
		&cli.StringFlag{Name: "extended-tests", Value: Config.ExtendedTests, Destination: &Config.ExtendedTests, Sources: cli.EnvVars("EXTENDED_TESTS")},
		&cli.StringFlag{Name: "gallery-name", Value: Config.GalleryName, Destination: &Config.GalleryName, Sources: cli.EnvVars("GALLERY_NAME")},
		&cli.StringFlag{Name: "gallery-resource-group", Value: Config.GalleryResourceGroupName, Destination: &Config.GalleryResourceGroupName, Sources: cli.EnvVars("GALLERY_RESOURCE_GROUP")},
		&cli.StringFlag{Name: "gallery-subscription-id", Value: Config.GallerySubscriptionID, Destination: &Config.GallerySubscriptionID, Sources: cli.EnvVars("GALLERY_SUBSCRIPTION_ID")},
		&cli.BoolFlag{Name: "ignore-missing-vhd", Value: Config.IgnoreScenariosWithMissingVHD, Destination: &Config.IgnoreScenariosWithMissingVHD, Sources: cli.EnvVars("IGNORE_SCENARIOS_WITH_MISSING_VHD")},
		&cli.BoolFlag{Name: "keep-vmss", Value: Config.KeepVMSS, Destination: &Config.KeepVMSS, Sources: cli.EnvVars("KEEP_VMSS")},
		&cli.StringFlag{Name: "network-isolated-nsg-name", Value: Config.NetworkIsolatedNSGName, Destination: &Config.NetworkIsolatedNSGName, Sources: cli.EnvVars("NETWORK_ISOLATED_NSG_NAME")},
		&cli.IntFlag{Name: "parallel", Value: Config.Parallel, Destination: &Config.Parallel, Sources: cli.EnvVars("E2E_PARALLEL", "PARALLEL")},
		&cli.IntFlag{Name: "retries", Value: Config.Retries, Destination: &Config.Retries, Sources: cli.EnvVars("E2E_FAILED_TESTS_RETRY_COUNT")},
		&cli.StringFlag{Name: "junit-file", Value: Config.JUnitFile, Destination: &Config.JUnitFile, Sources: cli.EnvVars("E2E_JUNIT_FILE")},
		&cli.StringFlag{Name: "output", Value: Config.OutputMode, Destination: &Config.OutputMode, Sources: cli.EnvVars("E2E_OUTPUT")},
		&cli.BoolFlag{Name: "hide-passed-logs", Value: Config.HidePassedLogs, Destination: &Config.HidePassedLogs, Sources: cli.EnvVars("E2E_HIDE_PASSED_LOGS")},
		&cli.StringFlag{Name: "sig-version-tag-name", Value: Config.SIGVersionTagName, Destination: &Config.SIGVersionTagName, Sources: cli.EnvVars("SIG_VERSION_TAG_NAME")},
		&cli.StringFlag{Name: "sig-version-tag-value", Value: Config.SIGVersionTagValue, Destination: &Config.SIGVersionTagValue, Sources: cli.EnvVars("SIG_VERSION_TAG_VALUE")},
		&cli.BoolFlag{Name: "skip-capacity-errors", Value: Config.SkipTestsWithSKUCapacityIssue, Destination: &Config.SkipTestsWithSKUCapacityIssue, Sources: cli.EnvVars("SKIP_TESTS_WITH_SKU_CAPACITY_ISSUE")},
		&cli.StringFlag{Name: "subscription-id", Value: Config.SubscriptionID, Destination: &Config.SubscriptionID, Sources: cli.EnvVars("SUBSCRIPTION_ID")},
		&cli.StringFlag{Name: "tags", Value: Config.TagsToRun, Destination: &Config.TagsToRun, Sources: cli.EnvVars("TAGS_TO_RUN")},
		&cli.StringFlag{Name: "skip-tags", Value: Config.TagsToSkip, Destination: &Config.TagsToSkip, Sources: cli.EnvVars("TAGS_TO_SKIP")},
		&cli.StringFlag{Name: "test-gallery-image-prefix", Value: Config.TestGalleryImagePrefix, Destination: &Config.TestGalleryImagePrefix, Sources: cli.EnvVars("TEST_GALLERY_IMAGE_PREFIX")},
		&cli.StringFlag{Name: "test-gallery-name-prefix", Value: Config.TestGalleryNamePrefix, Destination: &Config.TestGalleryNamePrefix, Sources: cli.EnvVars("TEST_GALLERY_NAME_PREFIX")},
		&cli.BoolFlag{Name: "test-pre-provision", Value: Config.TestPreProvision, Destination: &Config.TestPreProvision, Sources: cli.EnvVars("TEST_PRE_PROVISION")},
		&cli.DurationFlag{Name: "timeout", Value: Config.TestTimeout, Destination: &Config.TestTimeout, Sources: cli.EnvVars("TEST_TIMEOUT")},
		&cli.DurationFlag{Name: "suite-timeout", Value: Config.SuiteTimeout, Destination: &Config.SuiteTimeout, Sources: cli.EnvVars("E2E_GO_TEST_TIMEOUT", "SUITE_TIMEOUT", "TIMEOUT")},
		&cli.StringFlag{Name: "vhd-metadata-file", Value: Config.VHDMetadataFile, Destination: &Config.VHDMetadataFile, Sources: cli.EnvVars("E2E_VHD_METADATA_FILE")},
		&cli.DurationFlag{Name: "cluster-timeout", Value: Config.TestTimeoutCluster, Destination: &Config.TestTimeoutCluster, Sources: cli.EnvVars("TEST_TIMEOUT_CLUSTER")},
		&cli.DurationFlag{Name: "vmss-timeout", Value: Config.TestTimeoutVMSS, Destination: &Config.TestTimeoutVMSS, Sources: cli.EnvVars("TEST_TIMEOUT_VMSS")},
	}
}
