// Code generated by hack/genregions; DO NOT EDIT.
// Regenerate with `make generate-e2e-regions` after changing a scenario's region.

package config

// scenarioRegions is every region a non-Windows E2E scenario pins itself to. Shared
// gallery image versions are replicated to all of them regardless of which region the
// current test needs, so concurrent writers agree on the target region list.
// config.BaselineRegion is always included.
var scenarioRegions = []string{
	"eastus",
	"southcentralus",
	"southeastasia",
	"uaenorth",
	"westus2",
	"westus3",
}

// windowsScenarioRegions is every region a Windows E2E scenario pins itself to. It is
// tracked separately because Windows images are large, so they are not replicated to
// regions only Linux scenarios use. config.BaselineRegion is always included.
var windowsScenarioRegions = []string{
	"westus3",
}
