#!/usr/bin/env python3
"""
Injects hotfix write_files entries into the EnableScriptlessCSECmd section
of nodecustomdata.yml by copying matching blocks from the traditional section.

Usage: python3 hack/hotfix_inject.py <template_path> <varkey1> [varkey2 ...]

This script is called by hack/hotfix-generate.sh.
"""

import sys
import re


def find_block_boundaries(lines):
    """Find the EnableScriptlessCSECmd / else / end block boundaries."""
    scriptless_start = None
    else_line = None
    end_line = None

    for i, line in enumerate(lines):
        stripped = line.strip()
        if '{{if EnableScriptlessCSECmd}}' in stripped or '{{ if EnableScriptlessCSECmd }}' in stripped:
            scriptless_start = i
        elif scriptless_start is not None and else_line is None and stripped.startswith('{{- else'):
            else_line = i

    for i in range(len(lines) - 1, -1, -1):
        stripped = lines[i].strip()
        if stripped in ('{{- end}}', '{{end}}', '{{ end }}', '{{- end }}'):
            end_line = i
            break

    return scriptless_start, else_line, end_line


def parse_write_files_blocks(traditional_lines):
    """Parse write_files blocks from the traditional section.

    Each block is either a simple '- path:' entry or an entire conditional
    block (e.g., {{if IsAzlOSGuard}}...{{end}}) treated as a single unit.

    Returns a list of (varkeys_set, lines_list) tuples.
    """
    blocks = []
    current_block = []
    current_varkeys = set()
    in_block = False
    conditional_depth = 0

    for line in traditional_lines:
        stripped = line.strip()

        # Track conditional nesting depth
        if re.match(r'\{\{-?\s*if\s+', stripped):
            conditional_depth += 1
        if re.match(r'\{\{-?\s*end\s*\}\}', stripped):
            conditional_depth -= 1

        # Detect start of a new top-level write_files entry
        is_path_line = stripped.startswith('- path:')
        is_conditional_start = (conditional_depth == 1 and re.match(r'\{\{-?\s*if\s+', stripped))

        start_new = False
        if conditional_depth == 0 and is_path_line:
            start_new = True
        elif is_conditional_start:
            start_new = True

        if start_new:
            if current_block and current_varkeys:
                blocks.append((current_varkeys.copy(), list(current_block)))
            current_block = []
            current_varkeys = set()
            in_block = True

        if in_block:
            current_block.append(line)
            match = re.search(r'GetVariableProperty\s+"cloudInitData"\s+"(\w+)"', stripped)
            if match:
                current_varkeys.add(match.group(1))

    if current_block and current_varkeys:
        blocks.append((current_varkeys.copy(), list(current_block)))

    return blocks


def main():
    if len(sys.argv) < 3:
        print("Usage: hotfix_inject.py <template_path> <varkey1> [varkey2 ...]", file=sys.stderr)
        sys.exit(1)

    template_path = sys.argv[1]
    target_varkeys = set(sys.argv[2:])

    with open(template_path, 'r') as f:
        content = f.read()

    # Step 1: Remove any previous hotfix entries (idempotent)
    content = re.sub(
        r'\n# ---- hotfix: auto-generated by hotfix-generate GH Action ----\n.*?# ---- end hotfix ----\n',
        '',
        content,
        flags=re.DOTALL,
    )

    lines = content.splitlines(keepends=True)

    # Step 2: Find block boundaries
    scriptless_start, else_line, end_line = find_block_boundaries(lines)

    if scriptless_start is None or else_line is None or end_line is None:
        print(f"ERROR: Could not find EnableScriptlessCSECmd block boundaries", file=sys.stderr)
        print(f"  scriptless_start={scriptless_start}, else_line={else_line}, end_line={end_line}", file=sys.stderr)
        sys.exit(1)

    print(f"Template structure:", file=sys.stderr)
    print(f"  EnableScriptlessCSECmd block: lines {scriptless_start+1}-{else_line+1}", file=sys.stderr)
    print(f"  Traditional block: lines {else_line+2}-{end_line+1}", file=sys.stderr)

    # Step 3: Extract and parse write_files blocks from traditional section
    traditional_lines = lines[else_line+1:end_line]
    blocks = parse_write_files_blocks(traditional_lines)

    print(f"Found {len(blocks)} write_files blocks in traditional section", file=sys.stderr)

    # Step 4: Select blocks matching target varkeys
    selected_blocks = []
    for varkeys, block_lines in blocks:
        if varkeys & target_varkeys:
            selected_blocks.append(block_lines)
            print(f"  Selected block with varkeys: {varkeys}", file=sys.stderr)

    if not selected_blocks:
        print("No matching write_files blocks found for the target varkeys.", file=sys.stderr)
        sys.exit(0)

    # Step 5: Build hotfix insertion text
    hotfix_lines = [
        "\n",
        "# ---- hotfix: auto-generated by hotfix-generate GH Action ----\n",
    ]
    for block_lines in selected_blocks:
        hotfix_lines.extend(block_lines)
    hotfix_lines.append("# ---- end hotfix ----\n")

    # Step 6: Insert before {{- else }} line
    final_lines = lines[:else_line] + hotfix_lines + lines[else_line:]

    with open(template_path, 'w') as f:
        f.writelines(final_lines)

    print(f"\nInjected {len(selected_blocks)} write_files block(s) into EnableScriptlessCSECmd section", file=sys.stderr)
    print(f"Updated {template_path}", file=sys.stderr)


if __name__ == '__main__':
    main()
