apiVersion: apps/v1
kind: Deployment
metadata:
  name: &name debug
  labels:
    app: *name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: *name
  template:
    metadata:
      labels:
        app: *name
    spec:
      # nodeSelector:
      #   node.kubernetes.io/instance-type: Standard_NC12
      # tolerations:
      #   - key: "node-role.kubernetes.io/master"
      #     operator: "Exists"
      #
      # # above OR below needed ONLY, not both
      # #
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: node-role.kubernetes.io/master
      #           operator: Exists
      hostNetwork: true
      hostPID: true
      containers:
      - image: docker.io/ubuntu:18.04
        name: ubuntu
        command: ["sleep", "infinity"]
        resources:
          requests: {}
          limits: {}
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_PTRACE", "SYS_RAWIO"]