apiVersion: v1
kind: Pod
metadata:
  name: ${POD_NAME}
  labels:
    env: test
spec:
  containers:
  - name: ${POD_NAME}
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    command:
      - "powershell.exe"
      - "-command"
      - "Start-Sleep -s 1840000"
    imagePullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/hostname: ${VMSS_INSTANCE_NAME}