apiVersion: v1
kind: Pod
metadata:
  name: podname-rxpvhrw
  labels:
    env: test
spec:
  containers:
  - name: podname-rxpvhrw
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/hostname: abtes1ab1000001
