apiVersion: v1
kind: Pod
metadata:
  name: podname-q9ob2la
  labels:
    env: test
spec:
  containers:
  - name: podname-q9ob2la
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/hostname: abtesfb72000001
