name: $(SourceBranchName).$(date:yyMMdd)$(rev:.r)
trigger: none

phases:
  - phase: build_vhd
    queue:
      name: ace-test
      timeoutInMinutes: 120
    steps:
      # store some variables into files, later copy them into ev2 repo
      - bash: |
          echo "I was here" > vhd-publishing-info.json
        displayName: set vhd publishing info

      - task: PublishBuildArtifacts@1
        displayName: 'Publish vhd artifacts'
        inputs:
          artifactName: 'vhd'
          targetPath: 'vhd-publishing-info.json'

  - phase: ev2_build
    dependsOn: build_vhd
    queue:
      name: ace-test
      timeoutInMinutes: 120

    steps:
      - task: DownloadBuildArtifacts@0
        displayName: Download tools
        inputs:
          buildType: 'specific'
          project: 'CloudNativeCompute'
          pipeline: 'aks-deployment-tools'
          buildVersionToDownload: 'latestFromBranch'
          branchName: 'master'
          downloadType: 'single'
          artifactName: 'tools'
          downloadPath: '.'
      - bash: |
          pw
          ls
          displayName: show directory
      - powershell: |
          $env:BUILD_BUILDNUMBER | Out-File vhd-publishing-info.json
          ./tools/ev2ab.ps1 ev2 $(Build.ArtifactStagingDirectory)/ev2.artifacts
        displayName: Build ev2 artifacts

      - task: PublishBuildArtifacts@1
        displayName: 'Publish ev2 vhd artifacts'
        inputs:
          pathtoPublish: $(Build.ArtifactStagingDirectory)/ev2.artifacts/vhd
          artifactName: 'ev2.vhd'
