parameters:
  - name: stageName
    type: string
    displayName: Stage name for the created stages. Must contain only alphanmumeric values and _
  - name: imageName
    type: string
    displayName: The value of the imageName tag to run E2E tests on
  - name: windowsSku
    type: string
    displayName: The windows artifact to build. Might be a duplicate of artifactName
  - name: artifactName
    type: string
    displayName: The artifact to build. Might be a duplicate of windowsSku
  - name: dryrun
    displayName: Dry run
    type: boolean
    default: False
  - name: vhddebug
    displayName: VHD Debug
    type: boolean
    default: False
  - name: build
    displayName: Boolean flag to actually run these stages.
    type: boolean
    default: True
  - name: buildVmSize
    type: string
    displayName: VM SKU to build the VHD with. Has a sensible default
  - name: hyperVGeneration
    type: string
    displayName: V1 or V2.
  - name: architecture
    type: string
    displayName: CPU Architecture - X86_64 or ARM64
  - name: skipExtensionCheck
    displayName: Skip Extension Check
    type: boolean
    default: False
  - name: installOpenSshServer
    displayName: Install Open SSH Server
    type: boolean
    default: True
  - name: windowsBaseImageUrl
    displayName: Windows Base Image URL Override
    type: string
  - name: windowsNanoImageUrl
    displayName: Windows nano base container image URL Override
    type: string
  - name: windowsCoreImageUrl
    displayName: Windows core base container image URL Override
    type: string
  - name: overrideBranch
    type: string
    default: master
  - name: useOverrides
    displayName: Use component overrides
    type: boolean
  - name: csePackageDir
    type: string
    displayName: Path to the CSE package to use for the build.
  - name: cseFileName
    type: string
    displayName: CSE package filename.


stages:
  - stage: build_${{ parameters.stageName }}
    # Put the artifact name first so it doesn't get truncated as much in ADO
    displayName: Build (${{ parameters.artifactName }})
    condition: and(succeeded(), eq('${{ parameters.build }}', True))
    dependsOn: Package
    jobs:
      - job: build_${{ parameters.stageName }}
        dependsOn: [ ]
        timeoutInMinutes: 180
        steps:
          - template: ./.builder-release-template-windows.yaml
            parameters:
              artifactName: ${{ parameters.artifactName }}
              windowsSku: ${{ parameters.windowsSku }}
              hyperVGeneration: ${{ parameters.hyperVGeneration }}
              architecture: ${{ parameters.architecture }}
              buildVmSize: ${{ parameters.buildVmSize }}
              build: ${{ parameters.build }}
              vhddebug: ${{ parameters.vhddebug }}
              dryrun: ${{ parameters.dryrun }}
              installOpenSshServer: ${{ parameters.installOpenSshServer }}
              skipExtensionCheck: ${{ parameters.skipExtensionCheck }}
              windowsBaseImageUrl: ${{ parameters.windowsBaseImageUrl }}
              windowsNanoImageUrl: ${{ parameters.windowsNanoImageUrl }}
              windowsCoreImageUrl: ${{ parameters.windowsCoreImageUrl }}
              overrideBranch: ${{ parameters.overrideBranch }}
              useOverrides: ${{ parameters.useOverrides }}
              csePackageDir: ${{ parameters.csePackageDir }}
              csePackageFileName: ${{ parameters.cseFileName }}

  - stage: e2e_${{ parameters.stageName }}
    displayName: E2E (${{ parameters.artifactName }})
    dependsOn: build_${{ parameters.stageName }}
    condition: and(succeeded(), eq('${{ parameters.build }}', True))
    variables:
      TAGS_TO_RUN: imageName=${{ parameters.imageName }}
      BLOB_CONTAINER: wcct
      BLOB_STORAGE_ACCOUNT_PREFIX: wcct
      DEFAULT_VM_SKU: ${{ parameters.buildVmSize }}
      E2E_LOCATION: $(AZURE_E2E_LOCATION)   #note ${} will not work here, use $()
      GALLERY_SUBSCRIPTION_ID_WINDOWS: $(AZURE_BUILD_SUBSCRIPTION_ID)
      GALLERY_RESOURCE_GROUP_WINDOWS: $(AZURE_BUILD_RESOURCE_GROUP_NAME)
    jobs:
      - template: ./e2e-template.yaml
        parameters:
          name: For image ${{ parameters.imageName }}
          IgnoreScenariosWithMissingVhd: false

  - stage: aks_cluster_${{ parameters.stageName }}
    displayName: aks cluster (${{ parameters.artifactName }})
    dependsOn: build_${{ parameters.stageName }}
    condition: and(succeeded(), eq('${{ parameters.build }}', True))
    jobs:
      - template: ./.create-aks-cluster-template.yaml
        parameters:
          imageName: ${{ parameters.imageName }}
          kubernetesVersion: $(KUBERNETES_VERSION)

  - stage: k8s_e2e_${{ parameters.stageName }}
    displayName: k8s e2e (${{ parameters.artifactName }})
    dependsOn: aks_cluster_${{ parameters.stageName }}
    condition: and(succeeded(), eq('${{ parameters.build }}', True))
    variables:
      cluster_RG: $[ stageDependencies.aks_cluster_${{ parameters.stageName }}.create.outputs['setvar.CLUSTER_RG'] ]
    jobs:
      - template: ./.k8s-windows-e2e-template.yaml
        parameters:
          resourceGroup: $(CLUSTER_RG)
          clusterName: testcluster
          storageContainerName: "pipeline-test-logs"
          kustoUrl: "https://wccttest.eastus.kusto.windows.net"
          KustoDatabaseName: "wccttest"
          kustoTableName: "windowssigtestlogs"
          

