steps:
  - task: DownloadPipelineArtifact@2
    displayName: Download VHD publishing info
    inputs:
      source: 'specific'
      path: artifacts/vhd
      project: 'CloudNativeCompute'
      pipeline: $(VHD_PIPELINE_ID)
      runVersion: 'specific'
      runId: $(VHD_PIPELINE_RUN_ID)
  - script: |
      docker run --rm \
      -v ${PWD}:/go/src/github.com/Azure/AgentBaker \
      -w /go/src/github.com/Azure/AgentBaker \
      ${CONTAINER_IMAGE} make bootstrap
    displayName: Setup tools
  - script: |
      docker run --rm \
      -v ${PWD}:/go/src/github.com/Azure/AgentBaker \
      -w /go/src/github.com/Azure/AgentBaker \
      -e AZURE_TENANT_ID=${AZURE_TENANT_ID} \
      -e AZURE_CLIENT_ID=${AZURE_CLIENT_ID} \
      -e AZURE_CLIENT_SECRET="$(AZURE_CLIENT_SECRET)" \
      -e SKU_PREFIX=${SKU_PREFIX} \
      -e SKU_TEMPLATE_FILE=${SKU_TEMPLATE_FILE} \
      -e PUBLISHER=${PUBLISHER} \
      -e OFFER=${OFFER} \
      -e CONTAINER_RUNTIME=${CONTAINER_RUNTIME} \
      ${CONTAINER_IMAGE} ./vhdbuilder/publish/Marketplace/new-sku-and-add-image-version.sh
    displayName: Create a new marketplace SKU
  - script: |
      docker run --rm \
      -v ${PWD}:/go/src/github.com/Azure/AgentBaker \
      -w /go/src/github.com/Azure/AgentBaker \
      ${CONTAINER_IMAGE} make tools-clean
    displayName: cleanup - clean hack/tools/bin
    condition: always()
