parameters:
    - name: artifactName
      type: string
      default: 1604

steps:
  - bash: |
        cat <<EOF > vhd-publishing-info.json
        {
            "vhd_url" : "testUrl",
            "os_name" : "ubuntu",
            "sku_name" : "test",
            "offer_name" : "test",
            "hyperv_generation": "test",
            "image_version": "test"
        }
        EOF
    displayName: Getting Shared Access Signature URI
  - task: PublishPipelineArtifact@1
    inputs:
        artifactName: 'publishing-info-${{ parameters.artifactName }}'
        targetPath: 'vhd-publishing-info.json'
    condition: and(eq(variables.DRY_RUN, 'False'), ne(variables['MODE'], 'sigMode'))
  - task: UniversalPackages@0
    displayName: Universal Publish
    inputs:
      command: publish
      publishDirectory: 'vhd-publishing-info.json'
      vstsFeedPublish: 'CloudNativeCompute/AKS-Linux-VHD-Artifacts'
      vstsFeedPackagePublish: 'publishing-info-${{ parameters.artifactName }}'
      packagePublishDescription: 'VHD publishing info ${{ parameters.artifactName }}'