parameters:
    - name: artifactName
      type: string
      default: 2019

steps:

# Set VHD_NAME and SKU_NAME which will be published.
# Note: use -a to grep OS_DISK_SAS (packer-output should be read as a binary file in Linux)
# Perform this step only if we want to publish the VHD: Gen 1 or Gen 2 and the built sig is for production.
  - bash: |
      docker run --rm \
      -v ${PWD}:/go/src/github.com/Azure/AgentBaker \
      -w /go/src/github.com/Azure/AgentBaker \
      -e CLIENT_ID=${CLIENT_ID} \
      -e CLIENT_SECRET="$(CLIENT_SECRET)" \
      -e TENANT_ID=${TENANT_ID} \
      -e SUBSCRIPTION_ID="${SUBSCRIPTION_ID}" \
      -e CLASSIC_SA_CONNECTION_STRING="$(CLASSIC_SA_CONNECTION_STRING)" \
      -e STORAGE_ACCT_BLOB_URL=${STORAGE_ACCT_BLOB_URL} \
      -e WINDOWS_SKU=$(WINDOWS_SKU) \
      -e OS_NAME="Windows" \
      -e OFFER_NAME="Windows" \
      -e IMAGE_VERSION=${IMAGE_VERSION} \
      -e HYPERV_GENERATION=${HYPERV_GENERATION} \
      -e OS_TYPE="Windows" \
      ${CONTAINER_IMAGE} make -f packer.mk generate-sas
    displayName: Download vhd-publishing-info.json

# Will be stepped in if the sig is for production
  - task: PublishPipelineArtifact@1
    inputs:
        artifactName: 'publishing-info-${{ parameters.artifactName }}'
        targetPath: 'vhd-publishing-info.json'
