parameters:
  - name: stageName
    type: string
    displayName: Stage name for the created stages. Must contain only alphanmumeric values and _
  - name: imageName
    type: string
    displayName: The value of the imageName tag to run E2E tests on
  - name: windowsSku
    type: string
    displayName: The windows artifact to build. Might be a duplicate of artifactName
  - name: artifactName
    type: string
    displayName: The artifact to build. Might be a duplicate of windowsSku
  - name: dryrun
    displayName: Dry run
    type: boolean
    default: False
  - name: vhddebug
    displayName: VHD Debug
    type: boolean
    default: False
  - name: build
    displayName: Boolean flag to actually run these stages.
    type: boolean
    default: True
  - name: buildVmSize
    type: string
    default: Standard_D4s_v3
    displayName: VM SKU to build the VHD with. Has a sensible default
  - name: hyperVGeneration
    type: string
    displayName: V1 or V2.

stages:
  - stage: build_${{ parameters.stageName }}
    condition: eq('${{ parameters.build }}', True)
    dependsOn: [ ]
    jobs:
      - job: build_${{ parameters.stageName }}
        dependsOn: []
        timeoutInMinutes: 180
        steps:
          - bash: |
              echo '##vso[task.setvariable variable=VHD_DEBUG]${{ parameters.vhddebug }}'
              echo '##vso[task.setvariable variable=DRY_RUN]${{ parameters.dryrun }}'
              echo '##vso[task.setvariable variable=HYPERV_GENERATION]${{ parameters.hyperVGeneration }}'
              echo '##vso[task.setvariable variable=AZURE_VM_SIZE]${{ parameters.buildVmSize }}'
              echo '##vso[task.setvariable variable=WINDOWS_SKU]${{ parameters.windowsSku }}'
              echo '##vso[task.setvariable variable=WINDOWS_BASE_IMAGE_URL]$(WINDOWS_23H2_GEN2_BASE_IMAGE_URL)'
              echo '##vso[task.setvariable variable=WINDOWS_NANO_IMAGE_URL]$(WINDOWS_2022_NANO_IMAGE_URL)'
              echo '##vso[task.setvariable variable=WINDOWS_CORE_IMAGE_URL]$(WINDOWS_2022_CORE_IMAGE_URL)'
              echo '##vso[task.setvariable variable=WINDOWS_PRIVATE_PACKAGES_URL]$(PRIVATE_PACKAGES_URL)'
            displayName: Setup Build Variables
          - template: ./.builder-release-template-windows.yaml
            parameters:
              artifactName: ${{ parameters.artifactName }}

  - stage: e2e_${{ parameters.stageName }}
    dependsOn: build_${{ parameters.stageName }}
    condition: and(succeeded(), eq('${{ parameters.build }}', True))
    variables:
      TAGS_TO_RUN: imageName=${{ parameters.imageName }}
    jobs:
      - template: ./e2e-template.yaml
