parameters:
  - name: stageName
    type: string
  - name: imageName
    type: string
  - name: windowsSku
    type: string
  - name: artifactName
    type: string
  - name: dryrun
    displayName: Dry run
    type: boolean
    default: False
  - name: vhddebug
    displayName: VHD Debug
    type: boolean
    default: False
  - name: build
    type: boolean
    default: True
  - name: buildVmSize
    type: string
    default: Standard_D4s_v3
  - name: hyperVGeneration
    type: string

stages:
  - stage: build_${{ parameters.stageName }}
    dependsOn: [ ]
    jobs:
      - job: build_${{ parameters.stageName }}
        dependsOn: []
        condition: eq('${{ parameters.build }}', True)
        timeoutInMinutes: 180
        steps:
          - bash: |
              echo '##vso[task.setvariable variable=VHD_DEBUG]${{ parameters.vhddebug }}'
              echo '##vso[task.setvariable variable=DRY_RUN]${{ parameters.dryrun }}'
              echo '##vso[task.setvariable variable=HYPERV_GENERATION]${{ parameters.hyperVGeneration }})'
              echo '##vso[task.setvariable variable=AZURE_VM_SIZE]${{ parameters.buildVmSize }}'
              echo '##vso[task.setvariable variable=WINDOWS_SKU]${{ parameters.windowsSku }}'
              echo '##vso[task.setvariable variable=WINDOWS_BASE_IMAGE_URL]$(WINDOWS_23H2_GEN2_BASE_IMAGE_URL)'
              echo '##vso[task.setvariable variable=WINDOWS_NANO_IMAGE_URL]$(WINDOWS_2022_NANO_IMAGE_URL)'
              echo '##vso[task.setvariable variable=WINDOWS_CORE_IMAGE_URL]$(WINDOWS_2022_CORE_IMAGE_URL)'
              echo '##vso[task.setvariable variable=WINDOWS_PRIVATE_PACKAGES_URL]$(PRIVATE_PACKAGES_URL)'
            displayName: Setup Build Variables
          - template: ./.builder-release-template-windows.yaml
            parameters:
              artifactName: ${{ parameters.artifactName }}

  - stage: e2e_${{ parameters.stageName }}
    dependsOn: build_${{ parameters.stageName }}
    variables:
      TAGS_TO_RUN: imageName=${{ parameters.imageName }}
    jobs:
      - template: ./e2e-template.yaml
