parameters:
  - name: build2019containerd
    displayName: Build 2019 containerd
    type: boolean
    default: True
  - name: build2022containerd
    displayName: Build 2022 containerd
    type: boolean
    default: True
  - name: build2022containerdgen2
    displayName: Build 2022 containerd Gen 2
    type: boolean
    default: True
  - name: build23H2
    displayName: Build 23H2
    type: boolean
    default: True
  - name: build23H2gen2
    displayName: Build 23H2 Gen 2
    type: boolean
    default: True

  - name: dryrun
    displayName: Dry run
    type: boolean
    default: False
  - name: vhddebug
    displayName: VHD Debug
    type: boolean
    default: False

stages:
  - template: ./.build-and-test-windows-vhd-template.yaml
    parameters:
      stageName: win_2019_v1
      artifactName: 2019-containerd
      e2eTags: imageName=windows-2019-containerd
      windowsSku: 2019-containerd
      hyperVGeneration: V1
      build: ${{ parameters.build2019containerd }}
      vhddebug: ${{ parameters.vhddebug }}
      dryrun: ${{ parameters.dryrun }}
      buildVmSize: ${{ Standard_D4s_v3 }}

  - template: ./templates/.build-and-test-windows-vhd-template.yaml
    parameters:
      stageName: win_2022_v1
      artifactName: 2022-containerd
      e2eTags: imageName=windows-2022-containerd
      windowsSku: 2022-containerd
      hyperVGeneration: V1
      build: ${{ parameters.build2022containerd }}
      vhddebug: ${{ parameters.vhddebug }}
      dryrun: ${{ parameters.dryrun }}
      buildVmSize: ${{ Standard_D4s_v3 }}

  - template: ./templates/.build-and-test-windows-vhd-template.yaml
    parameters:
      stageName: win_2022_v2
      artifactName: 2022-containerd-gen2
      e2eTags: imageName=windows-2022-containerd-gen2
      windowsSku: 2022-containerd-gen2
      hyperVGeneration: V2
      build: ${{ parameters.build2022containerdgen2 }}
      vhddebug: ${{ parameters.vhddebug }}
      dryrun: ${{ parameters.dryrun }}
      buildVmSize: ${{ Standard_D4s_v3 }}

  - template: ./templates/.build-and-test-windows-vhd-template.yaml
    parameters:
      stageName: win_23H2_v1
      artifactName: 23H2
      e2eTags: imageName=windows-23H2
      windowsSku: 23H2
      hyperVGeneration: V1
      build: ${{ parameters.build23H2 }}
      vhddebug: ${{ parameters.vhddebug }}
      dryrun: ${{ parameters.dryrun }}
      buildVmSize: ${{ Standard_D4s_v3 }}

  - template: ./templates/.build-and-test-windows-vhd-template.yaml
    parameters:
      stageName: win_23H2_v2
      artifactName: 23H2-gen2
      e2eTags: imageName=windows-23H2-gen2
      windowsSku: 23H2-gen2
      hyperVGeneration: V2
      build: ${{ parameters.build23H2gen2 }}
      vhddebug: ${{ parameters.vhddebug }}
      dryrun: ${{ parameters.dryrun }}
      buildVmSize: ${{ Standard_D4s_v3 }}
