parameters:
  - name: artifactName
    type: string
    default: 1604
  - name: useOverrides
    type: boolean
    default: false
  - name: overrideBranch
    type: string
    default: master

steps:
  - template: ./.template-override-components-json.yaml
    parameters:
      overrideBranch: ${{ parameters.overrideBranch }}
      useOverrides: ${{ parameters.useOverrides }}

  - bash: |
      m="linuxVhdMode" && \
      echo "Set build mode to $m" && \
      echo "##vso[task.setvariable variable=MODE]$m"
    displayName: Get Build Mode

  - task: UniversalPackages@0
    displayName: Download CIS scanner
    inputs:
      command: download
      vstsFeed: AzCoreLinux-Compliance
      vstsFeedPackage: cisassessor
      vstsPackageVersion: '0.0.17'
      downloadDirectory: vhdbuilder/

  - task: DownloadPipelineArtifact@2
    condition: and(or(eq(variables.OS_SKU, 'CBLMariner'), eq(variables.OS_SKU, 'AzureLinux')), eq(variables.IMG_OFFER, 'cbl-mariner'))
    displayName: 'Download Kata CC UVM artifact'
    inputs:
      source: specific
      project: CloudNativeCompute
      pipeline: 318279
      specificBuildWithTriggering: true
      allowPartiallySucceededBuilds: false
      buildVersionToDownload: 'latestFromBranch'
      branchName: 'refs/heads/master'
      artifactName: 'drop_container_job_sign_uvm'
      itemPattern: |
        **/kata-containers-igvm-debug.img**
        **/igvm-measurement**
        **/kata-containers-igvm.img**
        **/kata-containers-cc.img**
        **/kata-containers.img**
        **/kata-containers-initrd-base.img**
      downloadPath: $(Build.SourcesDirectory)

  - task: DownloadPipelineArtifact@2
    condition: and(or(eq(variables.OS_SKU, 'CBLMariner'), eq(variables.OS_SKU, 'AzureLinux')), eq(variables.IMG_OFFER, 'azure-linux-3'))
    displayName: 'Download Kata and Kata CC AzureLinux3_0 UVM artifact'
    inputs:
      source: specific
      project: CloudNativeCompute
      pipeline: 417429
      specificBuildWithTriggering: true
      allowPartiallySucceededBuilds: false
      buildVersionToDownload: 'latestFromBranch'
      branchName: 'refs/heads/master'
      downloadType: 'single'
      artifactName: 'mariner-kata-3-0-uvm'
      itemPattern: |
        **/kata-containers.img**
      downloadPath: $(Build.SourcesDirectory)

  - bash: |
      pwd
      ls -R
    displayName: Show Directory

  - bash: |
      set -x
      GOPATH="$(go env GOPATH)"
      echo "GOPATH is currently set to $GOPATH"
      export PATH="$PATH:$GOPATH/bin"
      pushd /tmp
      GO111MODULE=on go install cuelang.org/go/cmd/cue@latest
      popd
      cue export ./schemas/manifest.cue > ./parts/linux/cloud-init/artifacts/manifest.json
    displayName: Setup Cue

  - bash: |
      SKU_NAME=${OS_VERSION} && \
      if [[ "${HYPERV_GENERATION,,}" == "v2" ]]; then SKU_NAME="${SKU_NAME}gen2"; fi && \
      if [[ "${ARCHITECTURE,,}" == "arm64" ]]; then SKU_NAME="${SKU_NAME}arm64"; fi && \
      if grep -q "GB200" <<< "$FEATURE_FLAGS"; then SKU_NAME="${SKU_NAME}gb200"; fi && \
      if [[ "${ENABLE_FIPS,,}" == "true" ]]; then SKU_NAME="${SKU_NAME}fips"; fi && \
      if grep -q "cvm" <<< "$FEATURE_FLAGS"; then SKU_NAME="${SKU_NAME}CVM"; fi && \
      if [[ "${IMG_SKU}" == *"minimal"* ]]; then SKU_NAME="${SKU_NAME}minimal"; fi && \
      if [[ "${ENABLE_TRUSTED_LAUNCH}" == "True" ]]; then SKU_NAME="${SKU_NAME}TL"; fi && \
      if [[ ${OS_SKU} != "CBLMariner" && ${OS_SKU} != "AzureLinux" && ${OS_SKU} != "AzureLinuxOSGuard" && ${OS_SKU} != "Flatcar" ]]; then SKU_NAME="${SKU_NAME}containerd"; fi && \
      SKU_NAME=$(echo ${SKU_NAME} | tr -d '.') && \
      echo "##vso[task.setvariable variable=SKU_NAME]$SKU_NAME"
      echo "Present working directory is: $PWD"
      echo "Set SKU_NAME to $SKU_NAME"
    displayName: Set SKU Name

  - task: DownloadSecureFile@1
    name: privateVHDSigningKey
    displayName: Download Private Key
    inputs:
      secureFile: 'aks_node_priv.asc'
      retryCount: 2

  - task: DownloadSecureFile@1
    name: publicVHDSigningKey
    displayName: Download Public Key
    inputs:
      secureFile: 'aks_node_pub.asc'
      retryCount: 2

  - bash: make -f packer.mk run-packer
    condition: ne(variables['BUILDER'], 'imagecustomizer')
    displayName: Build VHD
    retryCountOnTaskFailure: 3
    env:
      OS_TYPE: Linux
      GIT_VERSION: $(Build.SourceVersion)
      BRANCH: $(Build.SourceBranch)
      BUILD_NUMBER: $(Build.BuildNumber)
      BUILD_ID: $(Build.BuildId)
      BUILD_DEFINITION_NAME: $(Build.DefinitionName)
      UA_TOKEN: $(ua-token)
      PUBLIC_KEY_PATH: $(publicVHDSigningKey.secureFilePath)
      PRIVATE_KEY_PATH: $(privateVHDSigningKey.secureFilePath)
      GPG_PASSPHRASE: $(GPG_PASSPHRASE)
      RESOURCE_GROUP_NAME: $(AZURE_RESOURCE_GROUP_NAME)

  - bash: make -f packer.mk run-imagecustomizer
    condition: eq(variables['BUILDER'], 'imagecustomizer')
    displayName: Build VHD - Image Customizer
    retryCountOnTaskFailure: 3
    env:
      OS_TYPE: Linux
      GIT_VERSION: $(Build.SourceVersion)
      BRANCH: $(Build.SourceBranch)
      BUILD_NUMBER: $(Build.BuildNumber)
      BUILD_ID: $(Build.BuildId)
      BUILD_DEFINITION_NAME: $(Build.DefinitionName)

  - bash: |
      PACKER_VNET_RESOURCE_GROUP_NAME="$(cat vhdbuilder/packer/settings.json | grep "vnet_resource_group_name" | awk -F':' '{print $2}' | awk -F'"' '{print $2}')" && \
      PACKER_VNET_NAME="$(cat vhdbuilder/packer/settings.json | grep "vnet_name" | awk -F':' '{print $2}' | awk -F'"' '{print $2}')" && \
      CAPTURED_SIG_VERSION="$(cat vhdbuilder/packer/settings.json | grep "captured_sig_version" | awk -F':' '{print $2}' | awk -F'"' '{print $2}')" && \
      SIG_IMAGE_NAME="$(cat vhdbuilder/packer/settings.json | grep "sig_image_name" | awk -F':' '{print $2}' | awk -F'"' '{print $2}')" && \
      BUILD_LOCATION="$(cat vhdbuilder/packer/settings.json | grep "location" | awk -F':' '{print $2}' | awk -F'"' '{print $2}')" && \
      ARTIFACT_ID=$(date +%s) && \
      echo "##vso[task.setvariable variable=ARTIFACT_ID]${ARTIFACT_ID}" && \
      echo "##vso[task.setvariable variable=PACKER_BUILD_LOCATION]${BUILD_LOCATION}" && \
      echo "##vso[task.setvariable variable=PACKER_VNET_RESOURCE_GROUP_NAME]${PACKER_VNET_RESOURCE_GROUP_NAME}" && \
      echo "##vso[task.setvariable variable=PACKER_VNET_NAME]${PACKER_VNET_NAME}" && \
      echo "##vso[task.setvariable variable=VHD_NAME]${CAPTURED_SIG_VERSION}.vhd" && \
      echo "##vso[task.setvariable variable=IMAGE_NAME]${SIG_IMAGE_NAME}-${CAPTURED_SIG_VERSION}" && \
      echo "##vso[task.setvariable variable=SIG_IMAGE_NAME]${SIG_IMAGE_NAME}" && \
      echo "##vso[task.setvariable variable=CAPTURED_SIG_VERSION]${CAPTURED_SIG_VERSION}" && \
      echo "##vso[task.setvariable variable=IMPORTED_IMAGE_NAME]$(cat vhdbuilder/packer/settings.json | grep "imported_image_name" | awk -F':' '{print $2}' | awk -F'"' '{print $2}')" && \
      echo "##vso[task.setvariable variable=OS_DISK_URI]$(cat packer-output | grep "OSDiskUri:" | cut -d " " -f 2)" && \
      echo "##vso[task.setvariable variable=MANAGED_SIG_ID]$(cat packer-output | grep "ManagedImageSharedImageGalleryId:" | cut -d " " -f 2)" && \
      echo "##vso[task.setvariable variable=SIG_GALLERY_NAME]$(cat vhdbuilder/packer/settings.json | grep "sig_gallery_name" | awk -F':' '{print $2}' | awk -F'"' '{print $2}')" && \
      echo "##vso[task.setvariable variable=PERFORMANCE_DATA_FILE]vhd-build-performance-data.json" && \
      echo "##vso[task.setvariable variable=GRID_COMPATIBILITY_DATA_FILE]vhd-grid-compatibility-data.json" && \
      echo "##vso[task.setvariable variable=PKR_RG_NAME]$(cat packer-output | grep "ResourceGroupName" | cut -d "'" -f 2 | head -1)" && \
      echo "##vso[task.setvariable variable=OS_NAME]Linux" && \
      echo "##vso[task.setvariable variable=OS_TYPE]Linux" && \
      echo "##vso[task.setvariable variable=GIT_VERSION]$(Build.SourceVersion)" && \
      echo "##vso[task.setvariable variable=BUILD_DEFINITION_NAME]$(Build.DefinitionName)" && \
      echo "##vso[task.setvariable variable=BUILD_ID]$(Build.BuildId)" && \
      echo "##vso[task.setvariable variable=BUILD_NUMBER]$(Build.BuildNumber)" && \
      echo "##vso[task.setvariable variable=BRANCH]$(Build.SourceBranch)" && \
      echo "##vso[task.setvariable variable=GIT_BRANCH]$(Build.SourceBranch)" && \
      echo "##vso[task.setvariable variable=JOB_STATUS]$(Agent.JobStatus)" && \
      echo "##vso[task.setvariable variable=VHD_DEBUG]False"
    condition: always()
    displayName: Set Pipeline Variables

  - bash: make -f packer.mk publish-imagecustomizer
    condition: eq(variables['BUILDER'], 'imagecustomizer')
    displayName: Publish VHD - Image Customizer
    retryCountOnTaskFailure: 3
    env:
      RESOURCE_GROUP_NAME: $(AZURE_RESOURCE_GROUP_NAME)
      GENERATE_PUBLISHING_INFO: ${{ variables.GENERATE_PUBLISHING_INFO }}

  - bash: make -f packer.mk test-scan-and-cleanup
    condition: always()
    displayName: Test, Scan, and Cleanup
    env:
      BUILD_REPOSITORY_NAME: $(Build.Repository.Name)
      BUILD_SOURCEVERSION: $(Build.SourceVersion)
      SYSTEM_COLLECTIONURI: $(System.CollectionUri)
      SYSTEM_TEAMPROJECT: $(System.TeamProject)
      BUILD_RUN_NUMBER: $(Build.BuildNumber)
      VHD_ARTIFACT_NAME: ${{ parameters.artifactName }}
      SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
      PACKER_VNET_RESOURCE_GROUP_NAME: $(PACKER_VNET_RESOURCE_GROUP_NAME)
      PACKER_VNET_NAME: $(PACKER_VNET_NAME)
      SKIP_SCANNING: $(SKIP_SCANNING)
      DRY_RUN: $(DRY_RUN)

  - bash: make -f packer.mk replicate-captured-sig-image-version
    condition: ne(variables['REPLICATIONS'], '')
    displayName: Replicate captured SIG image version
    env:
      SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
      RESOURCE_GROUP_NAME: $(AZURE_RESOURCE_GROUP_NAME)
      DRY_RUN: $(DRY_RUN)

  - task: PublishPipelineArtifact@0
    condition: always()
    displayName: Publish BCC Tools Installation Log
    inputs:
      artifactName: 'bcc-tools-installation-log-$(ARTIFACT_ID)-${{ parameters.artifactName }}'
      targetPath: 'bcc-tools-installation.log'

  - task: CopyFiles@2
    condition: always()
    displayName: Copy BCC Tools Installation Log
    inputs:
      Overwrite: true
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: 'bcc-tools-installation.log'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: CopyFiles@2
    displayName: Copy Trivy Report
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: 'trivy-report.json'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: CopyFiles@2
    displayName: Copy Trivy Table
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: 'trivy-images-table.txt'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: CopyFiles@2
    condition: and(eq(variables.OS_SKU, 'Ubuntu'), in(variables.OS_VERSION, '22.04', '24.04'), in(variables.FEATURE_FLAGS, 'None', 'cvm'))
    displayName: Copy CIS Reports
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: |
        cis-report.html
        cis-report.txt
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishPipelineArtifact@0
    displayName: Publish Release Notes
    inputs:
      artifactName: 'vhd-release-notes-${{ parameters.artifactName }}'
      targetPath: 'release-notes.txt'

  - task: CopyFiles@2
    displayName: Copy Release Notes
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: 'release-notes.txt'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishPipelineArtifact@0
    displayName: Publish Container Image List
    inputs:
      artifactName: 'vhd-image-bom-${{ parameters.artifactName }}'
      targetPath: 'image-bom.json'

  - task: CopyFiles@2
    condition: succeeded()
    displayName: Copy Image Bom
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: 'image-bom.json'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: DownloadPipelineArtifact@2
    displayName: Download Build Performance Program
    condition: and(succeeded(), eq(variables.ENVIRONMENT, 'tme'))
    inputs:
      source: "specific"
      downloadPath: "vhdbuilder/packer/buildperformance"
      runVersion: "latest"
      project: $(System.TeamProject)
      pipeline: $(SOURCE_PIPELINE)
      artifactName: $(BUILD_PERFORMANCE_ARTIFACT_NAME)

  - bash: make -f packer.mk evaluate-build-performance
    condition: always()
    displayName: Check Build Performance

  - task: DownloadPipelineArtifact@2
    displayName: Download Grid Compatibility Program
    condition: and(succeeded(), ne(variables.ENVIRONMENT, 'tme'))
    inputs:
      source: "specific"
      downloadPath: "vhdbuilder/packer/gridcompatibility"
      runVersion: "latest"
      project: $(System.TeamProject)
      pipeline: 431951
      artifactName: "drop_gridCompatibilityProgram"

  - bash: make -f packer.mk evaluate-grid-compatibility
    condition: always()
    continueOnError: true
    displayName: Check Grid Compatibility

  - bash: make -f packer.mk generate-publishing-info
    displayName: Generate Publishing Info
    condition: and(succeeded(), eq(variables.GENERATE_PUBLISHING_INFO, 'True'))
    env:
      RESOURCE_GROUP_NAME: $(AZURE_RESOURCE_GROUP_NAME)
      STORAGE_ACCT_BLOB_URL: $(CLASSIC_BLOB)
      OFFER_NAME: $(OS_SKU)

  - task: PublishPipelineArtifact@1
    condition: and(succeeded(), eq(variables.GENERATE_PUBLISHING_INFO, 'True'))
    displayName: Publish Publishing Info
    inputs:
      artifactName: 'publishing-info-${{ parameters.artifactName }}'
      targetPath: 'vhd-publishing-info.json'

  - task: CopyFiles@2
    condition: and(succeeded(), eq(variables.GENERATE_PUBLISHING_INFO, 'True'))
    displayName: Copy Publishing Info
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: 'vhd-publishing-info.json'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishPipelineArtifact@0
    condition: succeeded()
    displayName: Publish Artifacts
    inputs:
      artifactName: '${{ parameters.artifactName }}'
      targetPath: '$(Build.ArtifactStagingDirectory)'
