stages:
  - stage: build_vhd_2019_containerd
    dependsOn: []
    condition: eq('${{ parameters.build2019containerd }}', True)
    jobs:
    - job: build
      pool:
        type: linux
        isCustom: true
        name: $(AZURE_POOL_NAME)
      variables:
        ob_outputDirectory: '$(Build.ArtifactStagingDirectory)/out'
        ob_artifactSuffix: v1
        ob_artifactBaseName: drop_test
      timeoutInMinutes: 180
      steps:
        - bash: |
            echo '##vso[task.setvariable variable=VHD_DEBUG]${{parameters.vhddebug}}'
            echo '##vso[task.setvariable variable=DRY_RUN]${{parameters.dryrun}}'
            echo '##vso[task.setvariable variable=HYPERV_GENERATION]V1'
            echo '##vso[task.setvariable variable=AZURE_VM_SIZE]Standard_D4s_v3'
            echo '##vso[task.setvariable variable=WINDOWS_SKU]2019-containerd'
            echo '##vso[task.setvariable variable=WINDOWS_BASE_IMAGE_URL]$(WINDOWS_2019_BASE_IMAGE_URL)'
            echo '##vso[task.setvariable variable=WINDOWS_NANO_IMAGE_URL]$(WINDOWS_2019_NANO_IMAGE_URL)'
            echo '##vso[task.setvariable variable=WINDOWS_CORE_IMAGE_URL]$(WINDOWS_2019_CORE_IMAGE_URL)'
            echo '##vso[task.setvariable variable=WINDOWS_PRIVATE_PACKAGES_URL]$(PRIVATE_PACKAGES_URL)'
          displayName: Setup Build Variables
        - template: .builder-release-template-windows.yaml
          parameters:
            artifactName: 2019-containerd

  - stage: build_vhd_2022_containerd
    dependsOn: []
    condition: eq('${{ parameters.build2022containerd }}', True)
    jobs:
    - job: build
      pool:
        type: linux
        isCustom: true
        name: $(AZURE_POOL_NAME)
      variables:
        ob_outputDirectory: '$(Build.SourcesDirectory)/out'
      timeoutInMinutes: 180
      steps:
        - bash: |
            echo '##vso[task.setvariable variable=VHD_DEBUG]${{parameters.vhddebug}}'
            echo '##vso[task.setvariable variable=DRY_RUN]${{parameters.dryrun}}'
            echo '##vso[task.setvariable variable=HYPERV_GENERATION]V1'
            echo '##vso[task.setvariable variable=AZURE_VM_SIZE]Standard_D4s_v3'
            echo '##vso[task.setvariable variable=WINDOWS_SKU]2022-containerd'
            echo '##vso[task.setvariable variable=WINDOWS_BASE_IMAGE_URL]$(WINDOWS_2022_BASE_IMAGE_URL)'
            echo '##vso[task.setvariable variable=WINDOWS_NANO_IMAGE_URL]$(WINDOWS_2022_NANO_IMAGE_URL)'
            echo '##vso[task.setvariable variable=WINDOWS_CORE_IMAGE_URL]$(WINDOWS_2022_CORE_IMAGE_URL)'
            echo '##vso[task.setvariable variable=WINDOWS_PRIVATE_PACKAGES_URL]$(PRIVATE_PACKAGES_URL)'
          displayName: Setup Build Variables
        - template: .builder-release-template-windows.yaml
          parameters:
            artifactName: 2022-containerd

  - stage: build_vhd_2022_containerd_gen2
    dependsOn: []
    condition: eq('${{ parameters.build2022containerdgen2 }}', True)
    jobs:
    - job: build
      pool:
        type: linux
        isCustom: true
        name: $(AZURE_POOL_NAME)
      variables:
        ob_outputDirectory: '$(Build.SourcesDirectory)/out'
      timeoutInMinutes: 180
      steps:
        - bash: |
            echo '##vso[task.setvariable variable=VHD_DEBUG]${{parameters.vhddebug}}'
            echo '##vso[task.setvariable variable=DRY_RUN]${{parameters.dryrun}}'
            echo '##vso[task.setvariable variable=HYPERV_GENERATION]V2'
            echo '##vso[task.setvariable variable=AZURE_VM_SIZE]Standard_D4s_v3'
            echo '##vso[task.setvariable variable=WINDOWS_SKU]2022-containerd-gen2'
            echo '##vso[task.setvariable variable=WINDOWS_BASE_IMAGE_URL]$(WINDOWS_2022_GEN2_BASE_IMAGE_URL)'
            echo '##vso[task.setvariable variable=WINDOWS_NANO_IMAGE_URL]$(WINDOWS_2022_NANO_IMAGE_URL)'
            echo '##vso[task.setvariable variable=WINDOWS_CORE_IMAGE_URL]$(WINDOWS_2022_CORE_IMAGE_URL)'
            echo '##vso[task.setvariable variable=WINDOWS_PRIVATE_PACKAGES_URL]$(PRIVATE_PACKAGES_URL)'
          displayName: Setup Build Variables
        - template: .builder-release-template-windows.yaml
          parameters:
            artifactName: 2022-containerd-gen2

  - stage: build_vhd_23H2
    dependsOn: []
    condition: eq('${{ parameters.build23H2 }}', True)
    jobs:
    - job: build
      pool:
        type: linux
        isCustom: true
        name: $(AZURE_POOL_NAME)
      variables:
        ob_outputDirectory: '$(Build.SourcesDirectory)/out'
      timeoutInMinutes: 180
      steps:
        - bash: |
            echo '##vso[task.setvariable variable=VHD_DEBUG]${{parameters.vhddebug}}'
            echo '##vso[task.setvariable variable=DRY_RUN]${{parameters.dryrun}}'
            echo '##vso[task.setvariable variable=HYPERV_GENERATION]V1'
            echo '##vso[task.setvariable variable=AZURE_VM_SIZE]Standard_D4s_v3'
            echo '##vso[task.setvariable variable=WINDOWS_SKU]23H2'
            echo '##vso[task.setvariable variable=WINDOWS_BASE_IMAGE_URL]$(WINDOWS_23H2_BASE_IMAGE_URL)'
            echo '##vso[task.setvariable variable=WINDOWS_NANO_IMAGE_URL]$(WINDOWS_2022_NANO_IMAGE_URL)'
            echo '##vso[task.setvariable variable=WINDOWS_CORE_IMAGE_URL]$(WINDOWS_2022_CORE_IMAGE_URL)'
            echo '##vso[task.setvariable variable=WINDOWS_PRIVATE_PACKAGES_URL]$(PRIVATE_PACKAGES_URL)'
          displayName: Setup Build Variables
        - template: .builder-release-template-windows.yaml
          parameters:
            artifactName: 23H2

  - stage: build_vhd_23H2_gen2
    dependsOn: []
    condition: eq('${{ parameters.build23H2gen2 }}', True)
    jobs:
    - job: build
      pool:
        type: linux
        isCustom: true
        name: $(AZURE_POOL_NAME)
      variables:
        ob_outputDirectory: '$(Build.SourcesDirectory)/out'
      timeoutInMinutes: 180
      steps:
        - bash: |
            echo '##vso[task.setvariable variable=VHD_DEBUG]${{parameters.vhddebug}}'
            echo '##vso[task.setvariable variable=DRY_RUN]${{parameters.dryrun}}'
            echo '##vso[task.setvariable variable=HYPERV_GENERATION]V2'
            echo '##vso[task.setvariable variable=AZURE_VM_SIZE]Standard_D4s_v3'
            echo '##vso[task.setvariable variable=WINDOWS_SKU]23H2-gen2'
            echo '##vso[task.setvariable variable=WINDOWS_BASE_IMAGE_URL]$(WINDOWS_23H2_GEN2_BASE_IMAGE_URL)'
            echo '##vso[task.setvariable variable=WINDOWS_NANO_IMAGE_URL]$(WINDOWS_2022_NANO_IMAGE_URL)'
            echo '##vso[task.setvariable variable=WINDOWS_CORE_IMAGE_URL]$(WINDOWS_2022_CORE_IMAGE_URL)'
            echo '##vso[task.setvariable variable=WINDOWS_PRIVATE_PACKAGES_URL]$(PRIVATE_PACKAGES_URL)'
          displayName: Setup Build Variables
        - template: .builder-release-template-windows.yaml
          parameters:
            artifactName: 23H2-gen2
  
  - stage: backfill_cleanup_outdated_resources
    dependsOn: []
    condition: always()
    jobs:
    - job: build
      pool:
        type: linux
        isCustom: true
        name: $(AZURE_POOL_NAME)
      timeoutInMinutes: 180
      steps:
        - bash: |
            m="windowsVhdMode"
            echo "Set build mode to $m" && \
            docker run --rm \
            -v ${PWD}:/go/src/github.com/Azure/AgentBaker \
            -w /go/src/github.com/Azure/AgentBaker \
            -e CLIENT_ID=${AZURE_BUILD_CLIENT_ID} \
            -e CLIENT_SECRET="$(AZURE_BUILD_CLIENT_SECRET)" \
            -e TENANT_ID=${AZURE_BUILD_TENANT_ID} \
            -e SUBSCRIPTION_ID="${AZURE_BUILD_SUBSCRIPTION_ID}" \
            -e PROD_SUBSCRIPTION_ID=${AZURE_PROD_SUBSCRIPTION_ID} \
            -e AZURE_RESOURCE_GROUP_NAME=${AZURE_BUILD_RESOURCE_GROUP_NAME} \
            -e MODE=$m \
            -e DRY_RUN=${DRY_RUN} \
            -e SIG_GALLERY_NAME=${SIG_GALLERY_NAME} \
            -e OS_TYPE="Windows" \
            ${AZURE_CONTAINER_IMAGE} make -f packer.mk backfill-cleanup
          displayName: Backfill Clean Up Older Resources
          condition: eq(variables.ENABLE_BACKFILL_CLEANUP, 'True')