parameters:
- name: VHD_BUILD_ID
  type: string
- name: IMAGE_VERSION_OVERRIDE
  type: string
  default: ""

steps:
- bash: |
    [ -n "$IMAGE_VERSION_OVERRIDE" ] && echo "IMAGE_VERSION_OVERRIDE is set to $IMAGE_VERSION_OVERRIDE" && exit 0
    source vhdbuilder/scripts/automate_generate_version.sh
    echo "setting image version to $GENERATED_IMAGE_VERSION"
    echo "##vso[task.setvariable variable=IMAGE_VERSION]$GENERATED_IMAGE_VERSION"
  env:
    VHD_BUILD_ID: ${{ parameters.VHD_BUILD_ID }}
  displayName: 'Set image version'
- bash: |
    echo "removing dangling publishing-info.json artifacts..."
    rm -f *vhd-publishing-info.json
  displayName: 'Cleanup publishing-info.json artifacts'