parameters:
- name: BUILD_ID
  type: string
- name: IMAGE_VERSION
  type: string

steps:
- bash: |
    /bin/bash vhdbuilder/scripts/automate_generate_version.sh
    echo "setting image version to $IMAGE_VERSION"
    echo "##vso[task.setvariable variable=IMAGE_VERSION]$IMAGE_VERSION"
  env:
    BUILD_ID: ${{ parameters.BUILD_ID }}
    IMAGE_VERSION: ${{ parameters.IMAGE_VERSION_OVERRIDE }}
  displayName: 'Set image version'