stages:
  - stage: versioning
    jobs:
      - job: set_image_version
        displayName: Set Image Version
        steps:
          - bash: |
              # YYYYMM.DD.PATCH, PATCH starts at 0
              IMAGE_VERSION="$(date +%Y%m.%d.0)"
              if [ -n "$IMAGE_VERSION_OVERRIDE" ]; then
                IMAGE_VERSION="$IMAGE_VERSION_OVERRIDE"
              fi
              echo "will use image version: $IMAGE_VERSION"
              echo "##vso[task.setvariable variable=IMAGE_VERSION;isOutput=true]$IMAGE_VERSION"
            displayName: Set image version
            name: imageVersion
