parameters:
- name: VHD_BUILD_ID
  type: string

steps:
- bash: |
    [ -n "$IMAGE_VERSION" ] && echo "IMAGE_VERSION is already set to $IMAGE_VERSION" && exit 0
    source vhdbuilder/scripts/automate_generate_version.sh
    echo "setting image version to $GENERATED_IMAGE_VERSION"
    echo "##vso[task.setvariable variable=IMAGE_VERSION]$GENERATED_IMAGE_VERSION"
  env:
    VHD_BUILD_ID: ${{ parameters.VHD_BUILD_ID }}
    IMAGE_VERSION: ${{ parameters.IMAGE_VERSION }}
  displayName: 'Set image version'
- bash: |
    echo "removing dangling publishing-info.json artifacts..."
    rm -f *vhd-publishing-info.json
  displayName: 'Cleanup publishing-info.json artifacts'