jobs:
  - job: E2E_Tests
    pool:
      name: nodesigtest-pool
    timeoutInMinutes: 90
    displayName: Run AgentBaker E2E
    variables:
      - group: ab-e2e
    steps:
      - bash: |
          set -ex
          az login --identity
          az account set -s $(AZURE_SUBSCRIPTION_ID)
        displayName: Azure login
      - bash: bash .pipelines/scripts/setup_go.sh
        displayName: Setup go
      - bash: |
          set -ex
          LOGGING_DIR="scenario-logs-$(date +%s)"
          echo "setting logging dir to $LOGGING_DIR"
          echo "##vso[task.setvariable variable=LOGGING_DIR]$LOGGING_DIR"
        displayName: Set logging directory
      - bash: |
          set -ex
          export PATH="/usr/local/go/bin:$PATH"
          go version
          
          echo "VHD_BUILD_ID=$VHD_BUILD_ID"
          
          if [ -n "${VHD_BUILD_ID}" ]; then
            export SIG_VERSION_TAG_NAME=buildId
            export SIG_VERSION_TAG_VALUE=$VHD_BUILD_ID
            export IGNORE_SCENARIOS_WITH_MISSING_VHD=true
          else
            echo "Build.BuildId is not specified. Running default e2e tests."
          fi
          
          cd e2e
          mkdir -p bin
          GOBIN=`pwd`/bin/ go install github.com/jstemmer/go-junit-report/v2@latest
          go test -v -parallel 100 -timeout 90m 2>&1 | ./bin/go-junit-report -iocopy -set-exit-code -out "$(Build.SourcesDirectory)/e2e/report.xml"
        displayName: Run AgentBaker E2E
        env:
          VHD_BUILD_ID: $(VHD_BUILD_ID)
          LOCATION: $(LOCATION)
          LOGGING_DIR: $(LOGGING_DIR)
      # Without this step next step may fail on successful run
      - bash: mkdir -p $(System.DefaultWorkingDirectory)/e2e/$(LOGGING_DIR)
        condition: always()
        displayName: Create folder for scenario logs
      - task: PublishTestResults@2
        displayName: Upload test results
        condition: succeededOrFailed()
        inputs:
          testRunner: JUnit
          testResultsFiles: "$(Build.SourcesDirectory)/e2e/report.xml"
      - publish: $(System.DefaultWorkingDirectory)/e2e/$(LOGGING_DIR)
        artifact: $(LOGGING_DIR)
        condition: always()
        continueOnError: true
      - bash: |
          set -x
          
          vmssResourceIds=""
          for vmssModel in e2e/scenario-logs/*/vmssId.txt; do
            resourceId=$(cat ${vmssModel})
            vmssResourceIds="${vmssResourceIds} ${resourceId}"
          done
          
          if [ -n "${vmssResourceIds// }" ]; then
            az resource delete --ids ${vmssResourceIds}
          fi
        displayName: ensure vmss deletion
        condition: always()
