# ====== BEGIN AKS BOOTSTRAP VARIABLES ======
# Every value that AgentBaker renders into this script is assigned in this block, and only here.
# The rest of the script is plain PowerShell that reads these variables.
# pkg/agent/windows_bootstrap_template_test.go enforces this.
$MasterIP="cluster-dns-abc123.hcp.eastus.azmk8s.io"
$KubeDnsServiceIp="10.0.0.10"
$MasterFQDNPrefix="cluster-dns"
$Location="customcloudregion"

$TargetEnvironment="akscustom"
$ArmResourceEndpoint="https://management.custom.example/"
$AADClientId="22222222-3333-4444-5555-666666666666"

# These globals will not change between nodes in the same cluster, so they are not
# passed as powershell parameters

## SSH public keys to add to authorized_keys
$global:SSHKeys=@( [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCQVFDNyBmaXJzdEBleGFtcGxl')), [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUIgc2Vjb25kQGV4YW1wbGU=')) )

## Certificates generated by aks-engine
$global:CACertificate="LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJmYWtlQ0EKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
$global:AgentCertificate="LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJmYWtlQ2xpZW50Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"

## Download sources provided by aks-engine
$global:KubeBinariesPackageSASURL="https://packages.aks.azure.com/kubernetes/v1.33.2/windowszip/v1.33.2-1int.zip"
$global:WindowsKubeBinariesURL=""
$global:KubeBinariesVersion="1.33.2"
$global:ContainerdUrl="https://packages.aks.azure.com/containerd/windows/"
$global:ContainerdSdnPluginUrl=""

## Docker Version
$global:DockerVersion="20.10.9"

## ContainerD Usage
$global:DefaultContainerdWindowsSandboxIsolation="process"
$global:ContainerdWindowsRuntimeHandlers=""

## VM configuration passed by Azure
$global:WindowsTelemetryGUID="fb801154-36b9-41bc-89c2-f4d4f05472b0"
$global:TenantId="72f988bf-86f1-41af-91ab-2d7cd011db47"
$global:SubscriptionId="00000000-0000-0000-0000-000000000001"
$global:ResourceGroup="MC_rg_cluster_eastus"
$global:VmType="vmss"
$global:SubnetName="aks-subnet"
$global:SecurityGroupName="aks-agentpool-18663747-nsg"
$global:VNetName="aks-vnet-18663747"
$global:RouteTableName="aks-agentpool-18663747-routetable"
$global:PrimaryAvailabilitySetName=""
$global:PrimaryScaleSetName="akswinnp"

$global:KubeClusterCIDR="10.244.0.0/16"
$global:KubeServiceCIDR="10.0.0.0/16"
$global:VNetCIDR="10.224.0.0/12"
$global:KubeletNodeLabels="agentpool=winnp,kubernetes.azure.com/agentpool=winnp,kubernetes.azure.com/mode=user,team=payments"
$global:KubeletConfigArgs=@( "--azure-container-registry-config=c:\k\azure.json", "--bootstrap-kubeconfig=c:\k\bootstrap-config", "--cert-dir=c:\k\pki", "--cgroups-per-qos=false", "--client-ca-file=c:\k\ca.crt", "--cloud-provider=external", "--cluster-dns=10.0.0.10", "--cluster-domain=cluster.local", "--enforce-node-allocatable=""""", "--eviction-hard=""""", "--feature-gates=RotateKubeletServerCertificate=true", "--hairpin-mode=promiscuous-bridge", "--image-gc-high-threshold=90", "--kube-reserved=cpu=100m,memory=3891Mi", "--kubeconfig=c:\k\config", "--max-pods=30", "--node-status-update-frequency=10s", "--resolv-conf=""""", "--rotate-certificates=true", "--rotate-server-certificates=true", "--tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256" )
$global:KubeletHealthzEndpoint="http://127.0.0.1:10248/healthz"
$global:KubeproxyConfigArgs=@( "--metrics-bind-address=0.0.0.0:10249" )

$global:KubeproxyFeatureGates=@( "WinDSR=true", "WinOverlay=false" )

$global:UseManagedIdentityExtension="false"
$global:UseInstanceMetadata="true"

$global:LoadBalancerSku="Standard"
$global:ExcludeMasterFromStandardLB="true"

$global:PrivateEgressProxyAddress=""

# Azure cni configuration
$global:NetworkPlugin="azure"
$global:VNetCNIPluginsURL="https://packages.aks.azure.com/azure-cni/v1.6.21/binaries/azure-vnet-cni-windows-amd64-v1.6.21.zip"
$global:IsDualStackEnabled=$true 
$global:IsAzureCNIOverlayEnabled=$true 
$global:CiliumDataplaneEnabled=$false 
$global:IsIMDSRestrictionEnabled=$false 

# Kubelet credential provider
$global:CredentialProviderURL="https://packages.aks.azure.com/cloud-provider-azure/v1.33.2/binaries/azure-acr-credential-provider-windows-amd64-v1.33.2.tar.gz"

# CSI Proxy settings
$global:EnableCsiProxy=[System.Convert]::ToBoolean("true");
$global:CsiProxyUrl="https://packages.aks.azure.com/csi-proxy/v1.1.2-hotfix.20230807/binaries/csi-proxy-v1.1.2-hotfix.20230807.tar.gz";

# Hosts Config Agent settings
$global:EnableHostsConfigAgent=[System.Convert]::ToBoolean("false");

# These scripts are used by cse
$global:CSEScriptsPackageUrl="https://packages.aks.azure.com/aks/windows/cse/";

# The windows nvidia gpu driver related url is used by windows cse
$global:GpuDriverURL="";

# PauseImage
$global:WindowsPauseImageURL="mcr.microsoft.com/oss/v2/kubernetes/pause:3.10.2";
$global:AlwaysPullWindowsPauseImage=[System.Convert]::ToBoolean("false");

# Calico
$global:WindowsCalicoPackageURL="";

## GPU install
$global:ConfigGPUDriverIfNeeded=[System.Convert]::ToBoolean("true");

# GMSA
$global:WindowsGmsaPackageUrl="https://packages.aks.azure.com/windows/gmsa/windows-gmsa-ccgakvplugin-v1.1.9.zip";

# TLS Bootstrap Token
$global:TLSBootstrapToken="07401b.f395accd246ae52d"

# Secure TLS Bootstrap settings
$global:EnableSecureTLSBootstrapping=[System.Convert]::ToBoolean("false");
$global:SecureTLSBootstrappingAADResource="";
$global:SecureTLSBootstrappingUserAssignedIdentityID="";
$global:CustomSecureTLSBootstrappingClientDownloadURL="";
$global:SecureTLSBootstrappingValidateKubeconfigTimeout="";
$global:SecureTLSBootstrappingGetAccessTokenTimeout="";
$global:SecureTLSBootstrappingGetInstanceDataTimeout="";
$global:SecureTLSBootstrappingGetNonceTimeout="";
$global:SecureTLSBootstrappingGetAttestedDataTimeout="";
$global:SecureTLSBootstrappingGetCredentialTimeout="";

# Disable OutBoundNAT in Azure CNI configuration
$global:IsDisableWindowsOutboundNat=[System.Convert]::ToBoolean("true");

$fipsEnabled=[System.Convert]::ToBoolean("false")

# HNS remediator
$global:HNSRemediatorIntervalInMinutes=[System.Convert]::ToUInt32("0");

# Log generator
$global:LogGeneratorIntervalInMinutes=[System.Convert]::ToUInt32("0");

$global:IsSkipCleanupNetwork=[System.Convert]::ToBoolean("true");
$PreProvisionOnly=[System.Convert]::ToBoolean("false");

$global:EnableKubeletServingCertificateRotation=[System.Convert]::ToBoolean("true")

# Windows Cilium Networking (WCN) Platform configuration
$global:EnableWindowsCiliumNetworking=[System.Convert]::ToBoolean("false");
$global:WindowsCiliumNetworkingConfiguration="";

# Network isolated cluster
$global:BootstrapProfileContainerRegistryServer=""
$global:MCRRepositoryBase="mcr.microsoft.com/"
$global:NetworkIsolatedClusterTestMode=[System.Convert]::ToBoolean("false"); # for ab e2e only for local ab test with remote cse package

# Values used by BasePrep and NodePrep
$WindowsSSHEnabled=[System.Convert]::ToBoolean("false")
$IsAKSCustomCloud=[System.Convert]::ToBoolean("true")

$AKSCustomCloudContainerRegistryDNSSuffix=".azurecr.custom.example"
$AKSCustomCloudEnvironmentJSONBase64="eyJuYW1lIjoiQXp1cmVTdGFja0Nsb3VkIiwiTmFtZSI6IkF6dXJlU3RhY2tDbG91ZCIsIm1jclVSTCI6Im1jci5taWNyb3NvZnQuY3VzdG9tLmV4YW1wbGUiLCJyZXNvdXJjZU1hbmFnZXJFbmRwb2ludCI6Imh0dHBzOi8vbWFuYWdlbWVudC5jdXN0b20uZXhhbXBsZS8iLCJhY3RpdmVEaXJlY3RvcnlFbmRwb2ludCI6Imh0dHBzOi8vbG9naW4uY3VzdG9tLmV4YW1wbGUvIiwicmVzb3VyY2VNYW5hZ2VyVk1ETlNTdWZmaXgiOiJjbG91ZGFwcC5jdXN0b20uZXhhbXBsZSIsImNvbnRhaW5lclJlZ2lzdHJ5RE5TU3VmZml4IjoiLmF6dXJlY3IuY3VzdG9tLmV4YW1wbGUiLCJyZXNvdXJjZUlkZW50aWZpZXJzIjp7fX0="

$IdentitySystem="azure_ad"
# ====== END AKS BOOTSTRAP VARIABLES ======
