# ====== BEGIN AKS BOOTSTRAP VARIABLES ======
# Every value that AgentBaker renders into this script is assigned in this block, and only here.
# The rest of the script is plain PowerShell that reads these variables.
# pkg/agent/windows_bootstrap_template_test.go enforces this.
$MasterIP="distinct-apiserver.example"
$KubeDnsServiceIp="10.101.0.10"
$MasterFQDNPrefix="distinct-dns-prefix"
$Location="westus3"

$UserAssignedClientID="distinct-kubelet-identity"

$TargetEnvironment="akscustom"
$ArmResourceEndpoint="https://distinct-management.example/"
$AADClientId="distinct-sp-client-id"

# These globals will not change between nodes in the same cluster, so they are not
# passed as powershell parameters

## SSH public keys to add to authorized_keys
$global:SSHKeys=@( [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('c3NoLWVkMjU1MTkgQUFBQWRpc3RpbmN0IG9ubHlAZXhhbXBsZQ==')) )

## Certificates generated by aks-engine
$global:CACertificate="ZGlzdGluY3QtY2EtY2VydGlmaWNhdGU="
$global:AgentCertificate="ZGlzdGluY3QtY2xpZW50LWNlcnRpZmljYXRl"

## Download sources provided by aks-engine
$global:KubeBinariesPackageSASURL="https://distinct.example/kubernetes.zip"
$global:WindowsKubeBinariesURL=""
$global:KubeBinariesVersion="1.32.7"
$global:ContainerdUrl="https://distinct.example/containerd/"
$global:ContainerdSdnPluginUrl="https://distinct.example/sdn.zip"

## Docker Version
$global:DockerVersion="distinct-docker-version"

## ContainerD Usage
$global:DefaultContainerdWindowsSandboxIsolation="hyperv"
$global:ContainerdWindowsRuntimeHandlers="17763,20348"

## VM configuration passed by Azure
$global:WindowsTelemetryGUID="distinct-telemetry-guid"
$global:TenantId="distinct-tenant"
$global:SubscriptionId="distinct-subscription"
$global:ResourceGroup="distinct-node-resource-group"
$global:VmType="standard"
$global:SubnetName="distinct-subnet"
$global:SecurityGroupName="aks-agentpool-15870020-nsg"
$global:VNetName="distinct-vnet"
$global:RouteTableName="aks-agentpool-15870020-routetable"
$global:PrimaryAvailabilitySetName="winnp-availabilitySet-15870020"
$global:PrimaryScaleSetName="distinct-scale-set"

$global:KubeClusterCIDR="10.100.0.0/16"
$global:KubeServiceCIDR="10.101.0.0/16"
$global:VNetCIDR="10.102.0.0/16"
$global:KubeletNodeLabels="agentpool=winnp,kubernetes.azure.com/agentpool=winnp,kubernetes.azure.com/mode=user,team=payments"
$global:KubeletConfigArgs=@( "--azure-container-registry-config=c:\k\azure.json", "--bootstrap-kubeconfig=c:\k\bootstrap-config", "--cert-dir=c:\k\pki", "--cgroups-per-qos=false", "--client-ca-file=c:\k\ca.crt", "--cloud-provider=external", "--cluster-dns=10.0.0.10", "--cluster-domain=cluster.local", "--enforce-node-allocatable=""""", "--eviction-hard=""""", "--feature-gates=RotateKubeletServerCertificate=true", "--hairpin-mode=promiscuous-bridge", "--healthz-port=10299", "--image-gc-high-threshold=90", "--kube-reserved=cpu=100m,memory=3891Mi", "--kubeconfig=c:\k\config", "--max-pods=30", "--node-status-update-frequency=10s", "--resolv-conf=""""", "--rotate-certificates=true", "--tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256" )
$global:KubeletHealthzEndpoint="http://127.0.0.1:10299/healthz"
$global:KubeproxyConfigArgs=@( "--metrics-bind-address=0.0.0.0:10249", "--v=4" )

$global:KubeproxyFeatureGates=@( "WinDSR=true", "WinOverlay=false" )

$global:UseManagedIdentityExtension="true"
$global:UseInstanceMetadata="false"

$global:LoadBalancerSku="Basic"
$global:ExcludeMasterFromStandardLB="true"

$global:PrivateEgressProxyAddress="http://10.1.2.3:8080"

# Azure cni configuration
$global:NetworkPlugin="azure"
$global:VNetCNIPluginsURL="https://distinct.example/azure-cni.zip"
$global:IsDualStackEnabled=$true 
$global:IsAzureCNIOverlayEnabled=$false 
$global:CiliumDataplaneEnabled=$true 
$global:IsIMDSRestrictionEnabled=$true 

# Kubelet credential provider
$global:CredentialProviderURL="https://distinct.example/credential-provider.tar.gz"

# CSI Proxy settings
$global:EnableCsiProxy=[System.Convert]::ToBoolean("false");
$global:CsiProxyUrl="https://distinct.example/csi-proxy.tar.gz";

# Hosts Config Agent settings
$global:EnableHostsConfigAgent=[System.Convert]::ToBoolean("true");

# These scripts are used by cse
$global:CSEScriptsPackageUrl="https://distinct.example/cse/";

# The windows nvidia gpu driver related url is used by windows cse
$global:GpuDriverURL="https://distinct.example/gpu.exe";

# PauseImage
$global:WindowsPauseImageURL="distinct.example/pause:1.0";
$global:AlwaysPullWindowsPauseImage=[System.Convert]::ToBoolean("false");

# Calico
$global:WindowsCalicoPackageURL="https://distinct.example/calico.zip";

## GPU install
$global:ConfigGPUDriverIfNeeded=[System.Convert]::ToBoolean("true");

# GMSA
$global:WindowsGmsaPackageUrl="https://distinct.example/gmsa.zip";

# TLS Bootstrap Token
$global:TLSBootstrapToken="dstnct.0123456789abcdef"

# Secure TLS Bootstrap settings
$global:EnableSecureTLSBootstrapping=[System.Convert]::ToBoolean("false");
$global:SecureTLSBootstrappingAADResource="distinct-aad-resource";
$global:SecureTLSBootstrappingUserAssignedIdentityID="distinct-stls-identity";
$global:CustomSecureTLSBootstrappingClientDownloadURL="https://distinct.example/stls-client.zip";
$global:SecureTLSBootstrappingValidateKubeconfigTimeout="11s";
$global:SecureTLSBootstrappingGetAccessTokenTimeout="12s";
$global:SecureTLSBootstrappingGetInstanceDataTimeout="13s";
$global:SecureTLSBootstrappingGetNonceTimeout="14s";
$global:SecureTLSBootstrappingGetAttestedDataTimeout="15s";
$global:SecureTLSBootstrappingGetCredentialTimeout="16s";

# Disable OutBoundNAT in Azure CNI configuration
$global:IsDisableWindowsOutboundNat=[System.Convert]::ToBoolean("true");

$fipsEnabled=[System.Convert]::ToBoolean("false")

# HNS remediator
$global:HNSRemediatorIntervalInMinutes=[System.Convert]::ToUInt32("3");

# Log generator
$global:LogGeneratorIntervalInMinutes=[System.Convert]::ToUInt32("7");

$global:IsSkipCleanupNetwork=[System.Convert]::ToBoolean("false");
$PreProvisionOnly=[System.Convert]::ToBoolean("false");

$global:EnableKubeletServingCertificateRotation=[System.Convert]::ToBoolean("false")

# Windows Cilium Networking (WCN) Platform configuration
$global:EnableWindowsCiliumNetworking=[System.Convert]::ToBoolean("true");
$global:WindowsCiliumNetworkingConfiguration="distinct-wcn-config";

# Network isolated cluster
$global:BootstrapProfileContainerRegistryServer="distinctacr.azurecr.io"
$global:MCRRepositoryBase="distinct-mcr.example/"
$global:NetworkIsolatedClusterTestMode=[System.Convert]::ToBoolean("false"); # for ab e2e only for local ab test with remote cse package

# Values used by BasePrep and NodePrep
$WindowsSSHEnabled=[System.Convert]::ToBoolean("false")
$IsAKSCustomCloud=[System.Convert]::ToBoolean("true")

$AKSCustomCloudContainerRegistryDNSSuffix=".distinct-registry.example"
$AKSCustomCloudEnvironmentJSONBase64="eyJuYW1lIjoiQXp1cmVTdGFja0Nsb3VkIiwiTmFtZSI6IkF6dXJlU3RhY2tDbG91ZCIsInJlc291cmNlTWFuYWdlckVuZHBvaW50IjoiaHR0cHM6Ly9kaXN0aW5jdC1tYW5hZ2VtZW50LmV4YW1wbGUvIiwiY29udGFpbmVyUmVnaXN0cnlETlNTdWZmaXgiOiIuZGlzdGluY3QtcmVnaXN0cnkuZXhhbXBsZSIsInJlc291cmNlSWRlbnRpZmllcnMiOnt9fQ=="

$IdentitySystem="azure_ad"
# ====== END AKS BOOTSTRAP VARIABLES ======
