# ====== BEGIN AKS BOOTSTRAP VARIABLES ======
# Every value that AgentBaker renders into this script is assigned in this block, and only here.
# The rest of the script is plain PowerShell that reads these variables.
# pkg/agent/windows_bootstrap_template_test.go enforces this.
$MasterIP="cluster-dns-abc123.hcp.eastus.azmk8s.io"
$KubeDnsServiceIp="10.0.0.10"
$MasterFQDNPrefix="cluster-dns"
$Location="eastus"

$UserAssignedClientID="11111111-2222-3333-4444-555555555555"

$TargetEnvironment="AzurePublicCloud"
$ArmResourceEndpoint="https://management.azure.com/"
$AADClientId="msi"

# These globals will not change between nodes in the same cluster, so they are not
# passed as powershell parameters

## SSH public keys to add to authorized_keys
$global:SSHKeys=@(  )

## Certificates generated by aks-engine
$global:CACertificate="LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJmYWtlQ0EKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
$global:AgentCertificate="LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJmYWtlQ2xpZW50Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"

## Download sources provided by aks-engine
$global:KubeBinariesPackageSASURL="https://packages.aks.azure.com/kubernetes/v1.33.2/windowszip/v1.33.2-1int.zip"
$global:WindowsKubeBinariesURL=""
$global:KubeBinariesVersion="1.33.2"
$global:ContainerdUrl="https://packages.aks.azure.com/containerd/windows/"
$global:ContainerdSdnPluginUrl=""

## Docker Version
$global:DockerVersion="20.10.9"

## ContainerD Usage
$global:DefaultContainerdWindowsSandboxIsolation="process"
$global:ContainerdWindowsRuntimeHandlers=""

## VM configuration passed by Azure
$global:WindowsTelemetryGUID="fb801154-36b9-41bc-89c2-f4d4f05472b0"
$global:TenantId="72f988bf-86f1-41af-91ab-2d7cd011db47"
$global:SubscriptionId="00000000-0000-0000-0000-000000000001"
$global:ResourceGroup="MC_rg_cluster_eastus"
$global:VmType="vmss"
$global:SubnetName="aks-subnet"
$global:SecurityGroupName="aks-agentpool-18663747-nsg"
$global:VNetName="aks-vnet-18663747"
$global:RouteTableName="aks-agentpool-18663747-routetable"
$global:PrimaryAvailabilitySetName=""
$global:PrimaryScaleSetName="akswinnp"

$global:KubeClusterCIDR="10.244.0.0/16"
$global:KubeServiceCIDR="10.0.0.0/16"
$global:VNetCIDR="10.224.0.0/12"
$global:KubeletNodeLabels="agentpool=winnp,kubernetes.azure.com/agentpool=winnp,kubernetes.azure.com/mode=user,team=payments"
$global:KubeletConfigArgs=@( "--azure-container-registry-config=c:\k\azure.json", "--bootstrap-kubeconfig=c:\k\bootstrap-config", "--cert-dir=c:\k\pki", "--cgroups-per-qos=false", "--client-ca-file=c:\k\ca.crt", "--cloud-provider=external", "--cluster-dns=10.0.0.10", "--cluster-domain=cluster.local", "--enforce-node-allocatable=""""", "--eviction-hard=""""", "--feature-gates=RotateKubeletServerCertificate=true", "--hairpin-mode=promiscuous-bridge", "--image-gc-high-threshold=90", "--kube-reserved=cpu=100m,memory=3891Mi", "--kubeconfig=c:\k\config", "--max-pods=30", "--node-status-update-frequency=10s", "--resolv-conf=""""", "--rotate-certificates=true", "--rotate-server-certificates=true", "--tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256" )
$global:KubeletHealthzEndpoint="http://127.0.0.1:10248/healthz"
$global:KubeproxyConfigArgs=@( "--metrics-bind-address=0.0.0.0:10249", "--v=3" )

$global:KubeproxyFeatureGates=@( "WinDSR=true", "WinOverlay=false" )

$global:UseManagedIdentityExtension="true"
$global:UseInstanceMetadata="true"

$global:LoadBalancerSku="Standard"
$global:ExcludeMasterFromStandardLB="true"

$global:PrivateEgressProxyAddress="http://10.1.0.5:3128"

# Azure cni configuration
$global:NetworkPlugin="azure"
$global:VNetCNIPluginsURL="https://packages.aks.azure.com/azure-cni/v1.6.21/binaries/azure-vnet-cni-windows-amd64-v1.6.21.zip"
$global:IsDualStackEnabled=$false 
$global:IsAzureCNIOverlayEnabled=$true 
$global:CiliumDataplaneEnabled=$false 
$global:IsIMDSRestrictionEnabled=$true 

# Kubelet credential provider
$global:CredentialProviderURL="https://packages.aks.azure.com/cloud-provider-azure/v1.33.2/binaries/azure-acr-credential-provider-windows-amd64-v1.33.2.tar.gz"

# CSI Proxy settings
$global:EnableCsiProxy=[System.Convert]::ToBoolean("true");
$global:CsiProxyUrl="https://packages.aks.azure.com/csi-proxy/v1.1.2-hotfix.20230807/binaries/csi-proxy-v1.1.2-hotfix.20230807.tar.gz";

# Hosts Config Agent settings
$global:EnableHostsConfigAgent=[System.Convert]::ToBoolean("false");

# These scripts are used by cse
$global:CSEScriptsPackageUrl="https://packages.aks.azure.com/aks/windows/cse/";

# The windows nvidia gpu driver related url is used by windows cse
$global:GpuDriverURL="https://packages.aks.azure.com/windows/gpu/driver.exe";

# PauseImage
$global:WindowsPauseImageURL="mcr.microsoft.com/oss/v2/kubernetes/pause:3.10.2";
$global:AlwaysPullWindowsPauseImage=[System.Convert]::ToBoolean("false");

# Calico
$global:WindowsCalicoPackageURL="https://packages.aks.azure.com/calico-node/v3.24.0/binaries/calico-windows-v3.24.0.zip";

## GPU install
$global:ConfigGPUDriverIfNeeded=[System.Convert]::ToBoolean("true");

# GMSA
$global:WindowsGmsaPackageUrl="https://packages.aks.azure.com/windows/gmsa/windows-gmsa-ccgakvplugin-v1.1.9.zip";

# TLS Bootstrap Token
$global:TLSBootstrapToken=""

# Secure TLS Bootstrap settings
$global:EnableSecureTLSBootstrapping=[System.Convert]::ToBoolean("true");
$global:SecureTLSBootstrappingAADResource="6dae42f8-4368-4678-94ff-3960e28e3630";
$global:SecureTLSBootstrappingUserAssignedIdentityID="";
$global:CustomSecureTLSBootstrappingClientDownloadURL="";
$global:SecureTLSBootstrappingValidateKubeconfigTimeout="30s";
$global:SecureTLSBootstrappingGetAccessTokenTimeout="";
$global:SecureTLSBootstrappingGetInstanceDataTimeout="";
$global:SecureTLSBootstrappingGetNonceTimeout="";
$global:SecureTLSBootstrappingGetAttestedDataTimeout="";
$global:SecureTLSBootstrappingGetCredentialTimeout="1m";

# Disable OutBoundNAT in Azure CNI configuration
$global:IsDisableWindowsOutboundNat=[System.Convert]::ToBoolean("true");

$fipsEnabled=[System.Convert]::ToBoolean("true")

# HNS remediator
$global:HNSRemediatorIntervalInMinutes=[System.Convert]::ToUInt32("1");

# Log generator
$global:LogGeneratorIntervalInMinutes=[System.Convert]::ToUInt32("5");

$global:IsSkipCleanupNetwork=[System.Convert]::ToBoolean("true");
$PreProvisionOnly=[System.Convert]::ToBoolean("true");

$global:EnableKubeletServingCertificateRotation=[System.Convert]::ToBoolean("true")

# Windows Cilium Networking (WCN) Platform configuration
$global:EnableWindowsCiliumNetworking=[System.Convert]::ToBoolean("true");
$global:WindowsCiliumNetworkingConfiguration="";

# Network isolated cluster
$global:BootstrapProfileContainerRegistryServer="privateacr.azurecr.io/aks-managed-repository"
$global:MCRRepositoryBase="mcr.microsoft.com/"
$global:NetworkIsolatedClusterTestMode=[System.Convert]::ToBoolean("false"); # for ab e2e only for local ab test with remote cse package

# Values used by BasePrep and NodePrep
$WindowsSSHEnabled=[System.Convert]::ToBoolean("true")
$IsAKSCustomCloud=[System.Convert]::ToBoolean("false")

$AKSCustomCloudContainerRegistryDNSSuffix=""
$AKSCustomCloudEnvironmentJSONBase64=""

$IdentitySystem="azure_ad"
# ====== END AKS BOOTSTRAP VARIABLES ======
