#!/bin/bash
set -uo pipefail

# aks-hosts-setup.sh
# Resolves A and AAAA records for critical AKS FQDNs and populates /etc/localdns/hosts.
# TARGET_CLOUD is set by CSE (cse_cmd.sh) and persisted via /etc/localdns/cloud-env
# as a systemd EnvironmentFile so it's available on both initial and timer-triggered runs.

HOSTS_FILE="/etc/localdns/hosts"

# Ensure the directory exists
mkdir -p "$(dirname "$HOSTS_FILE")"

# Use TARGET_CLOUD directly. It's available from:
#   1. CSE environment (initial run from enableAKSHostsSetup)
#   2. Systemd EnvironmentFile (timer-triggered runs via aks-hosts-setup.service)
# Falls back to AzurePublicCloud if unset (e.g. older CSE or missing env file).
local_cloud="${TARGET_CLOUD:-AzurePublicCloud}"

# Select critical FQDNs based on the cloud environment.
# Each cloud has its own service endpoints for container registry, identity, ARM, and packages.
# This mirrors the cloud detection in GetCloudTargetEnv (pkg/agent/datamodel/sig_config.go).

# FQDNs common to all clouds.
COMMON_FQDNS=(
    "packages.microsoft.com"            # Microsoft packages
)

# Cloud-specific FQDNs.
case "${local_cloud}" in
    AzureChinaCloud)
        CLOUD_FQDNS=(
            "acs-mirror.azureedge.net"          # K8s binaries mirror
            "mcr.azure.cn"                      # Container registry (China)
            "login.partner.microsoftonline.cn"  # Azure AD (China)
            "management.chinacloudapi.cn"       # ARM (China)
        )
        ;;
    AzureUSGovernmentCloud)
        CLOUD_FQDNS=(
            "acs-mirror.azureedge.net"          # K8s binaries mirror
            "mcr.microsoft.com"                 # Container registry
            "login.microsoftonline.us"          # Azure AD (US Gov)
            "management.usgovcloudapi.net"      # ARM (US Gov)
            "packages.aks.azure.com"            # AKS packages
        )
        ;;
    USNatCloud)
        CLOUD_FQDNS=(
            "mcr.microsoft.com"                        # Container registry
            "login.microsoftonline.eaglex.ic.gov"      # Azure AD (USNat)
            "management.azure.eaglex.ic.gov"           # ARM (USNat)
        )
        ;;
    USSecCloud)
        CLOUD_FQDNS=(
            "mcr.microsoft.com"                           # Container registry
            "login.microsoftonline.microsoft.scloud"      # Azure AD (USSec)
            "management.azure.microsoft.scloud"           # ARM (USSec)
        )
        ;;
    AzureStackCloud)
        # Custom cloud / AGC — endpoints are customer-defined.
        CLOUD_FQDNS=(
            "mcr.microsoft.com"                 # Container registry
        )
        ;;
    AzurePublicCloud|AzureGermanCloud|AzureGermanyCloud|AzureBleuCloud|*)
        # AzurePublicCloud: standard public endpoints.
        # AzureGermanCloud (legacy): retired, uses public endpoints.
        # AzureGermanyCloud (Delos) / AzureBleuCloud: EU sovereign clouds,
        #   use public endpoints for container registry and packages.
        CLOUD_FQDNS=(
            "acs-mirror.azureedge.net"          # K8s binaries mirror
            "mcr.microsoft.com"                 # Container registry
            "login.microsoftonline.com"         # Azure AD / Entra ID
            "management.azure.com"              # ARM
            "packages.aks.azure.com"            # AKS packages
        )
        ;;
esac

# Combine common + cloud-specific FQDNs.
CRITICAL_FQDNS=("${COMMON_FQDNS[@]}" "${CLOUD_FQDNS[@]}")

echo "Detected cloud environment: ${local_cloud}"

# Function to resolve IPv4 addresses for a domain
# Filters output to only include valid IPv4 addresses (rejects NXDOMAIN, SERVFAIL, hostnames, etc.)
resolve_ipv4() {
    local domain="$1"
    local output
    output=$(timeout 3 nslookup -type=A "${domain}" 2>/dev/null) || return 0
    # Parse Address lines (skip server address with #), validate IPv4 format (4 octets of 1-3 digits)
    echo "${output}" | awk '/^Address: / && !/^Address: .*#/ {print $2}' | grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$' || return 0
}

# Function to resolve IPv6 addresses for a domain
# Filters output to only include valid IPv6 addresses (rejects NXDOMAIN, SERVFAIL, hostnames, etc.)
resolve_ipv6() {
    local domain="$1"
    local output
    output=$(timeout 3 nslookup -type=AAAA "${domain}" 2>/dev/null) || return 0
    # Parse Address lines (skip server address with #), validate IPv6 format (must contain : and only hex/colons, min 3 chars)
    echo "${output}" | awk '/^Address: / && !/^Address: .*#/ {print $2}' | grep -E '^[0-9a-fA-F:]{3,}$' | grep ':' || return 0
}

echo "Starting AKS critical FQDN hosts resolution at $(date)"

# Track if we resolved at least one address
RESOLVED_ANY=false

# Start building the hosts file content
HOSTS_CONTENT="# AKS critical FQDN addresses resolved at $(date)
# This file is automatically generated by aks-hosts-setup.service
"

# Resolve each FQDN
for DOMAIN in "${CRITICAL_FQDNS[@]}"; do
    echo "Resolving addresses for ${DOMAIN}..."

    # Get IPv4 and IPv6 addresses using helper functions
    IPV4_ADDRS=$(resolve_ipv4 "${DOMAIN}")
    IPV6_ADDRS=$(resolve_ipv6 "${DOMAIN}")

    # Check if we got any results for this domain
    if [ -z "${IPV4_ADDRS}" ] && [ -z "${IPV6_ADDRS}" ]; then
        echo "  WARNING: No IP addresses resolved for ${DOMAIN}"
        continue
    fi

    RESOLVED_ANY=true
    HOSTS_CONTENT+="
# ${DOMAIN}"

    if [ -n "${IPV4_ADDRS}" ]; then
        for addr in ${IPV4_ADDRS}; do
            HOSTS_CONTENT+="
${addr} ${DOMAIN}"
        done
    fi

    if [ -n "${IPV6_ADDRS}" ]; then
        for addr in ${IPV6_ADDRS}; do
            HOSTS_CONTENT+="
${addr} ${DOMAIN}"
        done
    fi
done

# Check if we resolved at least one domain
if [ "${RESOLVED_ANY}" != "true" ]; then
    echo "WARNING: No IP addresses resolved for any domain at $(date)"
    echo "This is likely a temporary DNS issue. Timer will retry later."
    # Keep existing hosts file intact and exit successfully so systemd doesn't mark unit as failed
    exit 0
fi

# Write the hosts file
echo "Writing addresses to ${HOSTS_FILE}..."
echo "${HOSTS_CONTENT}" > "${HOSTS_FILE}"

echo "AKS critical FQDN hosts resolution completed at $(date)"
