#!/bin/bash
set -euo pipefail

# aks-hosts-setup.sh
# Resolves A and AAAA records for critical AKS FQDNs and populates /etc/localdns/hosts

HOSTS_FILE="/etc/localdns/hosts"

# Ensure the directory exists
mkdir -p "$(dirname "$HOSTS_FILE")"

# Critical AKS FQDNs that should be cached for DNS reliability
CRITICAL_FQDNS=(
    "acs-mirror.azureedge.net"
    "eastus.data.mcr.microsoft.com"
    "login.microsoftonline.com"
    "management.azure.com"
    "mcr.microsoft.com"
    "packages.aks.azure.com"
    "packages.microsoft.com"
)

echo "Starting AKS critical FQDN hosts resolution at $(date)"

# Track if we resolved at least one address
RESOLVED_ANY=false

# Start building the hosts file content
HOSTS_CONTENT="# AKS critical FQDN addresses resolved at $(date)
# This file is automatically generated by aks-hosts-setup.service
"

# Resolve each FQDN
for DOMAIN in "${CRITICAL_FQDNS[@]}"; do
    echo "Resolving addresses for ${DOMAIN}..."

    # Get IPv4 addresses (A records)
    IPV4_ADDRS=$(dig +short A "${DOMAIN}" 2>/dev/null | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' || true)

    # Get IPv6 addresses (AAAA records)
    IPV6_ADDRS=$(dig +short AAAA "${DOMAIN}" 2>/dev/null | grep -E '^[0-9a-fA-F:]+$' || true)

    # Check if we got any results for this domain
    if [[ -z "${IPV4_ADDRS}" ]] && [[ -z "${IPV6_ADDRS}" ]]; then
        echo "  WARNING: No IP addresses resolved for ${DOMAIN}"
        continue
    fi

    RESOLVED_ANY=true
    HOSTS_CONTENT+="
# ${DOMAIN}"

    if [[ -n "${IPV4_ADDRS}" ]]; then
        IPV4_COUNT=$(echo "${IPV4_ADDRS}" | wc -w)
        echo "  Resolved ${IPV4_COUNT} IPv4 address(es)"
        for addr in ${IPV4_ADDRS}; do
            HOSTS_CONTENT+="
${addr} ${DOMAIN}"
        done
    fi

    if [[ -n "${IPV6_ADDRS}" ]]; then
        IPV6_COUNT=$(echo "${IPV6_ADDRS}" | wc -w)
        echo "  Resolved ${IPV6_COUNT} IPv6 address(es)"
        for addr in ${IPV6_ADDRS}; do
            HOSTS_CONTENT+="
${addr} ${DOMAIN}"
        done
    fi
done

# Check if we resolved at least one domain
if [[ "${RESOLVED_ANY}" != "true" ]]; then
    echo "WARNING: No IP addresses resolved for any domain at $(date)"
    echo "This is likely a temporary DNS issue. Timer will retry later."
    # Keep existing hosts file intact and exit successfully so systemd doesn't mark unit as failed
    exit 0
fi

# Write the hosts file
echo "Writing addresses to ${HOSTS_FILE}..."
echo "${HOSTS_CONTENT}" > "${HOSTS_FILE}"

echo "AKS critical FQDN hosts resolution completed at $(date)"
