#!/bin/bash
set -euo pipefail

# localdns_exporter.sh
# Prometheus-compatible metrics exporter for localdns.service
# Reads pre-generated .prom files and outputs them as an HTTP response.
# This script is executed on-demand via systemd socket activation (localdns-exporter.socket)
#
# All metrics are pre-generated by localdns.sh (which runs as root) and written to .prom files:
#   - resources.prom: service status, CPU, and memory metrics (updated every watchdog tick ~6s)
#   - forward_ips.prom: VnetDNS and KubeDNS forward IP info (updated once at startup)
#
# This avoids the exporter needing to query systemd over D-Bus, which fails under DynamicUser=yes
# ("Transport endpoint is not connected") due to namespace isolation.

# Pre-generated .prom files written by localdns.sh
RESOURCES_PROM_FILE="/opt/azure/containers/localdns/resources.prom"
FORWARD_IPS_PROM_FILE="/opt/azure/containers/localdns/forward_ips.prom"

# Read the HTTP request line to extract the path
# Format: "GET /metrics HTTP/1.1"
# Handle read failure gracefully (client disconnected or incomplete request)
if ! read -r REQUEST_LINE; then
    # Client disconnected or sent an incomplete request; exit without error
    exit 0
fi
REQUEST_PATH=$(echo "$REQUEST_LINE" | awk '{print $2}')

# Only serve metrics at /metrics endpoint (Prometheus convention)
if [ "$REQUEST_PATH" != "/metrics" ]; then
    printf "HTTP/1.1 404 Not Found\r\nContent-Type: text/plain\r\n\r\n"
    echo "404 Not Found - Metrics available at /metrics"
    exit 0
fi

# Output HTTP Response in Prometheus Exposition Format
# Note: The empty line after headers is required by HTTP protocol
printf "HTTP/1.1 200 OK\r\nContent-Type: text/plain; version=0.0.4\r\n\r\n"

# Resource metrics (service status, CPU, memory) — pre-generated by localdns.sh
if [ -f "$RESOURCES_PROM_FILE" ]; then
    cat "$RESOURCES_PROM_FILE"
else
    # Fallback if .prom file doesn't exist yet (before first watchdog tick)
    echo "# HELP localdns_service_status Service status from systemctl is-active (1=active, 0=inactive)"
    echo "# TYPE localdns_service_status gauge"
    echo "localdns_service_status{status=\"unknown\"} 0"
    echo "# HELP localdns_memory_usage_bytes Current memory usage in bytes"
    echo "# TYPE localdns_memory_usage_bytes gauge"
    echo "localdns_memory_usage_bytes 0"
    echo "# HELP localdns_cpu_usage_seconds_total Total CPU time consumed in Seconds"
    echo "# TYPE localdns_cpu_usage_seconds_total counter"
    echo "localdns_cpu_usage_seconds_total 0.000000000"
fi

# Forward IP info metrics (VnetDNS, KubeDNS) — pre-generated by localdns.sh
if [ -f "$FORWARD_IPS_PROM_FILE" ]; then
    cat "$FORWARD_IPS_PROM_FILE"
else
    # Fallback if .prom file doesn't exist yet
    echo "# HELP localdns_vnetdns_forward_info VnetDNS forward plugin IP address from corefile"
    echo "# TYPE localdns_vnetdns_forward_info gauge"
    echo "localdns_vnetdns_forward_info{ip=\"unknown\",block=\"none\",status=\"file_missing\"} 0"
    echo "# HELP localdns_kubedns_forward_info KubeDNS forward plugin IP address from corefile"
    echo "# TYPE localdns_kubedns_forward_info gauge"
    echo "localdns_kubedns_forward_info{ip=\"unknown\",block=\"none\",status=\"file_missing\"} 0"
fi
