#!/bin/bash
set -euo pipefail

# localdns_exporter.sh
# Prometheus-compatible metrics exporter for localdns.service
# Scrapes systemd accounting metrics and converts them to Prometheus format
# This script is executed on-demand via systemd socket activation (localdns-exporter.socket)

UNIT="localdns.service"
# Forward IP metrics are pre-generated by localdns.sh and stored in a .prom file
FORWARD_IPS_PROM_FILE="/opt/azure/containers/localdns/forward_ips.prom"

# Read the HTTP request line to extract the path
# Format: "GET /metrics HTTP/1.1"
read -r REQUEST_LINE
REQUEST_PATH=$(echo "$REQUEST_LINE" | awk '{print $2}')

# Only serve metrics at /metrics endpoint (Prometheus convention)
if [ "$REQUEST_PATH" != "/metrics" ]; then
    printf "HTTP/1.1 404 Not Found\r\nContent-Type: text/plain\r\n\r\n"
    echo "404 Not Found - Metrics available at /metrics"
    exit 0
fi

# 1. Determine service status using systemctl is-active
# Returns: active, inactive, failed, activating, deactivating, or unknown
if systemctl is-active "$UNIT" >/dev/null 2>&1; then
    SERVICE_STATUS="active"
else
    SERVICE_STATUS="inactive"
fi

# 2. Scrape Raw Values from systemd
# --value flag prevents needing to parse "Key=Value" strings
# Capture failures gracefully to handle missing/renamed units without exiting
RAW_CPU=$(systemctl show "$UNIT" --property=CPUUsageNSec --value 2>/dev/null || echo "0")
RAW_MEM=$(systemctl show "$UNIT" --property=MemoryCurrent --value 2>/dev/null || echo "0")

# Handle empty or [not set] values
if [ -z "$RAW_CPU" ] || [ "$RAW_CPU" = "[not set]" ]; then
    RAW_CPU=0
fi
if [ -z "$RAW_MEM" ] || [ "$RAW_MEM" = "[not set]" ]; then
    RAW_MEM=0
fi

# 3. Math with Awk (Floating Point Conversion)
# CPU: Nanoseconds -> Seconds (divide by 1e9)
# VMAgent/Kusto will calculate rate() and multiply by 1000 to get millicores
# Memory: Bytes -> Megabytes (divide by 1024*1024)
CPU_SEC=$(awk -v val="$RAW_CPU" 'BEGIN {printf "%.4f", val / 1000000000}')
MEM_MB=$(awk -v val="$RAW_MEM" 'BEGIN {printf "%.2f", val / 1048576}')

# 4. Output HTTP Response in Prometheus Exposition Format
# Note: The empty line after headers is required by HTTP protocol
printf "HTTP/1.1 200 OK\r\nContent-Type: text/plain; version=0.0.4\r\n\r\n"

# Service status metric (info-style gauge with status label)
echo "# HELP localdns_service_status Service status from systemctl is-active (1=active, 0=inactive)"
echo "# TYPE localdns_service_status gauge"
if [ "$SERVICE_STATUS" = "active" ]; then
    echo "localdns_service_status{status=\"active\"} 1"
else
    echo "localdns_service_status{status=\"inactive\"} 0"
fi

# Memory metric
echo "# HELP localdns_memory_usage_mb Current memory usage in Megabytes"
echo "# TYPE localdns_memory_usage_mb gauge"
echo "localdns_memory_usage_mb $MEM_MB"

# CPU metric
echo "# HELP localdns_cpu_usage_seconds_total Total CPU time consumed in Seconds"
echo "# TYPE localdns_cpu_usage_seconds_total counter"
echo "localdns_cpu_usage_seconds_total $CPU_SEC"

# Forward IP info metrics (pre-generated by localdns.sh)
# Read from .prom file if it exists
if [ -f "$FORWARD_IPS_PROM_FILE" ]; then
    cat "$FORWARD_IPS_PROM_FILE"
else
    # Fallback if .prom file doesn't exist yet
    echo "# HELP localdns_vnetdns_forward_info VnetDNS forward plugin IP address from corefile"
    echo "# TYPE localdns_vnetdns_forward_info gauge"
    echo "localdns_vnetdns_forward_info{ip=\"unknown\",status=\"file_missing\"} 0"
    echo "# HELP localdns_kubedns_forward_info KubeDNS forward plugin IP address from corefile"
    echo "# TYPE localdns_kubedns_forward_info gauge"
    echo "localdns_kubedns_forward_info{ip=\"unknown\",status=\"file_missing\"} 0"
fi
