#!/bin/bash
set -euo pipefail

# localdns_exporter.sh
# Prometheus-compatible metrics exporter for localdns.service
# Reads pre-generated .prom files and outputs them as an HTTP response.
# This script is executed on-demand via systemd socket activation (localdns-exporter.socket)
#
# All metrics are pre-generated by localdns.sh (which runs as root) and written to .prom files:
#   - resources.prom: service status, CPU, and memory metrics (updated every watchdog tick ~6s)
#   - forward_ips.prom: VnetDNS and KubeDNS forward IP info (updated once at startup)
#
# This avoids the exporter needing to query systemd over D-Bus, which fails under DynamicUser=yes
# ("Transport endpoint is not connected") due to namespace isolation.

# A scrape client may close the socket after reading enough data (for example, a probe
# that only checks status/headers). Treat that as a normal connection termination so
# socket-activated worker units do not remain in a failed state.
trap 'exit 0' PIPE

# Pre-generated .prom files written by localdns.sh
# LOCALDNS_SCRIPT_PATH is set via Environment= in localdns-exporter@.service
LOCALDNS_SCRIPT_PATH="${LOCALDNS_SCRIPT_PATH:-/opt/azure/containers/localdns}"
RESOURCES_PROM_FILE="${LOCALDNS_SCRIPT_PATH}/resources.prom"
FORWARD_IPS_PROM_FILE="${LOCALDNS_SCRIPT_PATH}/forward_ips.prom"

emit() {
    printf "%s\n" "$*" 2>/dev/null || exit 0
}

emit_raw() {
    printf "%b" "$1" 2>/dev/null || exit 0
}

emit_file() {
    local file="$1"
    while IFS= read -r line || [ -n "$line" ]; do
        emit "$line"
    done < "$file"
}

# Read the HTTP request line to extract the path
# Format: "GET /metrics HTTP/1.1"
# Handle read failure gracefully (client disconnected, incomplete request, or timeout)
if ! read -r -t 5 REQUEST_LINE; then
    # Client disconnected, sent an incomplete request, or timed out; exit without error
    exit 0
fi
REQUEST_PATH=$(echo "$REQUEST_LINE" | awk '{print $2}')

# Only serve metrics at /metrics endpoint (Prometheus convention)
if [ "$REQUEST_PATH" != "/metrics" ]; then
    emit_raw "HTTP/1.1 404 Not Found\r\nContent-Type: text/plain\r\nConnection: close\r\n\r\n"
    emit "404 Not Found - Metrics available at /metrics"
    exit 0
fi

# Output HTTP Response in Prometheus Exposition Format
# Note: The empty line after headers is required by HTTP protocol
emit_raw "HTTP/1.1 200 OK\r\nContent-Type: text/plain; version=0.0.4\r\nConnection: close\r\n\r\n"

# Resource metrics (service status, CPU, memory) — pre-generated by localdns.sh
if [ -f "$RESOURCES_PROM_FILE" ]; then
    emit_file "$RESOURCES_PROM_FILE"
else
    # Fallback if .prom file doesn't exist yet (before first watchdog tick)
    emit "# HELP localdns_service_status CoreDNS process status (1=active, 0=inactive)"
    emit "# TYPE localdns_service_status gauge"
    emit "localdns_service_status{status=\"unknown\"} 0"
    emit "# HELP localdns_memory_usage_bytes Current memory usage in bytes"
    emit "# TYPE localdns_memory_usage_bytes gauge"
    emit "localdns_memory_usage_bytes 0"
    emit "# HELP localdns_cpu_usage_seconds_total Total CPU time consumed in Seconds"
    emit "# TYPE localdns_cpu_usage_seconds_total counter"
    emit "localdns_cpu_usage_seconds_total 0.000000000"
    emit "# HELP localdns_metrics_last_update_timestamp_seconds Unix timestamp of last metrics generation"
    emit "# TYPE localdns_metrics_last_update_timestamp_seconds gauge"
    emit "localdns_metrics_last_update_timestamp_seconds 0"
fi

# Forward IP info metrics (VnetDNS, KubeDNS) — pre-generated by localdns.sh
if [ -f "$FORWARD_IPS_PROM_FILE" ]; then
    emit_file "$FORWARD_IPS_PROM_FILE"
else
    # Fallback if .prom file doesn't exist yet
    emit "# HELP localdns_vnetdns_forward_info VnetDNS forward plugin IP address from corefile"
    emit "# TYPE localdns_vnetdns_forward_info gauge"
    emit "localdns_vnetdns_forward_info{ip=\"unknown\",block=\"none\",status=\"file_missing\"} 0"
    emit "# HELP localdns_kubedns_forward_info KubeDNS forward plugin IP address from corefile"
    emit "# TYPE localdns_kubedns_forward_info gauge"
    emit "localdns_kubedns_forward_info{ip=\"unknown\",block=\"none\",status=\"file_missing\"} 0"
fi
