#!/bin/bash
set -euo pipefail

# mcr-hosts-setup.sh
# Resolves A and AAAA records for mcr.microsoft.com and populates /etc/hosts.testing

HOSTS_FILE="/etc/hosts.testing"
DOMAIN="mcr.microsoft.com"

echo "Starting MCR hosts resolution at $(date)"

# Get IPv4 addresses (A records)
echo "Resolving IPv4 addresses for ${DOMAIN}..."
IPV4_ADDRS=$(dig +short A "${DOMAIN}" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' || true)

# Get IPv6 addresses (AAAA records)
echo "Resolving IPv6 addresses for ${DOMAIN}..."
IPV6_ADDRS=$(dig +short AAAA "${DOMAIN}" | grep -E '^[0-9a-f:]+$' || true)

# Check if we got any results
if [[ -z "${IPV4_ADDRS}" ]] && [[ -z "${IPV6_ADDRS}" ]]; then
    echo "WARNING: No IP addresses resolved for ${DOMAIN} at $(date)"
    echo "This is likely a temporary DNS issue. Timer will retry later."
    # Keep existing hosts file intact and exit successfully so systemd doesn't mark unit as failed
    exit 0
fi

# Populate hosts file
echo "Writing addresses to ${HOSTS_FILE}..."
{
    echo "# MCR addresses resolved at $(date)"
    echo "# This file is automatically generated by mcr-hosts-setup.service"
    echo ""

    if [[ -n "${IPV4_ADDRS}" ]]; then
        echo "# IPv4 addresses"
        for addr in ${IPV4_ADDRS}; do
            echo "${addr} ${DOMAIN}"
        done
    fi

    if [[ -n "${IPV6_ADDRS}" ]]; then
        echo ""
        echo "# IPv6 addresses"
        for addr in ${IPV6_ADDRS}; do
            echo "${addr} ${DOMAIN}"
        done
    fi
} > "${HOSTS_FILE}"

# Log summary
IPV4_COUNT=$(echo "${IPV4_ADDRS}" | wc -w)
IPV6_COUNT=$(echo "${IPV6_ADDRS}" | wc -w)
echo "Successfully updated ${HOSTS_FILE} with ${IPV4_COUNT} IPv4 and ${IPV6_COUNT} IPv6 addresses"

# Optional: Log the actual addresses for debugging
echo "IPv4 addresses: ${IPV4_ADDRS:-none}"
echo "IPv6 addresses: ${IPV6_ADDRS:-none}"

echo "MCR hosts resolution completed at $(date)"
