package main

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"log/slog"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

const (
	defaultNodeCustomDataPath = "/opt/azure/containers/nodecustomdata.yml"
	encodingGZIP              = "gzip"
	encodingBase64            = "base64"
	scriptHotfixBeginMarker   = "# ---- hotfix: auto-generated by hotfix-generate GH Action ----"
	scriptHotfixEndMarker     = "# ---- end hotfix ----"
)

type nodeCustomDataWriteFile struct {
	Path        string `yaml:"path"`
	Permissions string `yaml:"permissions"`
	Encoding    string `yaml:"encoding,omitempty"`
	Owner       string `yaml:"owner"`
	Content     string `yaml:"content"`
}

type nodeCustomData struct {
	WriteFiles []nodeCustomDataWriteFile `yaml:"write_files"`
}

func applyNodeCustomData(path string) error {
	hotfixCfg, err := readHotfixConfig(defaultHotfixVersionPath)
	if err != nil {
		return fmt.Errorf("read hotfix config for nodecustomdata apply: %w", err)
	}
	shouldApplyScriptHotfix := shouldApplyScriptsVersion(Version, hotfixCfg.ScriptsVersion)
	if !shouldApplyScriptHotfix && strings.TrimSpace(hotfixCfg.ScriptsVersion) != "" {
		slog.Info("skipping script hotfix entries due to scripts_version mismatch",
			"current", Version, "target", hotfixCfg.ScriptsVersion)
	}
	return applyNodeCustomDataWithFilter(path, shouldApplyScriptHotfix, nil)
}

func applyNodeCustomDataWriteFiles(path string, predicate func(nodeCustomDataWriteFile) bool) error {
	return applyNodeCustomDataWithFilter(path, true, predicate)
}

func applyNodeCustomDataWithHotfixConfig(path string, hotfixCfg hotfixConfig) error {
	shouldApplyScriptHotfix := shouldApplyScriptsVersion(Version, hotfixCfg.ScriptsVersion)
	return applyNodeCustomDataWithFilter(path, shouldApplyScriptHotfix, nil)
}

func applyNodeCustomDataWithFilter(path string, shouldApplyScriptHotfix bool, predicate func(nodeCustomDataWriteFile) bool) error {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("read nodecustomdata %s: %w", path, err)
	}
	content := string(data)
	if !shouldApplyScriptHotfix {
		content = stripScriptHotfixBlock(content)
	}

	var customData nodeCustomData
	if err := yaml.Unmarshal([]byte(content), &customData); err != nil {
		return fmt.Errorf("unmarshal nodecustomdata %s: %w", path, err)
	}

	for _, file := range customData.WriteFiles {
		if predicate != nil && !predicate(file) {
			continue
		}
		if err := applyNodeCustomDataWriteFile(file); err != nil {
			return fmt.Errorf("apply nodecustomdata write file %s: %w", file.Path, err)
		}
	}

	return nil
}

func stripScriptHotfixBlock(content string) string {
	_, start, _, end, ok := findScriptHotfixBlockBounds(content)
	if !ok {
		return content
	}
	// Trim the newline before the hotfix marker only when it's an actual blank
	// separator line (double newline), so we don't join adjacent YAML lines.
	if start > 1 && content[start-1] == '\n' && content[start-2] == '\n' {
		start--
	}
	return content[:start] + content[end:]
}

func findScriptHotfixBlockBounds(content string) (int, int, int, int, bool) {
	start := strings.Index(content, scriptHotfixBeginMarker)
	if start == -1 {
		return 0, 0, 0, 0, false
	}
	beginLineEndOffset := strings.Index(content[start:], "\n")
	if beginLineEndOffset == -1 {
		return 0, 0, 0, 0, false
	}
	contentStart := start + beginLineEndOffset + 1
	endMarkerOffset := strings.Index(content[contentStart:], scriptHotfixEndMarker)
	if endMarkerOffset == -1 {
		return 0, 0, 0, 0, false
	}
	endMarkerStart := contentStart + endMarkerOffset
	end := endMarkerStart + len(scriptHotfixEndMarker)
	if end < len(content) && content[end] == '\n' {
		end++
	}
	return contentStart, start, endMarkerStart, end, true
}

func applyNodeCustomDataWriteFile(file nodeCustomDataWriteFile) error {
	if file.Path == "" {
		return fmt.Errorf("path is required")
	}
	if file.Owner != "" && file.Owner != "root" {
		return fmt.Errorf("unsupported owner %q", file.Owner)
	}

	mode := os.FileMode(0o644)
	if file.Permissions != "" {
		parsedMode, err := strconv.ParseUint(file.Permissions, 8, 32)
		if err != nil {
			return fmt.Errorf("parse permissions: %w", err)
		}
		mode = os.FileMode(parsedMode)
	}

	contents, err := decodeNodeCustomDataWriteFileContent(file)
	if err != nil {
		return err
	}

	if err := os.MkdirAll(filepath.Dir(file.Path), 0o755); err != nil {
		return fmt.Errorf("create parent directory: %w", err)
	}

	if err := os.WriteFile(file.Path, contents, mode); err != nil {
		return fmt.Errorf("write file: %w", err)
	}

	return nil
}

func decodeNodeCustomDataWriteFileContent(file nodeCustomDataWriteFile) ([]byte, error) {
	switch file.Encoding {
	case "":
		return []byte(file.Content), nil
	case encodingGZIP:
		reader, err := gzip.NewReader(bytes.NewReader([]byte(file.Content)))
		if err != nil {
			return nil, fmt.Errorf("create gzip reader: %w", err)
		}
		defer reader.Close()

		decoded, err := io.ReadAll(reader)
		if err != nil {
			return nil, fmt.Errorf("read gzip content: %w", err)
		}
		return decoded, nil
	case encodingBase64:
		decoded, err := base64.StdEncoding.DecodeString(file.Content)
		if err != nil {
			return nil, fmt.Errorf("decode base64 content: %w", err)
		}
		return decoded, nil
	default:
		return nil, fmt.Errorf("unsupported encoding %q", file.Encoding)
	}
}
