parameters:
- name: DRY_RUN
  displayName: Dry Run
  type: boolean
  default: false

schedules:
- cron: '0 */4 * * *'
  displayName: Scheduled Garbage Collection
  always: true
  branches:
    include:
      - master

pool:
  name: $(POOL_NAME)

jobs:
- job: gc
  displayName: Garbage Collection
  steps:
    - checkout: self
      fetchTags: false
      fetchDepth: 1

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(ARM_SERVICE_CONNECTION)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          chmod +x ./vhdbuilder/scripts/gc.sh
          ./vhdbuilder/scripts/gc.sh
      env:
        SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
        DRY_RUN: ${{ parameters.DRY_RUN }}
      displayName: Garbage collect resource groups
