name: $(Date:yyyyMMdd)$(Rev:.r)_$(Build.SourceBranchName)_$(BuildID)
trigger: none

pool:
  vmImage: ubuntu-18.04

parameters:
- name: build2019
  displayName: Build 2019
  type: boolean
  default: true
- name: build2019containerd
  displayName: Build 2019 containerd
  type: boolean
  default: true
- name: dryrun
  displayName: Dry run
  type: boolean
  default: true

variables:
  CONTAINER_IMAGE:  'mcr.microsoft.com/oss/azcu/go-dev:v1.34.0'

stages:
  - stage: build_vhd_2019
    condition: eq('${{ parameters.build2019 }}', true)
    jobs:
    - job: build
      timeoutInMinutes: 180
      steps:
        - bash: |
            echo '##vso[task.setvariable variable=DRY_RUN]${{parameters.dryrun}}'
            echo '##vso[task.setvariable variable=HYPERV_GENERATION]V1'
            echo '##vso[task.setvariable variable=AZURE_VM_SIZE]Standard_D4s_v3'
            echo '##vso[task.setvariable variable=CONTAINER_RUNTIME]docker'
            echo '##vso[task.setvariable variable=WINDOWS_SKU]2019'
          displayName: Setup Build Variables
        - template: ./templates/.builder-release-template-windows.yaml
          parameters:
            artifactName: 2019

  - stage: build_vhd_2019_containerd
    condition: eq('${{ parameters.build2019containerd }}', true)
    jobs:
    - job: build
      timeoutInMinutes: 180
      steps:
        - bash: |
            echo '##vso[task.setvariable variable=DRY_RUN]${{parameters.dryrun}}'
            echo '##vso[task.setvariable variable=HYPERV_GENERATION]V1'
            echo '##vso[task.setvariable variable=AZURE_VM_SIZE]Standard_D4s_v3'
            echo '##vso[task.setvariable variable=CONTAINER_RUNTIME]containerd'
            echo '##vso[task.setvariable variable=WINDOWS_SKU]2019-containerd'
          displayName: Setup Build Variables
        - template: ./templates/.builder-release-template-windows.yaml
          parameters:
            artifactName: 2019-containerd
