name: $(Date:yyyyMMdd)$(Rev:.r)_$(Build.SourceBranchName)_$(BuildID)
trigger: none

parameters:
- name: createSkuAndPublish2019Image
  displayName: Create SKU and Publish 2019 Image
  type: boolean
  default: true
- name: createSkuAndPublish2019ContainerDImage
  displayName: Create SKU and Publish 2019 containerD image
  type: boolean
  default: true

variables:
  CONTAINER_IMAGE:  'mcr.microsoft.com/oss/azcu/go-dev:v1.28.5'

phases:
  - phase: create_sku_and_publish_2019_image
    condition: eq('${{ parameters.createSkuAndPublish2019Image }}', true)
    queue:
      name: Hosted Ubuntu 1604
      timeoutInMinutes: 180
    steps:
      - bash: |
          echo '##vso[task.setvariable variable=PUBLISHER]microsoft-aks'
          echo '##vso[task.setvariable variable=OFFER]aks-windows'
          echo '##vso[task.setvariable variable=CONTAINER_RUNTIME]docker'
          echo '##vso[task.setvariable variable=SKU_PREFIX]aks-2019-datacenter-core-smalldisk'
        displayName: Setup Build Variables
      - template: ./templates/.builder-marketplace-SKU-And-Image-template.yaml
        parameters:
          artifactName: 2019
  - phase: create_sku_and_publish_2019_containerd_image
    condition: eq('${{ parameters.createSkuAndPublish2019ContainerDImage }}', true)
    queue:
      name: Hosted Ubuntu 1604
      timeoutInMinutes: 180
    steps:
      - bash: |
          echo '##vso[task.setvariable variable=PUBLISHER]microsoft-aks'
          echo '##vso[task.setvariable variable=OFFER]aks-windows'
          echo '##vso[task.setvariable variable=CONTAINER_RUNTIME]containerd'
          echo '##vso[task.setvariable variable=SKU_PREFIX]aks-2019-datacenter-core-smalldisk-crd'
        displayName: Setup Build Variables
      - template: ./templates/.builder-marketplace-SKU-And-Image-template.yaml
        parameters:
          artifactName: 2019-containerd