name: $(Date:yyyyMMdd)$(Rev:.r)_$(Build.SourceBranchName)_$(BuildID)
trigger: none

pool:
  name: $(POOL_NAME)

stages:
  - stage: build_uvm
    dependsOn: []
    jobs:
    - job: build
      timeoutInMinutes: 180
      steps:
        - bash: |
            echo "Initial placeholder"
          displayName: Placeholder task