name: $(Date:yyyyMMdd)$(Rev:.r)_$(Build.SourceBranchName)_$(BuildID)
trigger: none

pool:
  name: $(POOL_NAME)

parameters:
  - name: useOverrides
    displayName: Use component overrides
    type: boolean
    default: false
  - name: overrideBranch
    displayName: Branch in aks-rp to use for overrides
    type: string
    default: master
  - name: build1804containerd
    displayName: Build 1804 containerd
    type: boolean
    default: true
  - name: build1804gen2containerd
    displayName: Build 1804 Gen2 containerd
    type: boolean
    default: true
  - name: build1804gpucontainerd
    displayName: Build 1804 GPU+containerd
    type: boolean
    default: true
  - name: build1804gen2gpucontainerd
    displayName: Build 1804 Gen2 GPU+containerd
    type: boolean
    default: true
  - name: buildMarinerV2gen1
    displayName: Build MarinerV2 Gen1
    type: boolean
    default: true
  - name: buildAzureLinuxV2gen1
    displayName: Build AzureLinuxV2 Gen1
    type: boolean
    default: true
  - name: buildAzureLinuxV3gen1
    displayName: Build AzureLinuxV3 Gen1
    type: boolean
    default: true
  - name: buildMarinerV2gen2
    displayName: Build MarinerV2 Gen2
    type: boolean
    default: true
  - name: buildAzureLinuxV2gen2
    displayName: Build AzureLinuxV2 Gen2
    type: boolean
    default: true
  - name: buildAzureLinuxV3gen2
    displayName: Build AzureLinuxV3 Gen2
    type: boolean
    default: true
  - name: buildMarinerV2gen1fips
    displayName: Build MarinerV2 Gen1 FIPS
    type: boolean
    default: true
  - name: buildAzureLinuxV2gen1fips
    displayName: Build AzureLinuxV2 Gen1 FIPS
    type: boolean
    default: true
  - name: buildAzureLinuxV3gen1fips
    displayName: Build AzureLinuxV3 Gen1 FIPS
    type: boolean
    default: true
  - name: buildMarinerV2gen2fips
    displayName: Build MarinerV2 Gen2 FIPS
    type: boolean
    default: true
  - name: buildAzureLinuxV2gen2fips
    displayName: Build AzureLinuxV2 Gen2 FIPS
    type: boolean
    default: true
  - name: buildAzureLinuxV3gen2fips
    displayName: Build AzureLinuxV3 Gen2 FIPS
    type: boolean
    default: true
  - name: buildMarinerV2gen2kata
    displayName: Build MarinerV2 Gen2 Kata
    type: boolean
    default: true
  - name: buildAzureLinuxV2gen2kata
    displayName: Build AzureLinuxV2 Gen2 Kata
    type: boolean
    default: true
  - name: buildMarinerV2ARM64
    displayName: Build MarinerV2 Gen2 - ARM64
    type: boolean
    default: true
  - name: buildAzureLinuxV2ARM64
    displayName: Build AzureLinuxV2 Gen2 - ARM64
    type: boolean
    default: true
  - name: buildAzureLinuxV3ARM64
    displayName: Build AzureLinuxV3 Gen2 - ARM64
    type: boolean
    default: true
  - name: buildMarinerV2gen2TrustedLaunch
    displayName: Build MarinerV2 Gen2 - Trusted Launch
    type: boolean
    default: true
  - name: buildAzureLinuxV2gen2TrustedLaunch
    displayName: Build AzureLinuxV2 Gen2 - Trusted Launch
    type: boolean
    default: true
  - name: buildMarinerV2gen2kataTrustedLaunch
    displayName: Build MarinerV2 Gen2 Kata - Trusted Launch
    type: boolean
    default: false
  - name: buildAzureLinuxV2gen2kataTrustedLaunch
    displayName: Build AzureLinuxV2 Gen2 Kata - Trusted Launch
    type: boolean
    default: false
  - name: build1804fipscontainerd
    displayName: Build 1804 FIPS containerd
    type: boolean
    default: true
  - name: build1804fipsgen2containerd
    displayName: Build 1804 FIPS Gen2 containerd
    type: boolean
    default: true
  - name: build2004fipscontainerd
    displayName: Build 2004 FIPS containerd
    type: boolean
    default: true
  - name: build2004fipsgen2containerd
    displayName: Build 2004 FIPS Gen2 containerd
    type: boolean
    default: true
  - name: build2204fipscontainerd
    displayName: Build 2204 FIPS containerd
    type: boolean
    default: false
  - name: build2204fipsgen2containerd
    displayName: Build 2204 FIPS Gen2 containerd
    type: boolean
    default: false
  - name: build2204arm64gen2containerd
    displayName: Build 2204 ARM64 Gen2 containerd
    type: boolean
    default: true
  - name: build2404arm64gen2containerd
    displayName: Build 2404 ARM64 Gen2 containerd
    type: boolean
    default: true
  - name: build2204containerd
    displayName: Build 2204 Gen1 Containerd
    type: boolean
    default: true
  - name: build2204gen2containerd
    displayName: Build 2204 Gen2 Containerd
    type: boolean
    default: true
  - name: build2404containerd
    displayName: Build 2404 Gen1 Containerd
    type: boolean
    default: true
  - name: build2404gen2containerd
    displayName: Build 2404 Gen2 Containerd
    type: boolean
    default: true
  - name: build2004cvmgen2containerd
    displayName: Build 2004 CVM Gen2 Containerd
    type: boolean
    default: true
  - name: build2204tlgen2containerd
    displayName: Build 2204 TL Gen2 Containerd
    type: boolean
    default: true
  - name: build2204minimalgen1containerd
    displayName: Build 2204 Minimal Gen1 Containerd
    type: boolean
    default: false
  - name: build2204minimalgen2containerd
    displayName: Build 2204 Minimal Gen2 Containerd
    type: boolean
    default: false

variables:
  - group: aks-vuln-to-kusto
  - group: "AKS Node SIG UA Token (KV)"

stages:
  - template: ./templates/.build-and-test-all-linux-vhds-template.yaml
    parameters:
      useOverrides: ${{ parameters.useOverrides }}
      overrideBranch: ${{ parameters.overrideBranch }}
      dryrun: false
      vhddebug: false
      build1804containerd: {{ parameters.build1804containerd }}
      build1804gen2containerd: {{ parameters.build1804gen2containerd }}
      build1804gpucontainerd: {{ parameters.build1804gpucontainerd }}
      build1804gen2gpucontainerd: {{ parameters.build1804gen2gpucontainerd }}
      buildMarinerV2gen1: {{ parameters.buildMarinerV2gen1 }}
      buildAzureLinuxV2gen1: {{ parameters.buildAzureLinuxV2gen1 }}
      buildAzureLinuxV3gen1: {{ parameters.buildAzureLinuxV3gen1 }}
      buildMarinerV2gen2: {{ parameters.buildMarinerV2gen2 }}
      buildAzureLinuxV2gen2: {{ parameters.buildAzureLinuxV2gen2 }}
      buildAzureLinuxV3gen2: {{ parameters.buildAzureLinuxV3gen2 }}
      buildMarinerV2gen1fips: {{ parameters.buildMarinerV2gen1fips }}
      buildAzureLinuxV2gen1fips: {{ parameters.buildAzureLinuxV2gen1fips }}
      buildAzureLinuxV3gen1fips: {{ parameters.buildAzureLinuxV3gen1fips }}
      buildMarinerV2gen2fips: {{ parameters.buildMarinerV2gen2fips }}
      buildAzureLinuxV2gen2fips: {{ parameters.buildAzureLinuxV2gen2fips }}
      buildAzureLinuxV3gen2fips: {{ parameters.buildAzureLinuxV3gen2fips }}
      buildMarinerV2gen2kata: {{ parameters.buildMarinerV2gen2kata }}
      buildAzureLinuxV2gen2kata: {{ parameters.buildAzureLinuxV2gen2kata }}
      buildMarinerV2ARM64: {{ parameters.buildMarinerV2ARM64 }}
      buildAzureLinuxV2ARM64: {{ parameters.buildAzureLinuxV2ARM64 }}
      buildAzureLinuxV3ARM64: {{ parameters.buildAzureLinuxV3ARM64 }}
      buildMarinerV2gen2TrustedLaunch: {{ parameters.buildMarinerV2gen2TrustedLaunch }}
      buildAzureLinuxV2gen2TrustedLaunch: {{ parameters.buildAzureLinuxV2gen2TrustedLaunch }}
      buildMarinerV2gen2kataTrustedLaunch: {{ parameters.buildMarinerV2gen2kataTrustedLaunch }}
      buildAzureLinuxV2gen2kataTrustedLaunch: {{ parameters.buildAzureLinuxV2gen2kataTrustedLaunch }}
      build1804fipscontainerd: {{ parameters.build1804fipscontainerd }}
      build1804fipsgen2containerd: {{ parameters.build1804fipsgen2containerd }}
      build2004fipscontainerd: {{ parameters.build2004fipscontainerd }}
      build2004fipsgen2containerd: {{ parameters.build2004fipsgen2containerd }}
      build2204fipscontainerd: {{ parameters.build2204fipscontainerd }}
      build2204fipsgen2containerd: {{ parameters.build2204fipsgen2containerd }}
      build2204arm64gen2containerd: {{ parameters.build2204arm64gen2containerd }}
      build2404arm64gen2containerd: {{ parameters.build2404arm64gen2containerd }}
      build2204containerd: {{ parameters.build2204containerd }}
      build2204gen2containerd: {{ parameters.build2204gen2containerd }}
      build2404containerd: {{ parameters.build2404containerd }}
      build2404gen2containerd: {{ parameters.build2404gen2containerd }}
      build2004cvmgen2containerd: {{ parameters.build2004cvmgen2containerd }}
      build2204tlgen2containerd: {{ parameters.build2204tlgen2containerd }}
      build2204minimalgen1containerd: {{ parameters.build2204minimalgen1containerd }}
      build2204minimalgen2containerd: {{ parameters.build2204minimalgen2containerd }}
