name: $(Date:yyyyMMdd)$(Rev:.r)_$(OS_SKU)$(OS_VERSION)_$(HYPERV_GENERATION)_$(FEATURE_FLAGS)_$(Build.SourceBranchName)
trigger: none
pr:
  branches:
    include:
    - master
  paths:
    include:
    - vhdbuilder/packer
    exclude:


pool:
  name: $(POOL_NAME)

variables:
- name: CONTAINER_IMAGE
  value: 'mcr.microsoft.com/oss/azcu/go-dev:v1.38.1'

stages:
  - stage: build_vhd
    dependsOn: []
    jobs:
    - job: build
      timeoutInMinutes: 180
      steps:
        - bash: |
            echo '##vso[task.setvariable variable=DRY_RUN]True'
            echo '##vso[task.setvariable variable=OS_SKU]Ubuntu'
            echo '##vso[task.setvariable variable=OS_VERSION]22.04'
            echo '##vso[task.setvariable variable=IMG_PUBLISHER]Canonical'
            echo '##vso[task.setvariable variable=IMG_OFFER]0001-com-ubuntu-server-jammy'
            echo '##vso[task.setvariable variable=IMG_SKU]22_04-lts-gen2'
            echo '##vso[task.setvariable variable=IMG_VERSION]latest'
            echo '##vso[task.setvariable variable=HYPERV_GENERATION]V2'
            echo '##vso[task.setvariable variable=AZURE_VM_SIZE]Standard_D16ds_v5'
            echo '##vso[task.setvariable variable=FEATURE_FLAGS]None'
            echo '##vso[task.setvariable variable=CONTAINER_RUNTIME]containerd'
            echo '##vso[task.setvariable variable=ARCHITECTURE]X86_64'
            echo '##vso[task.setvariable variable=ENABLE_TRUSTED_LAUNCH]False'
            echo '##vso[task.setvariable variable=SGX_INSTALL]True'
          displayName: Setup Build Variables
        - template: ./templates/.builder-release-template.yaml
          parameters:
            artifactName: 2204-gen2-containerd