name: $(Date:yyyyMMdd)$(Rev:.r)_$(Build.SourceBranchName)_$(BuildID)
trigger: none

variables:
  - name: CONTAINER_IMAGE
    value: 'mcr.microsoft.com/oss/azcu/go-dev:v1.38.1'

pool:
  name: $(POOL_NAME)

parameters:
  - name: useOverrides
    displayName: Use component overrides
    type: boolean
    default: false
  - name: overrideBranch
    displayName: Branch in aks-rp to use for overrides
    type: string
    default: master
  - name: build1804containerd
    displayName: Build 1804 containerd
    type: boolean
    default: true
  - name: build1804gen2containerd
    displayName: Build 1804 Gen2 containerd
    type: boolean
    default: true
  - name: build1804gpucontainerd
    displayName: Build 1804 GPU+containerd
    type: boolean
    default: true
  - name: build1804gen2gpucontainerd
    displayName: Build 1804 Gen2 GPU+containerd
    type: boolean
    default: true
  - name: buildMarinerV2gen1
    displayName: Build MarinerV2 Gen1
    type: boolean
    default: true
  - name: buildAzureLinuxV2gen1
    displayName: Build AzureLinuxV2 Gen1
    type: boolean
    default: true
  - name: buildMarinerV2gen2
    displayName: Build MarinerV2 Gen2
    type: boolean
    default: true
  - name: buildAzureLinuxV2gen2
    displayName: Build AzureLinuxV2 Gen2
    type: boolean
    default: true
  - name: buildMarinerV2gen1fips
    displayName: Build MarinerV2 Gen1 FIPS
    type: boolean
    default: true
  - name: buildAzureLinuxV2gen1fips
    displayName: Build AzureLinuxV2 Gen1 FIPS
    type: boolean
    default: true
  - name: buildMarinerV2gen2fips
    displayName: Build MarinerV2 Gen2 FIPS
    type: boolean
    default: true
  - name: buildAzureLinuxV2gen2fips
    displayName: Build AzureLinuxV2 Gen2 FIPS
    type: boolean
    default: true
  - name: buildMarinerV2gen2kata
    displayName: Build MarinerV2 Gen2 Kata
    type: boolean
    default: true
  - name: buildAzureLinuxV2gen2kata
    displayName: Build AzureLinuxV2 Gen2 Kata
    type: boolean
    default: true
  - name: buildMarinerV2ARM64
    displayName: Build MarinerV2 Gen2 - ARM64
    type: boolean
    default: true
  - name: buildAzureLinuxV2ARM64
    displayName: Build AzureLinuxV2 Gen2 - ARM64
    type: boolean
    default: true
  - name: buildMarinerV2gen2TrustedLaunch
    displayName: Build MarinerV2 Gen2 - Trusted Launch
    type: boolean
    default: true
  - name: buildAzureLinuxV2gen2TrustedLaunch
    displayName: Build AzureLinuxV2 Gen2 - Trusted Launch
    type: boolean
    default: true
  - name: buildMarinerV2gen2kataTrustedLaunch
    displayName: Build MarinerV2 Gen2 Kata - Trusted Launch
    type: boolean
    default: false
  - name: buildAzureLinuxV2gen2kataTrustedLaunch
    displayName: Build AzureLinuxV2 Gen2 Kata - Trusted Launch
    type: boolean
    default: false
  - name: build1804fipscontainerd
    displayName: Build 1804 FIPS containerd
    type: boolean
    default: true
  - name: build1804fipsgen2containerd
    displayName: Build 1804 FIPS Gen2 containerd
    type: boolean
    default: true
  - name: build2004fipscontainerd
    displayName: Build 2004 FIPS containerd
    type: boolean
    default: true
  - name: build2004fipsgen2containerd
    displayName: Build 2004 FIPS Gen2 containerd
    type: boolean
    default: true
  - name: build2204fipscontainerd
    displayName: Build 2204 FIPS containerd
    type: boolean
    default: false
  - name: build2204fipsgen2containerd
    displayName: Build 2204 FIPS Gen2 containerd
    type: boolean
    default: false
  - name: build2204arm64gen2containerd
    displayName: Build 2204 ARM64 Gen2 containerd
    type: boolean
    default: true
  - name: build2404arm64gen2containerd
    displayName: Build 2404 ARM64 Gen2 containerd
    type: boolean
    default: false
  - name: build2204containerd
    displayName: Build 2204 Gen1 Containerd
    type: boolean
    default: true
  - name: build2204gen2containerd
    displayName: Build 2204 Gen2 Containerd
    type: boolean
    default: true
  - name: build2404containerd
    displayName: Build 2404 Gen1 Containerd
    type: boolean
    default: false
  - name: build2404gen2containerd
    displayName: Build 2404 Gen2 Containerd
    type: boolean
    default: false
  - name: build2004cvmgen2containerd
    displayName: Build 2004 CVM Gen2 Containerd
    type: boolean
    default: true
  - name: build2204tlgen2containerd
    displayName: Build 2204 TL Gen2 Containerd
    type: boolean
    default: true
  - name: build2204minimalgen1containerd
    displayName: Build 2204 Minimal Gen1 Containerd
    type: boolean
    default: false
  - name: build2204minimalgen2containerd
    displayName: Build 2204 Minimal Gen2 Containerd
    type: boolean
    default: false
  - name: dryrun
    displayName: Dry run
    type: boolean
    default: False

stages:
  - stage: build1804containerd
    dependsOn: []
    - template: ./templates/.builder-release-template.yaml
      parameters:
        DRY_RUN: ${{parameters.dryrun}}
        OS_SKU: Ubuntu
        OS_VERSION: 18.04
        IMG_PUBLISHER: Canonical
        IMG_OFFER: UbuntuServer
        IMG_SKU: 18.04-LTS
        IMG_VERSION: latest
        HYPERV_GENERATION: V1
        AZURE_VM_SIZE: Standard_D16ds_v5
        FEATURE_FLAGS: None
        CONTAINER_RUNTIME: containerd
        ARCHITECTURE: X86_64
        ENABLE_TRUSTED_LAUNCH: false
        SGX_INSTALL: false