name: $(Date:yyyyMMdd)$(Rev:.r)_$(Build.SourceBranchName)_$(BuildID)
trigger: none

parameters:
- name: scanAzureLinuxV2gen1
  displayName: Scan AzureLinuxV2 Gen1
  type: boolean
  default: true

variables:
- name: CONTAINER_IMAGE
  value: 'mcr.microsoft.com/oss/azcu/go-dev:v1.38.1'
  
pool:
  name: $(POOL_NAME)

stages:
  - stage: scan_vhd_azurelinuxv2_gen1
    dependsOn: []
    condition: eq('${{ parameters.scanAzureLinuxV2gen1 }}', true)
    jobs:
    - job: scan
      timeoutInMinutes: 60
      steps:
        - bash: |
            echo '##vso[task.setvariable variable=DRY_RUN]${{parameters.dryrun}}'
            echo '##vso[task.setvariable variable=OS_SKU]AzureLinux'
            echo '##vso[task.setvariable variable=OS_VERSION]V2'
            echo '##vso[task.setvariable variable=ARCHITECTURE]X86_64'
            echo '##vso[task.setvariable variable=IMAGE_URL_NAME]AzureLinuxV2'
            echo '##vso[task.setvariable variable=ENABLE_TRUSTED_LAUNCH]False'
          displayName: 'Set variables'
        - template: ./templates/.scanning-template.yaml
          parameters:
            artifactName: azurelinuxv2-gen1
        