name: $(Date:yyyyMMdd)$(Rev:.r)_$(Build.SourceBranchName)_$(BuildID)
trigger: none

parameters:
- name: scanAzureLinuxV2gen1
  displayName: Scan AzureLinuxV2 Gen1
  type: boolean
  default: true

variables:
- name: CONTAINER_IMAGE
  value: 'mcr.microsoft.com/oss/azcu/go-dev:v1.38.1'
  
pool:
  name: $(POOL_NAME)

stages:
  - stage: scan_vhd_azurelinuxv2_gen1
    dependsOn: []
    condition: eq('${{ parameters.scanAzureLinuxV2gen1 }}', true)
    jobs:
    - job: scan
      steps:
        - task: UseGoTool@0
          inputs:
            version: '1.21'
        - script: |
            go version
            go run ../vhdbuilder/scanning/main.go
          displayName: 'Run Go Scanning Script'

