name: $(Date:yyyyMMdd)$(Rev:.r)_$(Build.SourceBranchName)_$(BuildID)
trigger: none

pool:
  name: $(POOL_NAME)

parameters:
  - name: useOverrides
    displayName: Use component overrides
    type: boolean
    default: false
  - name: overrideBranch
    displayName: Branch in aks-rp to use for overrides
    type: string
    default: master
  - name: build2404arm64gb200gen2containerd
    displayName: Build 2404 ARM64 GB200 Gen2 Containerd
    type: boolean
    default: true

variables:
  - group: aks-vuln-to-kusto
  - group: "AKS Node SIG UA Token (KV)"
  - group: build_performance
  - group: aks-vuln-to-kusto-tme
stages:
  - stage: build
    jobs:
      - job: build2404arm64gb200gen2containerd
        condition: eq('${{ parameters.build2404arm64gb200gen2containerd }}', true)
        dependsOn: [ ]
        timeoutInMinutes: 180
        steps:
          - bash: |
              echo '##vso[task.setvariable variable=OS_SKU]Ubuntu'
              echo '##vso[task.setvariable variable=OS_VERSION]24.04'
              echo '##vso[task.setvariable variable=IMG_PUBLISHER]Canonical'
              echo '##vso[task.setvariable variable=IMG_OFFER]ubuntu-24_04-lts'
              echo '##vso[task.setvariable variable=IMG_SKU]server-arm64'
              echo '##vso[task.setvariable variable=IMG_VERSION]latest'
              echo '##vso[task.setvariable variable=HYPERV_GENERATION]V2'
              echo '##vso[task.setvariable variable=AZURE_VM_SIZE]Standard_D16pds_v5'
              echo '##vso[task.setvariable variable=FEATURE_FLAGS]GB200'
              echo '##vso[task.setvariable variable=CONTAINER_RUNTIME]containerd'
              echo '##vso[task.setvariable variable=ARCHITECTURE]ARM64'
              echo '##vso[task.setvariable variable=ENABLE_FIPS]False'
              echo '##vso[task.setvariable variable=ENABLE_TRUSTED_LAUNCH]False'
            displayName: Setup Build Variables
          - template: ./templates/.builder-release-template.yaml
            parameters:
              useOverrides: ${{ parameters.useOverrides }}
              overrideBranch: ${{ parameters.overrideBranch }}
              artifactName: 2404-arm64-gb200-gen2-containerd
  - stage: e2e
    condition: and(succeeded(), ne(variables.SKIP_E2E_TESTS, 'true'))
    variables:
      VHD_BUILD_ID: $(Build.BuildId)
      TAGS_TO_SKIP: "os=windows"
    jobs:
      - template: ./templates/e2e-template.yaml
        parameters:
          name: All Linux
          IgnoreScenariosWithMissingVhd: true

