name: $(Date:yyyyMMdd)$(Rev:.r)
variables:
  - name: TAGS_TO_RUN
    value: "os=windows"
  - name: SKIP_E2E_TESTS
    value: false
  # this is intentionally blank to force the pipeline to use the VHD built from master
  - name: VHD_BUILD_ID
    value: ""
  - name: LOCATION
    value: $(PACKER_BUILD_LOCATION)
  - name: POOL_NAME
    value: $(AZURE_POOL_NAME)
  - name: SUBSCRIPTION_ID
    value: $(AZURE_BUILD_SUBSCRIPTION_ID)
    # if SIG_FOR_PRODUCTION is true, then the VHDs are deleted from the gallery before the e2e tests are run.
  - name: SIG_FOR_PRODUCTION
    value: False
    # These next vars are used for the e2e tests
  - name: AZURE_RESOURCE_GROUP_NAME
    value:  $(AZURE_BUILD_RESOURCE_GROUP_NAME)
  - name: "AKS-Windows"
    value: $(AZURE_BUILD_RESOURCE_GROUP_NAME)
  - name: GALLERY_SUBSCRIPTION_ID
    value: "4be8920b-2978-43d7-ab14-04d8549c1d05"


trigger:
  branches:
    include:
      - master
      - dev
pr:
  branches:
    include:
      - master
      - official/*
      - dev
  paths:
    include:
      - .pipelines/e2e-windows.yaml
      - .pipelines/templates/e2e-template.yaml
      - .pipelines/scripts/e2e_run.sh
      - .pipelines/scripts/e2e_delete_vmss.sh
      - e2e
      - parts/windows
      - pkg/agent
      - parts/common/components.json
      - staging/cse/windows/
      - go.mod
      - go.sum
    exclude:
      - pkg/agent/datamodel/sig_config*.go # SIG config changes
      - pkg/agent/datamodel/*.json # SIG version changes
      - pkg/agent/testdata/AKSWindows* # Windows test data
      - parts/common/components.json # centralized components management file
      - staging/cse/windows/README
      - /**/*.md
      - .github/**
      - e2e/scenario_test.go

jobs:
  - template: ./templates/e2e-template.yaml
    parameters:
      name: Windows Tests
      IgnoreScenariosWithMissingVhd: false
