name: $(Date:yyyyMMdd)$(Rev:.r)_e2e

pr:
  branches:
    include:
    - main
    - 'official/*'
  paths:
    include:
    - '.pipelines/*'
    - 'e2e/*'
    - 'parts/windows/*'

variables:
- group: ab-e2e-windows

pool:
  name: 1ES-AKS-Elastic-DevInfra-Auto-TearDown-Pool

parameters:
- name: test2019containerd
  displayName: Test 2019 containerd
  type: boolean
  default: True
- name: test2022containerd
  displayName: Test 2022 containerd
  type: boolean
  default: True
- name: test2022containerdgen2
  displayName: Test 2022 containerd Gen 2
  type: boolean
  default: True

stages:
- stage: test_2019_containerd
  dependsOn: []
  condition: eq('${{ parameters.test2019containerd }}', True)
  jobs:
  - template: ./templates/e2e-windows-template.yaml
    parameters:
      windowsImage: 2019-containerd

- stage: test_2022_containerd
  dependsOn: []
  condition: eq('${{ parameters.test2022containerd }}', True)
  jobs:
  - template: ./templates/e2e-windows-template.yaml
    parameters:
      windowsImage: 2022-containerd

- stage: test_2022_containerd_gen2
  dependsOn: []
  condition: eq('${{ parameters.test2022containerdgen2 }}', True)
  jobs:
  - template: ./templates/e2e-windows-template.yaml
    parameters:
      windowsImage: 2022-containerd-gen2