name: $(Date:yyyyMMdd)$(Rev:.r)
variables:
  TAGS_TO_RUN: "gpu=true"
  TAGS_TO_SKIP: "os=windows"
  SKIP_E2E_TESTS: false
  SKIP_TESTS_WITH_SKU_CAPACITY_ISSUE: true
  E2E_GO_TEST_TIMEOUT: "75m"
schedules:
  - cron: "0 8 * * *"
    displayName: Daily midnight PST
    branches:
      include:
        - main
    always: true
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - e2e/**
      - '**/*.go'
pr:
  branches:
    include:
      - official/*
      - windows/*
      - main
  paths:
    include:
      - e2e/**
      - '**/*.go'
jobs:
  - template: ./templates/e2e-template.yaml
    parameters:
      name: Linux GPU Tests
      IgnoreScenariosWithMissingVhd: false
