name: $(Date:yyyyMMdd)$(Rev:.r)
variables:
  TAGS_TO_RUN: "os=windows"
  SKIP_E2E_TESTS: false
trigger:
  branches:
    include:
      - master
      - dev
pr:
  branches:
    include:
      - master
      - official/*
      - dev
  paths:
    include:
      - .pipelines/e2e-windows.yaml
      - .pipelines/templates/e2e-template.yaml
      - e2e
      - parts/windows
      - pkg/agent
      - staging/cse/windows/
    exclude:
      - pkg/agent/datamodel/sig_config*.go # SIG config changes
      - pkg/agent/datamodel/*.json # SIG version changes
      - pkg/agent/testdata/AKSWindows* # Windows test data
      - parts/common/components.json # centralized components management file
      - staging/cse/windows/README
      - /**/*.md
      - .github/**
      - e2e/scenario_test.go

jobs:
  - template: ./templates/e2e-template.yaml
    parameters:
      name: Windows Tests
