name: $(Date:yyyyMMdd)$(Rev:.r)_e2e
trigger: none

pr:
  branches:
    include:
    - main
    - 'official/*'
  paths:
    include:
    - '.pipelines/*'
    - 'e2e/windows/*'
    - 'parts/windows/*'
    - 'staging/cse/windows/*'

variables:
- group: ab-e2e-windows

pool:
  # uncomment this if the auto teardown pool is down.
  # vmImage: ubuntu-22.04
  name: $(1ES_DevInfra_Auto_TearDown_Pool_Name)

parameters:
- name: test2019containerd
  displayName: Test 2019 containerd
  type: boolean
  default: True
- name: test2022containerd
  displayName: Test 2022 containerd
  type: boolean
  default: True
- name: test2022containerdgen2
  displayName: Test 2022 containerd Gen 2
  type: boolean
  default: True

stages:
- stage: test_2019_containerd
  dependsOn: []
  condition: eq('${{ parameters.test2019containerd }}', True)
  jobs:
  - template: ./templates/e2e-windows-template.yaml
    parameters:
      windowsImage: 2019-containerd
      windowsOSSKU: Windows2019
      windowsVMSize: Standard_D2s_v3
      windowsDistro: aks-windows-2019-containerd
      windowsNodeImageVersion: AKSWindows-2019-containerd-test-2023.02.07
      storageAccount: akswinstore2019

- stage: test_2022_containerd
  dependsOn: []
  condition: eq('${{ parameters.test2022containerd }}', True)
  jobs:
  - template: ./templates/e2e-windows-template.yaml
    parameters:
      windowsImage: 2022-containerd
      windowsOSSKU: Windows2022
      windowsVMSize: Standard_D2_v2
      windowsDistro: aks-windows-2022-containerd
      windowsNodeImageVersion: AKSWindows-2022-containerd-test-2023.02.07
      storageAccount: akswinstore2022

- stage: test_2022_containerd_gen2
  dependsOn: []
  condition: eq('${{ parameters.test2022containerdgen2 }}', True)
  jobs:
  - template: ./templates/e2e-windows-template.yaml
    parameters:
      windowsImage: 2022-containerd-gen2
      windowsOSSKU: Windows2022
      windowsVMSize: Standard_DS2_v2
      windowsDistro: aks-windows-2022-containerd-gen2
      windowsNodeImageVersion: AKSWindows-2022-containerd-gen2-test-2023.02.07
      storageAccount: akswinstore2022gen2