name: $(Date:yyyyMMdd)$(Rev:.r)
parameters:
  - name: vmSeriesCoverage
    type: boolean
    default: false
variables:
  SKIP_E2E_TESTS: false
  ${{ if eq(parameters.vmSeriesCoverage, true) }}:
    VM_SERIES_COVERAGE: true
    E2E_PARALLEL: 1
    E2E_GO_TEST_TIMEOUT: 210m
    E2E_FAILED_TESTS_RETRY_COUNT: 0
  ${{ else }}:
    E2E_FAILED_TESTS_RETRY_COUNT: 2

jobs:
  - template: ./templates/e2e-template.yaml
    parameters:
      name: AgentBaker Tests
      IgnoreScenariosWithMissingVhd: false
      ${{ if eq(parameters.vmSeriesCoverage, true) }}:
        jobTimeoutInMinutes: 240
      ${{ else }}:
        jobTimeoutInMinutes: 120
      failedTestsRetryCount: ${{ variables.E2E_FAILED_TESTS_RETRY_COUNT }}
      variableGroup: ab-e2e-tme
      subscriptionId: $(SUBSCRIPTION_ID_OVERRIDE)
