name: $(Date:yyyyMMdd)$(Rev:.r)
parameters:
  - name: cosiArtifactsBuildID
    displayName: Registered VHD build ID supplying the COSI target
    type: string
    default: ""
  - name: cosiNebraskaServer
    displayName: COSI Nebraska Omaha endpoint
    type: string
    default: "https://nebraska-poc-ep-cda8e2czfnhahxfk.b01.azurefd.net/v1/update"
  - name: cosiNebraskaAppID
    displayName: COSI Nebraska application ID
    type: string
    default: "59bbad61-257d-47f4-9730-6848d88e1a6e"
variables:
  - name: TAGS_TO_SKIP
    value: "os=windows,gpu=true"
  - name: SKIP_E2E_TESTS
    value: false
  - name: E2E_FAILED_TESTS_RETRY_COUNT
    value: 0
schedules:
  - cron: "0 8 * * *"
    displayName: Daily midnight PST
    branches:
      include:
        - main
    always: true
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - e2e/**
      - .pipelines/e2e.yaml
      - .pipelines/templates/e2e-template.yaml
pr:
  branches:
    include:
      - official/*
      - windows/*
      - main
  paths:
    include:
      - e2e/**
      - .pipelines/e2e.yaml
      - .pipelines/templates/e2e-template.yaml
jobs:
  - template: ./templates/e2e-template.yaml
    parameters:
      name: Linux Tests
      IgnoreScenariosWithMissingVhd: false
      failedTestsRetryCount: ${{ variables.E2E_FAILED_TESTS_RETRY_COUNT }}
      ${{ if ne(parameters.cosiArtifactsBuildID, '') }}:
        jobTimeoutInMinutes: 120
        cosiArtifactsBuildID: ${{ parameters.cosiArtifactsBuildID }}
        cosiNebraskaServer: ${{ parameters.cosiNebraskaServer }}
        cosiNebraskaAppID: ${{ parameters.cosiNebraskaAppID }}
        cosiArtifactNames:
          - "cosi-publishing-info-acl-tl-gen2"
