name: $(Date:yyyyMMdd)$(Rev:.r)
trigger: none
pr:
  branches:
    include:
      - master
      - official/*
  paths:
    include:
      - .pipelines/e2e.yaml
      - e2e
      - parts/linux
      - pkg/agent
    exclude:
      - e2e/windows
      - pkg/agent/datamodel/sig_config*.go # SIG config changes
      - pkg/agent/datamodel/*.json # SIG version changes
      - pkg/agent/testdata/AKSWindows* # Windows test data

variables:
  - group: "AKS Dev Assistant (KV)"
  - group: ab-e2e

pool:
  name: nodesigtest-pool

jobs:
  - template: ./templates/e2e-template.yaml
    parameters:
      defaultTimeout: 90
      poolName: nodesigtest-pool
      azureSubscriptionId: $(AZURE_SUBSCRIPTION_ID)
      vhdBuildId: $(VHD_BUILD_ID)
      adoPat: $(PAT-aksdevassistant)
