name: $(Date:yyyyMMdd)$(Rev:.r)
trigger: 
  branches:
    include: 
    - master
pr:
  branches:
    include:
      - master
      - official/*
  paths:
    include:
      - .pipelines/e2e.yaml
      - .pipelines/templates/e2e-template.yaml
      - e2e
      - parts/linux
      - pkg/agent
    exclude:
      - e2e/windows
      - pkg/agent/datamodel/sig_config*.go # SIG config changes
      - pkg/agent/datamodel/*.json # SIG version changes
      - pkg/agent/testdata/AKSWindows* # Windows test data
      - parts/linux/cloud-init/artifacts/components.json # centralized components management file
jobs:
  - template: ./templates/e2e-template.yaml
