name: $(Date:yyyyMMdd)$(Rev:.r)_e2e

pr:
  branches:
    include:
    - main
    - 'official/*'

variables:
- group: ab-e2e

pool:
  name: nodesigtest-pool

jobs:
- job: Run_AgentBaker_E2E
  steps:
  - bash: |
      az login --identity
      az account set -s $(AZURE_SUBSCRIPTION_ID)
    displayName: az login
  - bash: bash .pipelines/scripts/setup_go.sh
    displayName: setup go
  - bash: |
      export PATH="/usr/local/go/bin:$PATH"
      go version
      cd e2e
      go test -timeout 10m -v -run Test_All ./...
    displayName: Run AgentBaker E2E
  - publish: $(System.DefaultWorkingDirectory)/e2e/vm-logs
    artifact: vm-logs
    condition: always()
  - publish: $(System.DefaultWorkingDirectory)/e2e/cluster-parameters
    artifact: cluster-parameters
    condition: always()
 
 