name: $(Date:yyyyMMdd)$(Rev:.r)
parameters:
  - name: cosiArtifactsBuildID
    displayName: Registered VHD build ID supplying the COSI target
    type: string
    default: ""
variables:
  - name: TAGS_TO_SKIP
    value: "os=windows,gpu=true"
  - name: SKIP_E2E_TESTS
    value: false
  - name: E2E_FAILED_TESTS_RETRY_COUNT
    value: 0
  - ${{ if ne(parameters.cosiArtifactsBuildID, '') }}:
      - group: "AKS Node SIG - PMC COSI TME"
schedules:
  - cron: "0 8 * * *"
    displayName: Daily midnight PST
    branches:
      include:
        - main
    always: true
trigger:
  branches:
    include:
      - main
  paths:
    include:
      - e2e/**
      - .pipelines/e2e.yaml
      - .pipelines/templates/e2e-template.yaml
pr:
  branches:
    include:
      - official/*
      - windows/*
      - main
  paths:
    include:
      - e2e/**
      - .pipelines/e2e.yaml
      - .pipelines/templates/e2e-template.yaml
jobs:
  - template: ./templates/e2e-template.yaml
    parameters:
      name: Linux Tests
      IgnoreScenariosWithMissingVhd: false
      failedTestsRetryCount: ${{ variables.E2E_FAILED_TESTS_RETRY_COUNT }}
      ${{ if ne(parameters.cosiArtifactsBuildID, '') }}:
        jobTimeoutInMinutes: 120
        cosiArtifactsBuildID: ${{ parameters.cosiArtifactsBuildID }}
        cosiNebraskaServer: "$(NEBRASKA_PUBLISHER_ENDPOINT)v1/update"
        cosiNebraskaAppID: $(NEBRASKA_APP_ID)
        cosiArtifactNames:
          - "cosi-publishing-info-acl-tl-gen2"
