name: $(Date:yyyyMMdd)$(Rev:.r)
trigger: 
  branches:
    include: 
    - master
pr:
  branches:
    include:
      - master
      - official/*
  paths:
    include:
      - .pipelines/e2e.yaml
      - .pipelines/templates/e2e-template.yaml
      - e2e
    exclude:
      - e2e/windows
jobs:
  - template: ./templates/e2e-template.yaml
