name: $(Date:yyyyMMdd)$(Rev:.r)
trigger: none
pr:
  branches:
    include:
    - master
    - official/*
  paths:
    include:
    - pkg/proto
    - pkg/parser

jobs:
check-file:
  runs-on: ubuntu-latest
  steps:
  - name: Checkout current branch
    uses: actions/checkout@v2

  - name: build go binary
    run: make update-contract

  - name: Save file from current branch
    run: cp pkg/parser/bin/parser parser

  - name: Checkout master branch
    uses: actions/checkout@v2
    with:
      ref: 'master'

  - name: Compare file with master branch
    run: |
      if [ ! -f pkg/parser/bin/parser ]; then
        echo "Error: parser binary does not exist on master branch, please run `make update-contract` and push the changes"
        exit 1
      fi
      if ! cmp -s pkg/parser/bin/parser parser; then
        echo "Error: File is different on current branch"
        exit 1
      fi
