confdir /etc/chrony.conf.d
sourcedir /run/chrony-dhcp
keyfile /etc/chrony.keys
driftfile /var/lib/chrony/drift
ntsdumpdir /var/lib/chrony
logdir /var/log/chrony
maxupdateskew 100.0
rtcsync
makestep 1.0 -1
leapsectz right/UTC
refclock PHC /dev/ptp_hyperv poll 3 dpoll -2 offset 0