#!/bin/bash
cat <<'MPSTAT_EOF'
Linux 5.4.0-1043-azure (test-node)   01/01/70        _x86_64_        (4 CPU)

Average:     CPU    %usr   %nice    %sys %iowait    %irq   %soft  %steal  %guest  %gnice   %idle
Average:     all   20.00    0.00   10.00   35.00    0.00    2.00    3.00    0.00    0.00   30.00
MPSTAT_EOF
