#!/bin/bash
cat <<END
Linux 5.4.0-1064-azure (test-node) 	01/01/2024 	_x86_64_	(2 CPU)

Average:     CPU    %usr   %nice    %sys %iowait    %irq   %soft  %steal  %guest  %gnice   %idle
Average:     all   10.00    0.00   10.00    0.00    0.00    0.00    0.00    0.00    0.00   80.00
END
