#shellcheck shell=bash
#shellcheck disable=SC2148

Describe 'aks-hosts-setup.sh'
    SCRIPT_PATH="parts/linux/cloud-init/artifacts/aks-hosts-setup.sh"

    Describe 'DNS resolution and hosts file creation'
        setup() {
            TEST_DIR=$(mktemp -d)
            export HOSTS_FILE="${TEST_DIR}/hosts.testing"

            # Create a modified version of the script that uses our test HOSTS_FILE
            # and sources our mocked nslookup function
            TEST_SCRIPT="${TEST_DIR}/aks-hosts-setup-test.sh"

            # Create mock nslookup function file
            cat > "${TEST_DIR}/mock_nslookup.sh" << 'MOCK_EOF'
nslookup() {
    local record_type=""
    local domain=""
    for arg in "$@"; do
        if [[ "$arg" == "-type=A" ]]; then
            record_type="A"
        elif [[ "$arg" == "-type=AAAA" ]]; then
            record_type="AAAA"
        elif [[ "$arg" != -* ]]; then
            domain="$arg"
        fi
    done

    # Simulate nslookup output format
    echo "Server:		127.0.0.53"
    echo "Address:	127.0.0.53#53"
    echo ""
    echo "Non-authoritative answer:"
    echo "Name:	${domain}"

    case "$record_type" in
        A)
            echo "Address: 1.2.3.4"
            echo "Address: 5.6.7.8"
            ;;
        AAAA)
            echo "Address: 2001:db8::1"
            echo "Address: 2001:db8::2"
            ;;
    esac
}
export -f nslookup
MOCK_EOF

            # Create test script that overrides HOSTS_FILE before running the main logic
            cat > "${TEST_SCRIPT}" << EOF
#!/bin/bash
source "${TEST_DIR}/mock_nslookup.sh"
HOSTS_FILE="${HOSTS_FILE}"
EOF
            # Append the original script content, skipping the shebang and HOSTS_FILE declaration
            tail -n +8 "${SCRIPT_PATH}" >> "${TEST_SCRIPT}"
            chmod +x "${TEST_SCRIPT}"
        }

        cleanup() {
            rm -rf "$TEST_DIR"
        }

        BeforeEach 'setup'
        AfterEach 'cleanup'

        It 'creates hosts file with resolved addresses for all critical FQDNs'
            When run script "${TEST_SCRIPT}"
            The status should be success
            The file "$HOSTS_FILE" should be exist
            The output should include "Starting AKS critical FQDN hosts resolution"
            The output should include "AKS critical FQDN hosts resolution completed"
        End

        It 'includes all critical AKS FQDNs in hosts file'
            When run script "${TEST_SCRIPT}"
            The status should be success
            The output should include "Resolving addresses"
            The contents of file "$HOSTS_FILE" should include "mcr.microsoft.com"
            The contents of file "$HOSTS_FILE" should include "packages.microsoft.com"
            The contents of file "$HOSTS_FILE" should include "management.azure.com"
            The contents of file "$HOSTS_FILE" should include "login.microsoftonline.com"
            The contents of file "$HOSTS_FILE" should include "acs-mirror.azureedge.net"
            The contents of file "$HOSTS_FILE" should include "packages.aks.azure.com"
        End

        It 'includes IPv4 addresses in hosts file'
            When run script "${TEST_SCRIPT}"
            The status should be success
            The output should include "Resolved"
            The contents of file "$HOSTS_FILE" should include "1.2.3.4"
            The contents of file "$HOSTS_FILE" should include "5.6.7.8"
        End

        It 'includes IPv6 addresses in hosts file'
            When run script "${TEST_SCRIPT}"
            The status should be success
            The output should include "Resolved"
            The contents of file "$HOSTS_FILE" should include "2001:db8::1"
            The contents of file "$HOSTS_FILE" should include "2001:db8::2"
        End

        It 'formats hosts file entries correctly'
            When run script "${TEST_SCRIPT}"
            The status should be success
            The output should include "Writing addresses"
            The contents of file "$HOSTS_FILE" should include "1.2.3.4 mcr.microsoft.com"
            The contents of file "$HOSTS_FILE" should include "2001:db8::1 mcr.microsoft.com"
        End

        It 'includes header comments in hosts file'
            When run script "${TEST_SCRIPT}"
            The status should be success
            The output should include "Starting AKS critical FQDN hosts resolution"
            The contents of file "$HOSTS_FILE" should include "# AKS critical FQDN addresses resolved at"
            The contents of file "$HOSTS_FILE" should include "# This file is automatically generated by aks-hosts-setup.service"
        End
    End

    Describe 'DNS resolution failure handling'
        setup() {
            TEST_DIR=$(mktemp -d)
            export HOSTS_FILE="${TEST_DIR}/hosts.testing"
            TEST_SCRIPT="${TEST_DIR}/aks-hosts-setup-test.sh"

            # Create mock nslookup function that returns nothing (simulating DNS failure)
            cat > "${TEST_DIR}/mock_nslookup.sh" << 'MOCK_EOF'
nslookup() {
    # Return empty response - simulating DNS failure
    echo "Server:		127.0.0.53"
    echo "Address:	127.0.0.53#53"
    echo ""
    echo "** server can't find domain: NXDOMAIN"
    return 0
}
export -f nslookup
MOCK_EOF

            cat > "${TEST_SCRIPT}" << EOF
#!/bin/bash
source "${TEST_DIR}/mock_nslookup.sh"
HOSTS_FILE="${HOSTS_FILE}"
EOF
            tail -n +8 "${SCRIPT_PATH}" >> "${TEST_SCRIPT}"
            chmod +x "${TEST_SCRIPT}"
        }

        cleanup() {
            rm -rf "$TEST_DIR"
        }

        BeforeEach 'setup'
        AfterEach 'cleanup'

        It 'exits gracefully when no DNS records are resolved'
            When run script "${TEST_SCRIPT}"
            The status should be success
            The output should include "WARNING: No IP addresses resolved for any domain"
            The output should include "This is likely a temporary DNS issue"
        End

        It 'does not create hosts file when no DNS records are resolved'
            When run script "${TEST_SCRIPT}"
            The status should be success
            The output should include "WARNING"
            The file "$HOSTS_FILE" should not be exist
        End
    End
End
