#!/bin/bash

Describe 'block_wireserver.sh'
    Include "./parts/linux/cloud-init/artifacts/block_wireserver.sh"

    # Records every iptables invocation so we can assert on which ones ran.
    # Exits 0 for -C when RULE_EXISTS is set, mimicking iptables' "rule found" contract.
    iptables() {
        echo "iptables $*"
        case "$1" in
            -C) [ "${RULE_EXISTS:-false}" = "true" ] ;;
            *) return 0 ;;
        esac
    }

    Describe 'blockWireserverPort'
        It 'inserts the rule when it is not already present'
            RULE_EXISTS=false
            When call blockWireserverPort 80
            The status should be success
            The stdout should include "iptables -C FORWARD -d 168.63.129.16 -p tcp --dport 80 -j DROP"
            The stdout should include "iptables -I FORWARD -d 168.63.129.16 -p tcp --dport 80 -j DROP"
        End

        It 'does not insert a duplicate when the rule already exists'
            RULE_EXISTS=true
            When call blockWireserverPort 80
            The status should be success
            The stdout should include "iptables -C FORWARD -d 168.63.129.16 -p tcp --dport 80 -j DROP"
            The stdout should not include "iptables -I"
        End

        It 'checks the same rule spec that it inserts'
            RULE_EXISTS=false
            When call blockWireserverPort 32526
            The status should be success
            The lines of stdout should eq 2
            # A -C spec that drifts from the -I spec never matches, so the rule would be
            # re-inserted on every kubelet start even though it is already there.
            check_spec=$(echo "$stdout" | grep -- '-C' | sed 's/^iptables -C //')
            insert_spec=$(echo "$stdout" | grep -- '-I' | sed 's/^iptables -I //')
            The variable check_spec should equal "$insert_spec"
        End

        It 'propagates failure when the insert fails'
            RULE_EXISTS=false
            iptables() {
                case "$1" in
                    -C) return 1 ;;
                    *) return 4 ;;
                esac
            }
            When call blockWireserverPort 80
            The status should eq 4
        End
    End

    Describe 'parity with the copy generated by cse_config.sh'
        # /opt/azure/containers/kubelet.sh is written twice: baked into the VHD from this file
        # by packer_source.sh, and regenerated at provisioning time by ensureKubelet() in
        # cse_config.sh. If only one gains the idempotency guard, nodes still leak rules.
        It 'generates a guarded rule insert in cse_config.sh'
            When call grep -c 'iptables -C FORWARD -d 168.63.129.16' ./parts/linux/cloud-init/artifacts/cse_config.sh
            The status should be success
            The stdout should eq "1"
        End

        It 'leaves no unguarded insert in cse_config.sh'
            # An -I on its own line, not preceded by the -C guard, is the pre-fix pattern.
            When call grep -c '^iptables -I FORWARD -d 168.63.129.16' ./parts/linux/cloud-init/artifacts/cse_config.sh
            The status should eq 1
            The stdout should eq "0"
        End
    End
End
