#shellcheck shell=bash
#shellcheck disable=SC2148

Describe 'mcr-hosts-setup.sh'

    Describe 'DNS resolution and hosts file creation'
        # Mock dig command to return test IPs
        dig() {
            case "$3" in
                A)
                    echo "1.2.3.4"
                    echo "5.6.7.8"
                    ;;
                AAAA)
                    echo "2001:db8::1"
                    echo "2001:db8::2"
                    ;;
            esac
        }

        setup() {
            TEST_DIR="/tmp/mcrhostssetuptest"
            mkdir -p "$TEST_DIR"

            HOSTS_FILE="${TEST_DIR}/etc/hosts.testing"
            mkdir -p "$(dirname "$HOSTS_FILE")"
        }

        cleanup() {
            rm -rf "$TEST_DIR"
        }

        BeforeEach 'setup'
        AfterEach 'cleanup'

        It 'creates hosts file with resolved addresses'
            DOMAIN="mcr.microsoft.com"

            # Simulate script logic
            IPV4_ADDRS=$(dig +short A "${DOMAIN}" | grep -E '^[0-9]+\.' || true)
            IPV6_ADDRS=$(dig +short AAAA "${DOMAIN}" | grep -E '^[0-9a-f:]+' || true)

            {
                echo "# MCR addresses resolved at $(date)"
                echo "# This file is automatically generated by mcr-hosts-setup.service"
                echo ""

                if [ -n "${IPV4_ADDRS}" ]; then
                    echo "# IPv4 addresses"
                    for addr in ${IPV4_ADDRS}; do
                        echo "${addr} ${DOMAIN}"
                    done
                fi

                if [ -n "${IPV6_ADDRS}" ]; then
                    echo ""
                    echo "# IPv6 addresses"
                    for addr in ${IPV6_ADDRS}; do
                        echo "${addr} ${DOMAIN}"
                    done
                fi
            } > "${HOSTS_FILE}"

            When call test -f "$HOSTS_FILE"
            The status should be success
            The file "$HOSTS_FILE" should be exist
        End

        It 'includes IPv4 addresses in hosts file'
            Skip if "not implemented yet" test -z "$SKIP_THIS_TEST"

            DOMAIN="mcr.microsoft.com"
            IPV4_ADDRS=$(dig +short A "${DOMAIN}" | grep -E '^[0-9]+\.' || true)

            {
                for addr in ${IPV4_ADDRS}; do
                    echo "${addr} ${DOMAIN}"
                done
            } > "${HOSTS_FILE}"

            The contents of file "$HOSTS_FILE" should include "1.2.3.4 mcr.microsoft.com"
            The contents of file "$HOSTS_FILE" should include "5.6.7.8 mcr.microsoft.com"
        End

        It 'includes IPv6 addresses in hosts file'
            Skip if "not implemented yet" test -z "$SKIP_THIS_TEST"

            DOMAIN="mcr.microsoft.com"
            IPV6_ADDRS=$(dig +short AAAA "${DOMAIN}" | grep -E '^[0-9a-f:]+' || true)

            {
                for addr in ${IPV6_ADDRS}; do
                    echo "${addr} ${DOMAIN}"
                done
            } > "${HOSTS_FILE}"

            The contents of file "$HOSTS_FILE" should include "2001:db8::1 mcr.microsoft.com"
            The contents of file "$HOSTS_FILE" should include "2001:db8::2 mcr.microsoft.com"
        End
    End
End
