name: Auto-update
# Auto-update only listens to `push` events.
# If a pull request is already outdated when enabling auto-merge, manually click on the "Update branch" button a first time to avoid having to wait for another commit to land on the base branch for the pull request to be updated.
on:
  push:
    branches:
      - master

jobs:
  Auto:
    name: Auto-update
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - uses: tibdex/auto-update@4081c5bdc34560b58288a010318054e63e6f4a51 # v2.2.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
