name: check-shell
on: pull_request

jobs:
  check-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.16'
    - run: |
        make validate-shell
      name: Verify Shell scripts
