name: check-generated
on: pull_request

jobs:
  check-generated:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v3
      with:
        go-version: '^1.16'
    - run: |
        make
        git diff --exit-code
      name: Make generate and diff
