name: Commit Message Lint

on:
  pull_request:
    branches:
      - master
      - 'official/*'

jobs:
  commit-message-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install commitlint
      run: |
        npm install commitlint@latest  @commitlint/config-conventional conventional-changelog-conventionalcommits
    - name: Validate PR commits with commitlint
      if: github.event_name == 'pull_request'
      run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
