name: Windows Powershell Unit Test
on: pull_request

# To run these tests on a Windows machine, you can use the commands below. However, most people have their git repo
# stored in WSL. So you'll need to change directory to whereever you have the repo checked out in WSL. Something like this:
# cd \\wsl$\Ubuntu\home\tim\git\AgentBaker

jobs:
  pester-test:
    name: Pester test
    runs-on: windows-latest
    permissions:
      checks: write
      issues: write
      pull-requests: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: Perform a Pester test from the parts/windows/*.tests.ps1 file
        if: (!cancelled())
        shell: powershell
        run: |

          Get-Module -ListAvailable -Name Pester
          if (-not (Test-Path test-results)) { New-Item -ItemType Directory -Force test-results | Out-Null }

          $config = New-PesterConfiguration
          $config.Run.Path = "parts/windows/*.tests.ps1"
          #$config.CodeCoverage.CoveragePercentTarget = 80
          $config.CodeCoverage.OutputPath = "test-results/coverage_parts_windows.xml"
          $config.CodeCoverage.Enabled = $true
          $config.CodeCoverage.ExcludeTests = $true
          $config.CodeCoverage.OutputFormat = JaCoCo
          $config.TestResult.Enabled = $true
          $config.TestResult.OutputFormat = "JUnitXml"
          $config.TestResult.OutputPath = "test-results/parts_windows.xml"
          Invoke-Pester -Configuration $config

      - name: Perform a Pester test from the vhdbuilder/packer/windows/*.tests.ps1 file
        if: (!cancelled())
        shell: pwsh
        run: |
          Get-Module -ListAvailable -Name Pester
          if (-not (Test-Path test-results)) { New-Item -ItemType Directory -Force test-results | Out-Null }

           $config = New-PesterConfiguration
          $config.Run.Path = "vhdbuilder/packer/windows/*.tests.ps1"
          #$config.CodeCoverage.CoveragePercentTarget = 80
          $config.CodeCoverage.OutputPath = "test-results/coverage_vhdbuilder_packer_windows.xml"
          $config.CodeCoverage.Enabled = $true
          $config.CodeCoverage.ExcludeTests = $true
          $config.CodeCoverage.OutputFormat = JaCoCo
          $config.TestResult.Enabled = $true
          $config.TestResult.OutputFormat = "JUnitXml"
          $config.TestResult.OutputPath = "test-results/vhdbuilder_packer_windows.xml"
          Invoke-Pester -Configuration $config

      - name: Perform a Pester test from the staging/cse/windows/*.tests.ps1 file
        if: (!cancelled())
        shell: powershell
        run: |
          Get-Module -ListAvailable -Name Pester
          if (-not (Test-Path test-results)) { New-Item -ItemType Directory -Force test-results | Out-Null }
          Install-Module -Name powershell-yaml -Force

          $config = New-PesterConfiguration
          $config.Run.Path = "staging/cse/windows/*.tests.ps1"
          #$config.CodeCoverage.CoveragePercentTarget = 80
          $config.CodeCoverage.OutputPath = "test-results/coverage_staging_cse_windows.xml"
          $config.CodeCoverage.Enabled = $true
          $config.CodeCoverage.ExcludeTests = $true
          $config.CodeCoverage.OutputFormat = JaCoCo
          $config.TestResult.Enabled = $true
          $config.TestResult.OutputFormat = "JUnitXml"
          $config.TestResult.OutputPath = "test-results/staging_cse_windows.xml"
          Invoke-Pester -Configuration $config

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/windows@v2
        if: (!cancelled())
        with:
          files: |
            test-results/parts_windows.xml
            test-results/vhdbuilder_packer_windows.xml
            test-results/staging_cse_windows.xml
