name: validate-pull-request-source
on: pull_request

jobs:
  validate-pull-request-source:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Validate if PR is not from a forked repo
        run: |
          if [ "${GITHUB_EVENT_PULL_REQUEST_HEAD_REPO_FULL_NAME}" != "${{ github.repository }}" ]; then
            echo "Please create the PR from a branch in this repository, not from a forked repository."
            exit 1
          else
            echo "PR is from a branch in this repository."
          fi
        env:
          GITHUB_EVENT_PULL_REQUEST_HEAD_REPO_FULL_NAME: ${{ github.event.pull_request.head.repo.full_name }}
