name: Windows Powershell Unit Test
on: pull_request

# To run these tests on a Windows machine, you can use the commands below. However, most people have their git repo
# stored in WSL. So you'll need to change directory to whereever you have the repo checked out in WSL. Something like this:
# cd \\wsl$\Ubuntu\home\tim\git\AgentBaker

jobs:
  pester-test:
    name: Pester test
    runs-on: windows-latest
    permissions:
      checks: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: Perform a Pester test from the parts/windows/*.tests.ps1 file
        if: (!cancelled())
        shell: powershell
        run: |
          Get-Module -ListAvailable -Name Pester
          Invoke-Pester parts/windows/*.tests.ps1 -Passthru -OutputFile test-results/parts_windows.xml -OutputFormat JUnitXML
      - name: Perform a Pester test from the vhdbuilder/packer/windows/*.tests.ps1 file
        if: (!cancelled())
        shell: pwsh
        run: |
          Get-Module -ListAvailable -Name Pester
          Invoke-Pester vhdbuilder/packer/windows/*.tests.ps1 -Passthru -OutputFile test-results/vhdbuilder_packer_windows.xml -OutputFormat JUnitXML
      - name: Perform a Pester test from the staging/cse/windows/*.tests.ps1 file
        if: (!cancelled())
        shell: powershell
        run: |
          Get-Module -ListAvailable -Name Pester
          Install-Module -Name powershell-yaml -Force
          Invoke-Pester staging/cse/windows/*.tests.ps1 -Passthru -OutputFile test-results/staging_cse_windows.xml -OutputFormat JUnitXML
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/windows@v2
        if: (!cancelled())
        with:
          files: |
            test-results/parts_windows.xml
            test-results/vhdbuilder_packer_windows.xml
            test-results/staging_cse_windows.xml
