name: Lint Azure DevOps Pipeline Files
on:
  pull_request:
    paths:
      - '.pipelines/**'
      - '.yamllint.yaml'

permissions: {}

jobs:
  yamllint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: '3.x'
    - name: Install yamllint
      run: pip install yamllint
    - name: Lint ADO pipeline YAML with yamllint
      run: yamllint -c .yamllint.yaml -f colored .pipelines/
