package agent

import (
	"context"
	"fmt"
	"sort"
	"strings"

	"github.com/Azure/agentbaker/aks-node-controller/parser"
	aksnodeconfigv1 "github.com/Azure/agentbaker/aks-node-controller/pkg/gen/aksnodeconfig/v1"
	"github.com/Azure/agentbaker/aks-node-controller/pkg/gpu"
	"github.com/Azure/agentbaker/pkg/agent/datamodel"
)

// CSEEnvDiff represents a difference between NBC-generated and AKSNodeConfig-generated CSE env vars.
type CSEEnvDiff struct {
	// OnlyInNBC contains env vars present in NBC output but not in AKSNodeConfig output.
	OnlyInNBC map[string]string
	// OnlyInANC contains env vars present in AKSNodeConfig output but not in NBC output.
	OnlyInANC map[string]string
	// ValueMismatch contains env vars present in both but with different values.
	// Key is the var name, value is [nbcValue, ancValue].
	ValueMismatch map[string][2]string
}

// HasDifferences returns true if there are any differences between the two env var sets.
func (d *CSEEnvDiff) HasDifferences() bool {
	return len(d.OnlyInNBC) > 0 || len(d.OnlyInANC) > 0 || len(d.ValueMismatch) > 0
}

// String returns a human-readable summary of the differences.
func (d *CSEEnvDiff) String() string {
	if !d.HasDifferences() {
		return "no differences"
	}
	var sb strings.Builder
	if len(d.OnlyInNBC) > 0 {
		sb.WriteString("Only in NBC:\n")
		for _, k := range sortedKeys(d.OnlyInNBC) {
			fmt.Fprintf(&sb, "  %s=%s\n", k, d.OnlyInNBC[k])
		}
	}
	if len(d.OnlyInANC) > 0 {
		sb.WriteString("Only in AKSNodeConfig:\n")
		for _, k := range sortedKeys(d.OnlyInANC) {
			fmt.Fprintf(&sb, "  %s=%s\n", k, d.OnlyInANC[k])
		}
	}
	if len(d.ValueMismatch) > 0 {
		sb.WriteString("Value mismatches:\n")
		keys := make([]string, 0, len(d.ValueMismatch))
		for k := range d.ValueMismatch {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			v := d.ValueMismatch[k]
			fmt.Fprintf(&sb, "  %s:\n    NBC: %s\n    ANC: %s\n", k, v[0], v[1])
		}
	}
	return sb.String()
}

// CompareCSEEnvVars compares the CSE environment variables generated by the legacy NBC path
// (from NodeBootstrappingConfiguration) against those generated by the AKSNodeConfig path
// (from aks-node-controller's parser.GetCSEEnv).
//
// nbcConfig is the legacy NodeBootstrappingConfiguration used by baker.go to generate CSE.
// aksNodeConfig is the AKSNodeConfig proto that aks-node-controller would receive.
// gpuConfig is the GPU configuration (can be nil for non-GPU nodes).
func CompareCSEEnvVars(ctx context.Context, nbcConfig *datamodel.NodeBootstrappingConfiguration, aksNodeConfig *aksnodeconfigv1.Configuration, gpuConfig *gpu.GPUConfiguration) *CSEEnvDiff {
	// Generate env vars from the AKSNodeConfig path (what aks-node-controller produces)
	ancEnv := parser.GetCSEEnv(ctx, aksNodeConfig, gpuConfig)

	// Generate env vars from the NBC path (what baker.go produces via getCSECommandVariables)
	nbcEnv := getNBCEnvMap(nbcConfig)

	return diffEnvMaps(nbcEnv, ancEnv)
}

// getNBCEnvMap converts the NBC's CSE command variables into a flat string map
// comparable to the AKSNodeConfig env var output.
func getNBCEnvMap(config *datamodel.NodeBootstrappingConfiguration) map[string]string {
	variables := getCSECommandVariables(config)
	result := make(map[string]string, len(variables))
	for k, v := range variables {
		result[strings.ToUpper(k)] = fmt.Sprintf("%v", v)
	}
	return result
}

// diffEnvMaps compares two env var maps and returns the differences.
func diffEnvMaps(nbcEnv, ancEnv map[string]string) *CSEEnvDiff {
	diff := &CSEEnvDiff{
		OnlyInNBC:     make(map[string]string),
		OnlyInANC:     make(map[string]string),
		ValueMismatch: make(map[string][2]string),
	}

	for k, nbcVal := range nbcEnv {
		ancVal, exists := ancEnv[k]
		if !exists {
			diff.OnlyInNBC[k] = nbcVal
		} else if nbcVal != ancVal {
			diff.ValueMismatch[k] = [2]string{nbcVal, ancVal}
		}
	}

	for k, ancVal := range ancEnv {
		if _, exists := nbcEnv[k]; !exists {
			diff.OnlyInANC[k] = ancVal
		}
	}

	return diff
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
